.github/workflows/CI.yml
codecov.yml
package.json

- adds code coverage checking
make sure it's safe

Add coverage checking

---

.github/workflows/CI.yml

try using nvm

---

.eslintrc
.github/workflows/CI.yml
package.json
tsconfig.build.json
tsconfig.json

add build step

---

codecov.yml
src/third-party-tags/permutive.ts
src/types.ts

adds permutive tage
first test module

add permutive

---

.github/workflows/CI.yml
.github/workflows/release.yml
package.json
yarn.lock

add first pass at using [semantic release](https://github.com/semantic-release/semantic-release)
take away some pain and enforce consistency

First pass at semantic releases

---

.github/workflows/CI.yml

Use coveralls instead

---

README.md
package.json
yarn.lock

Add commitzen

---

.github/workflows/CI.yml

this should not trigger release job 🙏

gonna need deps

---

src/third-party-tags/ias.ts

feat: 🎸 add IAS third-party tag

---

package.json
yarn.lock

chore: 🤖 make repo commitzen-friendly 🤗

---

.github/workflows/CI.yml
.releaserc.json
package.json

Use release personal token

---

package.json
yarn.lock

adds commitlint
make sure commits are formatted correctly if you don't use `git commit` from the command line

Add commitlint

---

.github/workflows/CI.yml
README.md

Add doctoc in CI

---

.github/workflows/CI.yml
README.md

docs: limit toc to 3 headers deep

---

package.json
yarn.lock

chore(deps): bumps deps

---

src/third-party-tags/facebook-pixel.spec.ts
src/third-party-tags/ias.spec.ts
src/third-party-tags/permutive.spec.ts

Fix fb coverage

---

src/index.ts
src/third-party-tags/remarketing.spec.ts

exports ThirdPartyTag type
to be used in frontend

fix: export TPT type 

---

src/EventTimer.ts

Add slot ready event
To capture the time when slot is ready

feat: Add slot ready event

---

.github/workflows/CI.yml

uses guardian/actions-setup-node
cleaner

chore: use guardian/actions-setup-node

---

yarn.lock

Update deps of @dependabot
Stay up to date

chore(deps): Bump deps 22/5/20

---

package.json
yarn.lock

chore: Bump deps 2021.04.16

---

src/third-party-tags/remarketing.spec.ts
yarn.lock

chore(deps): Bump dependencies 2021.05.25

---

yarn.lock

chore(deps): Bump dependencies 2021.06.02

---

package.json
yarn.lock

chore(deps): Bump dependencies 2021.06.22

---

package.json
yarn.lock

chore(deps): Bump dependencies 2021.07.13

---

yarn.lock

chore(deps): Bump dependencies 2021.07.20

---

package.json
yarn.lock

chore(deps): Bump dependencies 2021.07.27

---

yarn.lock

chore(deps-dev): Bump dependencies 2021.08.24

---

package.json
yarn.lock

Bump dependencies.
Keep things up to date.

chore: Bump deps 2021 09 14

---

src/sendCommercialMetrics.spec.ts
src/sendCommercialMetrics.ts
yarn.lock

Adds an extra parameter to the `sendCommercialMetrics` function which is put into the `properties` of the payload.
We want to collect data on readers' use of ad blockers.

feat: Add ad block property to `sendCommercialMetrics `

---

package.json
yarn.lock

chore(deps): Bump dependencies 2021.09.22

---

yarn.lock

chore(deps): Bump dependencies 2021.09.27

---

.vscode/settings.json
src/EventTimer.ts
src/GoogleAnalytics.spec.ts
src/targeting/personalised.ts
src/third-party-tags/ias.spec.ts
src/types.ts

Fixes spelling mistakes, and add jargon to the local dictionary.
Easier on the eyes!

chore(spelling): Fix spelling typos

---

src/third-party-tags/facebook-pixel.ts
src/third-party-tags/ias.ts
src/third-party-tags/inizio.ts
src/third-party-tags/permutive.ts
src/third-party-tags/remarketing.ts
src/third-party-tags/twitter-uwt.ts

Adds documentation comments for commercial modules
This should improve understanding of what these files do

docs: Document third party tags

---

.github/workflows/CD.yml
.github/workflows/CI.yml
yarn.lock

Updates dependencies by cherry-picking dependabot commits
```
git cherry-pick e511cbe
git cherry-pick 36a42b4
git cherry-pick 134210d
git cherry-pick cc4d448
git cherry-pick 2537769
git cherry-pick 016cbea
git cherry-pick 98b01fd
```

chore(deps): Bump dependencies 2022.03.09

---

src/ad-sizes.test.ts
src/ad-sizes.ts

Remove the `video` ad size
It is never used

fix: Remove `video` ad size

---

docs/e2e-testing/# E2E testing.md

Add documentation for our plan for end-to-end testing.

docs: Add E2E testing doc

---

yarn.lock

chore: Bump deps 2022-05-12

---

package.json
yarn.lock

chore: Bump deps 2022-05-18

---

package.json
yarn.lock

chore(deps): Bump deps 2022-07-01

---

yarn.lock

chore: Bump deps 2022-07-21

---

package.json
yarn.lock

chore: Bump deps 2022-08-25

---

yarn.lock

chore: Bump deps 2022-08-29

---

package.json
yarn.lock

chore: Bump deps 2022-09-01

---

src/index.ts
src/messenger.spec.ts
src/messenger.ts
src/messenger/post-message.ts

Migrate `messenger.ts`, it's test and `post-message.ts` to commercial-core

feat: Migrate messenger

---

src/index.ts

Oopsy, I forgot in https://github.com/guardian/commercial-core/pull/686

feat: Export `PageTargeting` type

---

.github/workflows/CD.yml
src/event-timer.ts
src/global.ts
src/send-commercial-metrics.ts
yarn.lock

chore: Bump deps 2022.10.31

---

yarn.lock

chore: Bump deps 2022-11- 24

---

.eslintrc.json
.github/workflows/CI.yml
.github/workflows/snyk.yml
.prettierignore
.releaserc.json
.vscode/settings.json
README.md
docs/google-ad-manager-advertising/readme.md
docs/header-bidding/readme.md
docs/migration/migration.md
package.json
src/targeting/personalised.spec.ts
src/targeting/youtube-ima.ts
tsconfig.build.json
tsconfig.json
yarn.lock

Adds prettier to CI github action and commitlint
README.md needs to be ignored, as the TOC generator action disagrees with prettier
prettier code

ci: Add prettier to CI

---

yarn.lock

chore: Bump deps 2022-12-23

---

core/package.json
standalone/package.json
yarn.lock

chore: Bump deps 2023-01-17

---

.github/workflows/CI-standalone.yml
.github/workflows/standalone-e2e.yml
package.json
yarn.lock

remove standalone & cypress workspace entry from root `package.json`
There are some dependency resolution issues that need investigation, but we'd like releases to work asap.

ci: Temporary fix for releases

---

bundle/README.md
e2e/package.json

Add a readme to the bundle workspace
Helpful docs

docs: add readme.md commercial bundle

---

bundle/.eslintrc.js
bundle/src/bootstraps/standalone.commercial.ts
bundle/src/projects/commercial/modules/consentless/render-advert-label.ts
bundle/src/projects/commercial/modules/dfp/render-advert-label.ts

feat: Pull changes from frontend

---

.github/workflows/snyk.yml

Add `SKIP_SBT: true` as per [DCR workflow](https://github.com/guardian/dotcom-rendering/blob/3bdbef92bd4356bf2f05cce0eb67f31f6bd937c5/.github/workflows/dcr-snyk.yml) as we are getting the following snyk error:
```
Error: No file in /home/runner/work/commercial/commercial matched to [**/*.sbt,**/project/build.properties,**/project/**.{scala,sbt}], make sure you have checked out the target repository
```

fix: Update snyk.yml

---

.github/workflows/standalone-e2e.yml
e2e/cypress/e2e/parallel-1/consent.cy.ts
e2e/cypress/e2e/parallel-1/targeting.cy.ts
e2e/cypress/e2e/parallel-2/article-inline-slots.cy.ts
e2e/cypress/e2e/parallel-3/liveblog-inline-slots.cy.ts
e2e/cypress/e2e/parallel-3/liveblog-live-update.cy.ts
e2e/cypress/e2e/parallel-4/merchandising-high.cy.ts
e2e/cypress/e2e/parallel-4/merchandising.cy.ts
e2e/cypress/e2e/parallel-5/mostpop.cy.ts
e2e/cypress/e2e/parallel-5/right-slot.cy.ts
e2e/cypress/e2e/parallel-5/top-above-nav.cy.ts
e2e/cypress/support/commands.ts
yarn.lock

- parallel e2e tests
- only install production deps

chore: Parallel e2e tests

---

bundle/package.json
core/package.json
yarn.lock

Bump  @guardian/consent-management-platform@^12.0.0
Update all the things but mainly to align deps for https://github.com/guardian/frontend/pull/25892

chore!: @guardian/consent-management-platform@^12.0.0

---

bundle/README.md

Testing the new squash and merge repo setting to check if a ! postfix will perform a release
Update node instructions

docs!: Update node instructions

---

bundle/src/projects/common/modules/experiments/tests/eager-prebid.ts

Bump the test added in #811 to 5%

feat: bump eager prebid test to 5%

---

bundle/package.json
yarn.lock

Bump @guardian/commercial-core@^6.3.0 for #859

feat: Bump bundle core@^6.3.0

---

.eslintrc.js
src/core/send-commercial-metrics.ts
src/lib/dfp/fill-advert-slots.ts
src/lib/dfp/prepare-a9.ts
src/lib/elements-manager/targeting.ts
src/lib/header-bidding/prebid/bid-config.ts
src/lib/identity/api.ts
src/standalone.commercial.ts

Add [this rule](https://eslint.org/docs/latest/rules/no-else-return)
Tidier code

Add eslint no-else-return

---

src/lib/detect/detect-breakpoint.ts
src/lib/header-bidding/prebid/bid-config.spec.ts
src/lib/header-bidding/prebid/price-config.spec.ts
src/lib/header-bidding/slot-config.ts
src/lib/header-bidding/utils.spec.ts

Fixes noUncheckedIndexedAccess errors for files in the `header-bidding` folder
Reduces the number of these errors by 16.

Fix noUncheckedIndexedAccess errors for files in the header bidding folder

---

src/lib/messenger/get-stylesheet.ts
src/lib/messenger/passback.ts
src/lib/messenger/scroll.ts
src/lib/messenger/viewport.ts

Fixes the noUncheckedIndexedAccess errors in messenger files.
Reduces the total error count by 5.

Fix noUncheckedIndexedAccess errors for messenger files

---

.changeset/early-dolphins-speak.md
src/lib/experiments/ab.spec.ts
src/lib/identity/api.ts
src/lib/user-prefs.ts
src/lib/utils/$$.ts

Fixes instances of no unchecked indexed access errors in following files
```
src/lib/identity/api.ts
src/lib/utils/$$.ts
src/lib/user-prefs.ts
src/lib/experiments/ab.spec.ts
```
Better type safety

fix more noUncheckedIndexedAccess

---

.changeset/pretty-weeks-destroy.md
.eslintrc.js
src/lib/experiments/ab.spec.ts
src/lib/header-bidding/slot-config.ts
src/lib/messenger/resize.ts
src/lib/messenger/scroll.ts
src/lib/spacefinder/spacefinder.ts
src/lib/third-party-tags/imr-worldwide.ts
tsconfig.json

Thanks to the whole team's work over the last couple weeks we can now enable this tsconfig option!
Better type safety

Enable noUncheckedIndexedAccess

---

.changeset/fresh-pumpkins-taste.md
.github/workflows/beta-release-on-label.yml
.github/workflows/ci.yml
.github/workflows/e2e-cypress.yml
.github/workflows/e2e-visual.yml
.prettierignore
docs/dependabot/dependabot.md
package.json
scripts/dependamerge.sh
yarn.lock

- Combines open dependabot updates
- Adds `dependamerge.sh` (Thanks membership-frontend). A script to combine dependabot branches into one branch.
- Adds untracked file `.vscode/settings.json` to prettier ignore file
Stay up to date with dependabot

Dependabot updates

---

playwright/tests/parallel-4/pageskin.spec.ts
src/lib/dfp/init-slot-ias.ts

- Skip the playwright test that always fails on CI
- So all Playwright tests pass on CI. There will be a follow up PR to fix the failing test

Skip failing playwright test

---

.changeset/bright-clouds-flash.md
src/lib/header-bidding/prebid/bid-config.ts

Handle undefined testgroups and add a changeset for #1121

Handle undefined testgroups 

---

.changeset/glue-candle-expression.md

Add a Changeset that was missing from https://github.com/guardian/commercial/pull/1138.
To release this change.

Add Changeset for new Index site id

---

.changeset/nervous-guests-dress.md
jest.setupTestFrameworkScriptFile.js
package.json
src/header-bidding/prebid/prebid.spec.ts
yarn.lock

Upgrade prebid to 8.24.0
Mainly for security updates

Upgrade Prebid to v8.24.0

---

playwright/lib/load-page.ts
playwright/lib/util.ts

Log when a slot comes back unfilled from GAM
Useful to help find out if it was GAM, the test code or our code that resulted in the empty slot!

Log when a slot comes back unfilled in playwright

---

.changeset/red-parrots-watch.md
src/dfp/render-advert.ts

Reverts guardian/commercial#1194

Revert "collapse merchandise ad slots on viewport resize"

---

.changeset/odd-emus-clean.md
src/experiments/tests/prebid-kargo.ts

Still not getting high enough volumes for this test

Bump prebid kargo AB test to 8%

---

src/init/consented/prepare-prebid.ts

Add prefix to prebid consent log to make it clearer in the logs

Add prefix to prebid consent log

---

.github/dependabot.yml

This should allow dependabot to group updates into a single PR

Enable grouped dependabot PR

---

.changeset/small-ghosts-retire.md
package.json
pnpm-lock.yaml

Brings in changes for the sourcepoint config change ab test - https://github.com/guardian/csnx/pull/1507

bump @guardian/libs to 17.0.0

---

package.json
pnpm-lock.yaml
src/core/ad-sizes.ts
src/core/targeting/pick-targeting-values.ts
src/lib/header-bidding/slot-config.ts

Upgrade `@typescript-eslint/*` packages
Keep dependencies up to date

Upgrade `@typescript-eslint/*` packages

---

.changeset/gorgeous-camels-hunt.md
src/lib/header-bidding/prebid/bid-config.ts

Updates the value of the seenthis vertical video pubmatic placement ID.
We can set the integration live once this has been updated.

Update seenthis pubmatic placement ID

---

.changeset/wicked-worms-march.md
src/experiments/tests/new-header-bidding-endpoint.ts

Fix header-bidding test id

---

src/lib/header-bidding/a9/a9.spec.ts
src/lib/header-bidding/a9/a9.ts
src/types/global.ts

Reverts guardian/commercial#1799

Revert "unblock gumgum for specific ad slots"

---

.changeset/silent-houses-warn.md
package.json
playwright/benchmark/cmp-reject-all.setup.spec.ts
playwright/lib/cmp.ts
playwright/lib/load-page.ts
playwright/tests/consent.spec.ts
pnpm-lock.yaml

Bump @guardian/libs to 22.0.0
To keep up to date. 
Release Consent or Pay logic

Bump @guardian/libs to 22.0.0

---

src/lib/header-bidding/prebid/prebid.ts

Add permutive segments to magnite orbt2 config

add permutive segments to magnite/rubicon ortb2

---

src/define/define-slot.ts
src/lib/error/report-error.spec.ts
src/lib/error/report-error.ts
src/types/global.ts

We're getting a large number of these errors in Sentry, but we're not sure why!

Add sizeMapping to size mapping error message

---

src/experiments/tests/the-trade-desk.ts

Increase to the trade desk test to 10% in each variant
We have not reached sample size yet

Increase the trade desk test to 10% in each variant

---

src/experiments/tests/prebid-multibid.ts

We are extending the `prebid-multibid` test by 4 weeks to collect more data

extend prebid-multibid test
