guardian/commercial

- src/third-party-tags/facebook-pixel.ts
- src/third-party-tags/ias.spec.ts
- src/third-party-tags/ias.ts
- src/third-party-tags/permutive.spec.ts
- src/third-party-tags/permutive.ts
- src/types.ts
Sourcepoint Id is moved to `consent-management-platform` and name is used instead to use inside the `getConsentFor` 
https://github.com/guardian/consent-management-platform/pull/276
Will work with new cmp release
> chore: update sourcepointId to name

- .eslintrc
- jest.config.js
- package.json
- yarn.lock
- lints for explanations if you `eslint-disable`
info for the next viewer
> Require eslint disable explanation

- package.json
The hook for linting now runs pre-commit instead of pre-push
Linter runs on staged files, but was setup to run on pre-push which is odd. Now it runs pre-commit
> build(package.json): linting now runs pre-commit instead of pre-push

- package.json
in lint-staged was incorrect
Corrects the syntax
The library uses https://github.com/micromatch/micromatch which needs bar for or not commas
> build(package.json): syntax for glob to select files 

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/semantic-PRs.yml
- package.json
- lints PRs for conventional commit compliance, rather than individual commits
- we should get the benefit of automatic semantic release without getting too involved with individual developer's ways of working
> ci: Semantic PRs

- src/GoogleAnalytics.ts
Tracker name will default to the one set in `ga.create` if not set 
To keep monitoring events without tracker name specified in window.config
> feat: make trackername optional

- src/EventTimer.ts
- src/GoogleAnalytics.ts
Improves some edge cases.
- Don't push an empty mark if it doesn't exist
- Don't throw an error if ga doesn't exist - it could happen possibly - we just don't measure the event in this case
It will remove some errors we have seen recently
> fix: Improve some edge cases

- src/EventTimer.ts
Performance API seems to be undefined on mobiles. 
It got picked up by Sentry here:
https://sentry.io/organizations/the-guardian/issues/2246881950/?project=35463&query=is%3Aunresolved
Also refactored mark to void as the return is not used
Less errors in sentry
> fix: call mark if performance API exists

- package.json
- yarn.lock
Update dependencies using @dependenbot’s commits.
Safe in the knowledge that everything is up-to-date.
> chore(deps): Weekly dependencies bump 2021.03.16

- .github/workflows/CD.yml
Enables `validateSingleCommit`, which was added in [`action-semantic-pull-request` 3.4.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v3.4.0)
We’ve been bitten before!
> chore(CD): Validate single commit

- package.json
- yarn.lock
- Bump `ts-jest` to the latest version.
- Bump `eslint` to [7.23.0](https://github.com/eslint/eslint/releases)
- Bump Husky to v6.
Keep @dependabot happy.
> chore(deps): Bump deps 2021.03.29

- yarn.lock
Update dependencies using @dependenbot’s commits.
Safe in the knowledge that everything is up-to-date.
> chore: Weekly dependencies bump 2021.04.07

- yarn.lock
Bump dependencies.
- bump `@typescript-eslint/parser` from 4.21.0 to 4.22.0
- bump `eslint-config-prettier` from 8.1.0 to 8.2.0
- bump `eslint-plugin-prettier` from 3.3.1 to 3.4.0
- bump `ts-jest` from 26.5.4 to 26.5.5
Keep @dependabot happy.
> chore(deps): Bump deps 2021.04.20

- yarn.lock
Bump dependencies.
bump eslint-config-prettier from 8.2.0 to 8.3.0 
bump eslint from 7.24.0 to 7.25.0 
bump eslint-plugin-jest from 24.3.5 to 24.3.6
Keep @dependabot happy.
> chore(deps): Bump deps 2021.04.27

- .github/workflows/CI.yml
ensures that test coverage is run on PR creation too, which in turn ensures that PRs are compared against main, not themselves
accurate coverage change reporting
> chore: run jobs on PRs

- package.json
- src/index.ts
- src/sendCommercialMetrics.spec.ts
- src/sendCommercialMetrics.ts
- yarn.lock
Moves logic around sending commercial metrics from front end
- Keeps more commercial-specific code in commercial-core
- Makes logic more reusable especially in migration from frontend to DCR
> feat: Send commercial metrics

- src/sendCommercialMetrics.spec.ts
- src/sendCommercialMetrics.ts
Filters event timer properties with undefined values.
~Also introduces a `PropertyEntry` type and annotation in order to prevent a [no-unnecessary-condition
](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md) eslint errror.~
Prevents undefined properties being included and sent with commercial metrics.
> fix: Filter eventTimer properties with undefined values

- src/EventTimer.spec.ts
- src/GoogleAnalytics.spec.ts
- src/third-party-tags/inizio.spec.ts
- src/third-party-tags/inizio.ts
This PR adds:
- Additional unit tests to EventTimer, testing multiple events and `mark`.
- Additional unit tests to the Inizio third party tag.
- Unit tests for google analytics.
Increase code coverage!
> test: Additional unit tests for event timer, Inizio and Google Analytics

- src/sendCommercialMetrics.spec.ts
- src/sendCommercialMetrics.ts
Stop sending `received_timestamp` and `received_date` as part of commercial metrics.
Commercial metrics will receive timestamps server-side (see https://github.com/guardian/fastly-edge-cache/pull/911).
> fix: Stop sending client-side date metrics

- README.md
Updates the ReadMe.
- We now have 100% coverage, and coveralls wasn’t picking up the main branch, it seemed
- We don’t release a cjs module, so bundlephobia cannot do its thing.
> docs: update coverage and remove bundlephobia link

- src/EventTimer.spec.ts
- tsconfig.json
Enable the `--noUncheckedIndexedAccess` flag and fix occurrences where indexed access now gives type errors.
More info is included in the [tsconfig documentation](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess).
Indexed accesses are typed as being possibly undefined, requiring explicit checking of whether values are undefined. For example:
```
const x = [1, 2, 3][3];
```
When the flag is not enabled this is typed as `x: number` even though its value is `undefined`. When the flag is enabled
`x: number | undefined` and requires more explicit handling of the `undefined` case in the code.
> refactor: Enable --noUncheckedIndexedAccess typescript flag

- src/EventTimer.spec.ts
- src/EventTimer.ts
Co-authored-by: Chris Jones <christopher.jones@guardian.co.uk>
This change adds CMP-related timers to `EventTimer`, allowing us to send SourcePoint timers to the data lake.
CMP events are not tracked by `EventTimer`'s `trigger` function (see example [here](https://github.com/guardian/consent-management-platform/blob/c404fd68dc629525f4a70e25dfc97fc419a1eb97/src/tcfv2/sourcepoint.ts#L46)), so a static array including CMP event names has been added to to the fields of the `EventTimer` class, as well as a getter function that concatenates `EventTimer`'s private events to the external consent timers.
The tracked events are:
- `cmp-[framework]-init`
-  `cmp-[framework]-got-consent`
where `[framework]` is one of `tcfv2`, `ccpa`, or `aus`. 
Because CMP events are now included in `EventTimer`, no …
> feat: Include CMP events in EventTimer

- src/GoogleAnalytics.ts
Sometimes window.ga is null, not undefined, and this previously caused a problem.
Checks if window.ga is a function, instead of checking if it's not undefined.
In some circumstance it appears that window.ga is set to null, when CCPA opt-out is applied, for example.
> fix: Error when window.ga is unavailable.

- src/global.ts
- src/types.ts
Move global types to a separate file, so they don’t get packaged.
This prevents clashing when trying to import this package in [`dotcom-rendering`](https://github.com/guardian/dotcom-rendering/pull/3152).
> fix: Isolate global types from package

- package.json
- src/types.ts
- yarn.lock
- run `yarn upgrade`
- remove unused type import
#318 didn’t close all of @dependabot’s PRs.
> chore(deps): Cleanup on 2021.07.27

- package.json
- yarn.lock
This PR migrates from the [`@guardian/types`](https://github.com/guardian/types) library to [`@guardian/libs`](https://github.com/guardian/libs) as [`@guardian/types` is now deprecated](https://github.com/guardian/types/pull/140).
For this repository, that simply means dropping `@guardian/types` from both `devDependencies` and `peerDependencies` as it wasn't being used anywhere.
Run all validation and ensure that everything still runs as expected.
> fix: Migrate from `@guardian/types` to `@guardian/libs`

- jest.config.js
- src/EventTimer.spec.ts
- src/GoogleAnalytics.spec.ts
- src/sendCommercialMetrics.spec.ts
- src/third-party-tags/inizio.spec.ts
- src/third-party-tags/remarketing.spec.ts
All our unit tests are meant to be running in the browser, so we set `testEnvironment` to `jsdom` in the Jest config.
> chore(tests): set testEnvironment globally

- yarn.lock
Bump dependencies.
Run `yarn upgrade` after doing a dep check so we catch as many package upgrades as possible.
> chore: Bump dependencies (again!) 2021-9-15

- src/ad-sizes.test.ts
- src/ad-sizes.ts
- src/index.ts
Migrate the size definitions that are currently defined separately in [frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/ad-sizes.js) and [DCR](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/AdSlot.tsx) to commercial core.
- Frontend and DCR size definitions won't need to be manually kept in sync.
- These are important definitions that can be appropriately documented here.
- One of the first steps in a longer-term goal to move commercial code out of frontend.
> feat: Migrate ad size definitions to commercial core

- src/detectAdBlocker.ts
- src/index.ts
- Move code implemented in [frontend](https://github.com/guardian/frontend/blob/3e91c6942494aabf089de63000a5eeb81ddf8405/common/app/templates/inlineJS/nonBlocking/detectAdblock.scala.js#L6) and [dcr](https://github.com/guardian/dotcom-rendering/blob/150fc2d81e6a66d9c3336185e874fc8cd0288546/dotcom-rendering/src/web/lib/detectAdBlocker.ts#L3) so that it can be shared.
- Add to the classes of the fake ad element and conditions under which we consider it to be blocked in order to make function more reliable for certain ad blockers (see [spreadsheet](https://docs.google.com/spreadsheets/d/18n2N5p8ARA4R2ySfe2-bvocCuvJjApdtbMu9fa1Ol8k/edit?usp=sharing)). Code borrowed from [just-detect-adblock](https://github.com/wmcmurray/just-detect-adblock)
- Remove duplicated code so that future changes can …
> feat: Detect ad blockers

- yarn.lock
Bumps more dependencies 
More popped up since yesterday's PR: https://github.com/guardian/commercial-core/pull/401
> chore(deps): Bump dependencies 2021.10.19

- src/index.ts
Add an exported type for `atoms-rendering/YoutubeAtom`
> fix: export CustomParams type

- src/index.ts
Export constants from the package’s `index` file.
More consistent usage by consumers.
> fix: Export constants from index

- package.json
- pnpm-lock.yaml
This PR reverses the version bump of [@guardian/libs](https://github.com/guardian/libs) applied in #414. Instead we fix the version to `3.3.0` for both the development and peer dependency.
This resolves an an issue caused when using this package as a dependency of Dotcom Rendering. A runtime error occurred when trying to run the DCR server and was of the form `localStorage is not defined`. This appears to be caused by an attempt to use a browser API on the server.
The version can be returned to `^3` when a more suitable fix for the error is found upstream.
> fix: Fix @guardian/libs to version 3.3.0

- .gitignore
- package.json
- pnpm-lock.yaml
- src/global.ts
- src/third-party-tags/inizio.ts
- tsconfig.build.json
Use `@types/googletag` instead of `@types/doubleclick-gpt`. See guardian/frontend#24349.
The types are more restrictive, hence better.
> chore(deps-dev): Use `@types/googletag`

- .gitignore
- package.json
Removes a pre-install step introduced in #404.
It cannot be installed in `yarn` and `npm` packages.
> fix: allow installation in non-pnpm packages

- src/targeting/content.spec.ts
- src/targeting/content.ts
- src/types.ts
Adds types around Content Targeting, which as per the JSDoc:
```ts
/**
* Content Targeting comes from the server
*
* For a specific URL, it will only change on
* - a Composer/CAPI update
* - a rendering platform capability update
* - a main media update
* - a series tag update
* - a surge in page views per minute
*/
export type ContentTargeting = { /* … */ }
```
Returns key-value pairs based on CAPI content. Takes an optional `videoLength` parameter.
[Explore the IDE IntelliSense](https://github.dev/guardian/commercial-core/blob/6c10c1ea1624b9e2c9c67dabc3326a849402531b/src/targeting/content.ts)
JSDoc style means the documentation is as close as possible to the actual code.
> feat: Ad Targeting – Content

- .eslintrc.json
- src/ad-targeting-youtube.ts
- src/sendCommercialMetrics.ts
- src/targeting/personalised.spec.ts
- src/targeting/personalised.ts
- src/types.ts
Adds types around Content Targeting, which as per the JSDoc:
```ts
/**
* Personalised Targeting requires user consent
*
* It allows or prevents personalised advertising, restrict data processing
* and handles access to cookies and localstorage
*/
export type PersonalisedTargeting = { /* … */ }
```
Returns key-value pairs based on user consent. Will remove existing data in local storage if no consent is given.
[Explore the IDE IntelliSense](https://github.dev/guardian/commercial-core/blob/fc234df1c466f586df6e6f364077bac82903ad74/src/targeting/personalised.ts)
JSDoc style means the documentation is as close as possible to the actual code.
> feat: Ad Targeting – Personalised

- package.json
- pnpm-lock.yaml
- src/targeting/session.spec.ts
- src/targeting/session.ts
Adds types around Sessions Targeting, which as per the JSDoc:
```ts
/**
* Session Targeting is based on the browser session
*
* Includes information such as the country of origin, referrer, page view ID.
*
* These values identify a browser session are either generated client-side,
* read from a cookie or passed down from the server.
*/
export type SessionTargeting = { /* … */ }
```
Returns key-value pairs based on the browser session. Requires an object containing server-side and client-side A/B test participations.
[Explore the IDE IntelliSense](https://github.dev/guardian/commercial-core/blob/9023662/src/targeting/session.ts)
JSDoc style means the documentation is as close as possible to the actual code.
> feat: Ad Targeting – Session

- src/EventTimer.spec.ts
- src/EventTimer.ts
Makes `trigger` and `trackInGA` private methods of `EventTimer`
Note: contrary to the PR title, this isn't a really feature but needs to be labeled as such in order to trigger a minor release when merged.
- Consumers should use `EventTimer.trigger` rather than `.mark` so that we 
-  track events with Google Analytics
- de-dup events (?)
We can enforce the use of `trigger` by making the other two methods private.
> feat: `EventTimer.mark` and `.trackInGA` are private methods

- yarn.lock
- chore(deps-dev): bump jest from 27.4.2 to 27.4.3
- chore(deps-dev): bump prettier from 2.5.0 to 2.5.1
- chore(deps-dev): bump ts-jest from 27.0.7 to 27.1.0
Keep @dependabot happy! 🤖
> chore(deps): Bump dependencies 2021-12-08

- package.json
- src/targeting/pick-targeting-values.spec.ts
- src/targeting/pick-targeting-values.ts
- yarn.lock
- Fix an issue with arrays of valid and invalid strings
- Lean `type-fest` for the funny type
- Update tests to cover more explicitly what the type does
Easier to read!
> fix(types): Pick targeting keys + use `type-fest`

- yarn.lock
- chore(deps-dev): bump ts-jest from 27.1.0 to 27.1.2
- chore(deps-dev): bump typescript from 4.5.2 to 4.5.4
- chore(deps-dev): bump @typescript-eslint/eslint-plugin
- chore(deps-dev): bump @typescript-eslint/parser from 5.5.0 to 5.7.0
happy robot, happy dev
> chore(deps-dev): Bump dependencies 2021-12-21

- src/targeting/content.ts
- src/targeting/session.spec.ts
- src/targeting/session.ts
Unify the API to match other `get*Targeting` methods
Consistency!
> feat: unify getSessionTargeting API

- src/ad-sizes.test.ts
- src/ad-sizes.ts
As outlined in this [ticket](https://trello.com/c/nakVaVsO/1659-add-gettuple-method-to-commercial-core-ad-sizes), now that ad sizes have moved over to commercial core it makes sense for some helper functions to join them. This adds a `getTuple` function and `AdSizeTuple` type to `ad-sizes.ts`.
> feat: Add `getTuple` helper function to `ad-sizes.ts`

- src/ad-sizes.test.ts
- src/ad-sizes.ts
- src/index.ts
Refactor previous PR by replacing `getTuple` with `getAdSize` and changing the old `getAdSize` to a more accurate `createAdSize`. The tuples are no more. Also fix exports so imports from the @guardian/commercial-core package works properly.
This was the product of a mobbing session with @ashishpuliyel, @arelra, and @simonbyford in which we questioned what a tuple ( `[width: number, height: number]` ) offered which the `AdSize` object below doesn't: 
```
{
width: number;
height: number;
toString: () => AdSizeString;
}
``` 
Both contained width and height values, the latter just has a handy custom `toString` function. This seemed like a good opportunity to streamline the code, and will be followed up on with a corresponding PR in Frontend.
> feat: Replace `getTuple` with `getAdSize`

- src/EventTimer.spec.ts
- src/EventTimer.ts
Make the constructor private, to prevent people from doing `new EventTimer()` instead of `EventTimer.get()`.
Rely on the fact `performance.mark` returns the mark it created, so use that instead of going through all the marks and getting the last one. Fixed the tests so the mocks more closely match browser implementation.
The filtering of events is flipped so as to get rid of a type assertion. For `_externallyDefinedEventNames`, we now check if an entry exists, return an `Event` from it if id does, and return `undefined` otherwise. Then filter the resulting array for entries that are instances of `Event`.
Cleaner, probably faster, uses returns types from the API.
> fix(EventTimer): private constructor and rely on `performance.mark()`’s return

- package.json
- src/types.ts
- yarn.lock
changes the type of `ThirdPartyTag.name` from `string` to `VendorName`, an enum of the ~26 vendors [handled by the CMP](https://github.com/guardian/consent-management-platform/blob/e7cbfce74be59c7d4c0f765ff4c5a83c0b4717da/src/getConsentFor.ts#L9)
- `VendorName` is more specific than a `string` and so can help us avoid errors e.g. typos in vendor names
- Allows frontend's `third-party-tags.js` to be [converted to TypeScript](https://github.com/guardian/frontend/pull/24516)
> feat!: `ThirdPartyTag` type uses `VendorName`

- .releaserc.json
- package.json
- yarn.lock
- Add dev dependency [conventional-changelog-conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits)
- add preset `conventionalcommits` to `.releaserc`
This allows the use inclusion of `!` in commit messages to trigger major releases. 
Thanks @sndrs for finding the fix for the [same issue](https://github.com/guardian/consent-management-platform/pull/512) on the consent management platform.
> feat: Conventional commit

- src/ad-sizes.ts
Done while pairing with @mxdvl looking at `AdSize` types and tuples, just feels a bit easier to read.
> feat: Order ad size info alphabetically

- docs/spacefinder/readme.md
Makes some minor updates to the spacefinder readme
To improve its accuracy
I have noticed the readme doesn't cover one part of the process which is the [attempted insertion of an inline merchandising ad](https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/article-body-adverts.js#L239-L241). This happens before the inline ads are inserted. Depending on how exhaustive the docs are supposed to be (potentially not very..?) we should probably add a note about this too.
> docs: Small updates to spacefinder readme

- .github/workflows/CD.yml
- package.json
- yarn.lock
Upgrades the following dependencies:
- @commitlint/config-conventional 
- @types/jest from 27.0.3 to 27.4.0 
- amannn/action-semantic-pull-request 
- @commitlint/cli from 15.0.0 to 16.1.0 
- @guardian/libs from 3.5.1 to 3.6.1 
- lint-staged from 12.1.3 to 12.3.2
> chore(deps): Bump dependencies 2022.02.01

- src/targeting/viewport.spec.ts
- src/targeting/viewport.ts
Adjust the minimum width of the viewport for `findBreakpoint` to output `tablet` from `740` (the width of the `tablet` breakpoint) to `660` (the width of the `phablet` breakpoint).
Update the tests to reflect this change.
To match the current implementation in [Frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/common/modules/commercial/build-page-targeting.ts#L113-L128), where `phablet` width `660` also maps to `tablet` when generating page targeting.
> fix(targeting): Change minimum tablet width

- src/index.ts
- src/targeting/viewport.spec.ts
- src/targeting/viewport.ts
Export functions and types related to ad targeting, introduced in feature branches
- https://github.com/guardian/commercial-core/pull/421
- https://github.com/guardian/commercial-core/pull/422
- https://github.com/guardian/commercial-core/pull/423
- https://github.com/guardian/commercial-core/pull/424
- https://github.com/guardian/commercial-core/pull/455
This will replace the ad targeting implementations in Frontend and DCR (where targeting on AMP is different to that in the commercial bundle), after the changes in [Frontend #24498](https://github.com/guardian/frontend/pull/24498).
Secondly, this PR includes a small change to the type of `getViewportTargeting`, making it take an object rather than two arguments. This is so that it has a similar interface to the other targeting functions …
> feat: Export ad targeting and adjust `getViewportTargeting` arguments

- .github/workflows/CD.yml
- package.json
- yarn.lock
Co-authored-by: Lucy Monie Hall <lucy.monie-hall@guardian.co.uk>
Upgrade dependencies from Dependabot. This PR was created using the following command
```
git cherry-pick --allow-empty 436c880 eea467c 0ab757d f061305 25bca7a 2e570c8
```
To keep our dependencies up to date!
> chore(deps): Bump dependencies 2022.02.09

- src/EventTimer.spec.ts
- src/EventTimer.ts
Makes changes 2 and 3 from the diagram below:
- Renames the commercial timer event `commercialEnd` to `commercialModulesLoaded`
- Adds two commercial metrics, `commercialExtraModulesLoaded` and `commercialBaseModulesLoaded`
- The change from `commercialEnd` to `commercialModulesLoaded` reflects what has actually occurred when the metric is triggered; All commercial modules have been loaded (but haven't necessarily finished executing), but since more commercial events (e.g. initialising the first slot and showing the first ad) have yet to happen, `commercialEnd` could be misleading.
- `commercialExtraModulesLoaded` and `commercialBaseModulesLoaded` are [already being triggered](https://github.com/guardian/frontend/blob/fed5c0cbf116e432d1bdb58d64ce7d8ad904b386/static/src/javascripts/bootstra …
> feat: Update event timer names

- docs/spacefinder/readme.md
Add some info about how to debug `spacefinder`.
[There’s a visualiser!](https://github.com/guardian/frontend/pull/24618)
> docs: spacefinder debug mode

- src/EventTimer.ts
- src/index.ts
- src/track-scroll-depth.spec.ts
- src/track-scroll-depth.ts
Adds a function `initTrackScrollDepth` which collects commercial metrics on user scroll depth. It does this by inserting hidden elements at intervals of 1 viewport height, then using an intersection observer to mark the time when the viewport intersects with these elements with `EventTimer.trigger`.
We'd like to be more accurate in finding the optimal moment to load lazily-loaded ads and suspect that there may be a possible solution that considers scroll velocity. We're temporarily collecting scroll depth metrics in order as background research to help us with this.
- There will be some noise from inaccurate scroll depth metrics due to users resizing their window after the page loads
> feat: Collect commercial metrics on scroll depth

- src/EventTimer.ts
- Adds a new event timer property and allows it to be set by `setProperty`
- As part of the [frontend experiment](https://github.com/guardian/frontend/pull/24770) to find an optimal lazy load margin, we need to be able to record the margin values used for the variant group.
> feat: add property `lazyLoadMarginPercent` to `EventTimer`

- docs/migration/migration.md
Co-authored-by: Chris Jones <christopher.jones@guardian.co.uk>
Document to detail our plan to migrate code from Frontend to commercial-core.
To migrate out of an increasingly legacy platform.
> docs: Initial migration document

- .eslintrc.json
- src/ad-sizes.ts
- src/permutive.ts
- src/send-commercial-metrics.ts
- src/targeting/content.ts
- src/targeting/personalised.ts
- src/targeting/session.ts
- src/targeting/shared.ts
- src/targeting/viewport.ts
- src/types.ts
Introduce a new Eslint rule [`import/exports-last`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md) which enforces that all exports must be declared at the bottom of the file. Fix all occurrences where this isn't the case.
As part of a new [migration strategy](https://github.com/guardian/commercial-core/pull/530), we'd like to standardise on how we manage file exports. This rule ensures all exports are at the bottom of the file, making it easy where to check which values are exported.
We enforce this with an Eslint rule in order to automate checks for this.
Note that this rule only forces that all exports must occur at the bottom of the file, and that you can still use named exports, so long as they appear at the end. Hence the following would be …
> chore: Exports at bottom of files

- src/detect-ad-blocker.ts
- src/targeting/shared.ts
Co-authored-by: Max Duval <max.duval@theguardian.com>
Replace git.io links with resolved links as git.io will be deprecated on 2022-04-29:
https://github.blog/changelog/2022-04-25-git-io-deprecation
Used @mxdvl 's guide:
https://gist.github.com/mxdvl/eae14de45152bfec04c9d7c9786ad997
> chore: Replace git.io links with resolved links

- src/ad-sizes.ts
- src/index.ts
Add size mappings to `ad-sizes.ts` so they can be imported from DCR, rather than inline in the component.
I think right to move to this package? But not totally sure
Simplify how size mappings are managed.
> feat: add size mappings to ad-sizes.ts

- package.json
- src/ad-targeting-youtube.spec.ts
- src/send-commercial-metrics.spec.ts
- src/send-commercial-metrics.ts
- src/targeting/personalised.spec.ts
- yarn.lock
When in TCFv2 mode, check the user has consented to purpose 7 (measure ad performance) and 8 (measure content performance) of the TCF framework before sending commercial metrics to the server.
When in non-TCFv2 mode, no need to check anything.
Also makes some improvements to `send-commercial-metrics.spec.ts` which are easiest reviewed commit-by-commit. Some of these are down to taste and I'm definitely happy to be challenged if these go against any testing principles I'm not aware of!
We shouldn't be collecting metrics without consent
> feat: Get consent before sending commercial metrics

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- package.json
- yarn.lock
Upgrades the following dependencies:
@guardian/eslint-config-typescript
@types/jest from 27.4.0 to 27.5.0
@guardian/prettier from 0.7.0 to 1.0.0
@commitlint/config-conventional
amannn/action-semantic-pull-request
actions/upload-artifact from 2 to 3
actions/download-artifact from 2 to 3
> chore(deps): Bump dependencies 2022.05.09

- package.json
- yarn.lock
Bump deps 2022-05-24
[chore(deps-dev): bump eslint-plugin-import from 2.25.3 to 2.26.0](https://github.com/guardian/commercial-core/commit/f15c5c4cb19f102653583fe232f5960a7477e6fb) 
[chore(deps-dev): bump @typescript-eslint/parser from 5.23.0 to 5.25.0](https://github.com/guardian/commercial-core/commit/b17f1ef628b0c95d9f83f0ef88cebfdde098571a) 
[chore(deps-dev): bump @commitlint/config-conventional](https://github.com/guardian/commercial-core/commit/cb3dcb7e2920469415b8ee279b3e71ff1807bf10) 
[chore(deps-dev): bump eslint-plugin-jest from 26.1.5 to 26.2.2](https://github.com/guardian/commercial-core/commit/b51734159c1888e1745a77ea0f24424bcf052845) 
[chore(deps-dev): bump husky from 7.0.4 to 8.0.1](https://github.com/guardian/commercial-core/commit/9659d634f4ac918dfb0a4a44bc4d530978b0a55e)
> chore: Bump deps 2022-05-24

- package.json
- src/event-timer.ts
- src/index.ts
- src/track-gpc-signal.spec.ts
- src/track-gpc-signal.ts
- yarn.lock
Adds a function `initTrackGpcSignal` which collects metrics on the [GPC signal](https://globalprivacycontrol.org/#gpc-spec) when handed a `ConsentState` from the [guardian/consent-management-platform](https://github.com/guardian/consent-management-platform) library. 
We'd like to understand the commercial impact of the GPC signal on our platform and track any changes over time.
Depends on https://github.com/guardian/consent-management-platform/pull/606
> feat: Collect commercial metrics on GPC signal

- src/ad-sizes.ts
- src/create-ad-slot.spec.ts
- src/create-ad-slot.ts
- src/global.ts
- src/index.ts
- src/types.ts
Migrate create-ad-slot.ts and it's test to commerical-core
> feat: Migrate create-ad-slot.ts

- src/index.ts
We forgot to export `createAdSlot` in the mobbing session
> fix: export createAdSlot

- src/ad-sizes.ts
- src/create-ad-slot.ts
Copy frontend size mappings into ad-sizes
Sorry, yet another PR on ad sizes
Didn't do this initially because of the clash with the 'top-above-nav' name, but have noticed it's actually safe to do as frontend only uses the `mobile` size in the browser and dotcom the rest
This is needed in order to lookup the ad sizes in frontend, they _could_ be kept in separate objects but unnecessary I think and would require different object names etc.
> feat: Copy frontend size mappings into ad-sizes

- src/send-commercial-metrics.ts
Send commercial metrics a maximum of one time for each pageview.
@ashishpuliyel has a hypothesis that some of the outliers in the timing data is related to browsers that suspend the window, and then resume (tabs put into the background and resumed the next day for example).
The timers become somewhat meaningless once the tab has been put into the background, so we should stop the timers after that.
> fix: Only send commercial metrics once

- src/targeting/personalised.spec.ts
- src/targeting/personalised.ts
- Set cookie `amtgrp` if the user is in CCPA or aus, regardless of the user's consent state. This is because this cookie is not used for targeting/personalisation. It is used for A/B tests.
- Remove superfluous functions: `personalisedAdvertising` and `tcfv2AllPurposesConsented`.
- To correct logic whilst migrating commercial code over from frontend to commercial-core.
> feat: Add logic for setting Ad Manager group cookie

- src/ad-sizes.ts
Adding a new slot size mapping for the crossword banner ads that appear on tablet displays.
At the moment the crossword banner ad slot is not getting the right sizes of adverts, causing ads to overlap comments on the page. Adding this new size mapping is the first step towards fixing this bug.
> feat: Add crossword banner slot to slot size definitions

- src/ad-sizes.ts
- src/create-ad-slot.ts
- src/index.ts
- src/lib/breakpoint.spec.ts
- src/lib/breakpoint.ts
Deal with one of our `// TODO` markers by refactoring the `concatSizeMappings` function.
This requires the introduction of an `isBreakpoint` type guard - to ensure we don't concat additional keys in objects. Note that because of the use of `reduce` we won't affect the original size mappings.
> TODO
> feat: Refactor and export `concatSizeMappings`

- src/ad-sizes.ts
Adding the cascade banner size to our list of defined ad sizes
Trying to centralise our ad definitions to reduce the number of places that ad sizes are defined
> feat: Add the cascade banner size

- src/create-ad-slot.spec.ts
- src/create-ad-slot.ts
Removes anything to do with sizeMappings from `createAdSlot`, as they no longer need to be written to the data attributes.
They are redundant now, size mappings are now loaded from https://github.com/guardian/commercial-core/blob/main/src/ad-sizes.ts#L143 as of this frontend PR https://github.com/guardian/frontend/pull/25124
> feat: createAdSlot no longer adds size mappings data attrs

- src/ad-sizes.test.ts
- src/ad-sizes.ts
Adding a new function to return the array of a given ad size, and added some relevant tests to make sure the function behaves as expected.
This will be useful in frontend to make sure that we send arrays with working array methods on them, such as splice.
> feat: add new function to return the array of an ad size

- src/ad-sizes.test.ts
- src/ad-sizes.ts
- yarn.lock
Bump deps 2022-08-24
Bumping TypeScript seems to have flagged a new error:
```
error TS2564: Property '[0]' has no initializer and is not definitely assigned in the constructor
```
```
FAIL src/ad-sizes.test.ts
● Test suite failed to run
src/ad-sizes.ts:[23](https://github.com/guardian/commercial-core/runs/7992252393?check_suite_focus=true#step:5:24):11 - error TS2564: Property '[0]' has no initializer and is not definitely assigned in the constructor.
23  readonly [0]: number;
~~~
src/ad-sizes.ts:[24](https://github.com/guardian/commercial-core/runs/7992252393?check_suite_focus=true#step:5:25):11 - error TS[25](https://github.com/guardian/commercial-core/runs/7992252393?check_suite_focus=true#step:5:26)64: Property '[1]' has no initializer and is not definitely assigned in the …
```
> chore: Bump deps 2022-08-24

- src/event-timer.ts
- src/track-labs-container.ts
Co-Authored-By: Zeke Hunter-Green <17057932+zekehuntergreen@users.noreply.github.com>
Refactor `setProperty` so it takes into account the type of the property being set. Previously it only supported setting number values.
Now we can use `setProperty` in `initTrackLabsContainer` to set the boolean property `hasLabsContainer` instead of writing to the `properties` object directly, which wasn't a great solution.
> refactor: Refactor `setProperty`

- src/event-timer.ts
- src/track-labs-container.spec.ts
- src/track-labs-container.ts
Follows on from https://github.com/guardian/commercial-core/pull/665
Modifies `initTrackLabsContainer` to also capture `labsUrl` when a Guardian Labs container is present. 
In the below case, it would set `labsUrl` to `/a-vision-for-better-food`
So we know which campaign the reader saw.
> feat: Capture `labsUrl` when container is present

- yarn.lock
- Remove an old conventionalcommits entry from yarn.lock
It is no longer needed. I think we should have removed it in #659 but for some reason yarn didn't pick it up at the time.
Running `yarn` in the `main` branch creates this diff.
> chore: Remove old conventionalcommits entry from yarn.lock

- .github/workflows/CI.yml
add ` HUSKY_SKIP_HOOKS=1` to environment
potentially preventing semantic-release from publishing
> fix: skip husky hooks during release

- src/create-ad-slot.spec.ts
- src/create-ad-slot.ts
- src/event-timer.spec.ts
- src/global.ts
- src/google-analytics.spec.ts
- src/google-analytics.ts
- src/index.ts
- src/targeting/build-page-targeting.ts
- src/targeting/personalised.ts
- src/types.ts
Co-authored-by: Ravi <7014230+arelra@users.noreply.github.com>
Co-authored-by: Zeke Hunter-Green <zeke.huntergreen@guardian.co.uk>
Moves the logic to build page targeting from [frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/common/modules/commercial/build-page-targeting.ts). A subsequent PR in frontend will remove the old logic and instead call this method. After that, we'll do the same for DCR.
So we can standardise the way we build page targeting across DCR and frontend. Currently there is a lot of duplication and inconsistency.
> feat: Migrate `build-page-targeting` from frontend

- src/ad-sizes.ts
- src/constants/adLabelHeight.ts
- src/constants/index.spec.ts
- src/constants/index.ts
- src/constants/prebid-timeout.ts
- src/index.ts
1. Exports standard ad sizes
2. Adds ad label height to constants
1. So that in other apps we can distinguish between standard ad-sizes and sizes that are variable (e.g. fluid) or do not show up on the page (e.g. [1,1 ], [2, 2]) or look like a standard ad size but are actually variable (e.g. merchandising slot: [88, 87]). It will be useful in frontend to know if the top-above-ad is of a standard ad size or a fluid ad. I don't want to duplicate ad sizes in the frontend repo.
2. We define this constant in multiple places in both frontend and dotcom-rendering. Best to define it in one place that makes sense.
> feat: Export standard ad sizes

- src/index.ts
- src/targeting/build-page-targeting-consentless.ts
Co-Authored-By: Jake Lee Kennedy <jake@bodhi.io>
- adds function `buildPageTargetingConsentless` which calls the consented version, `buildPageTargeting` and returns only the targeting key / values needed for Opt Out integration
- Custom targeting functionality is needed to release our Opt Out integration, showing real ads to readers.
> feat: Build consentless page targeting

- src/create-ad-slot.spec.ts
- src/event-timer.spec.ts
- src/google-analytics.spec.ts
- src/lib/get-locale.spec.ts
- src/lib/get-locale.ts
- src/targeting/build-page-targeting-consentless.ts
- src/targeting/build-page-targeting.spec.ts
- src/targeting/build-page-targeting.ts
- src/types.ts
Co-authored-by: <ravi.lal.freelancer@guardian.co.uk>
- removes the parameter `countryCode` from `buildPageTargeting()`. The country code is instead calculated directly using a script [copied from `libs`](https://github.com/guardian/csnx/blob/main/libs/%40guardian/libs/src/locale/getLocale.ts) and modified to be synchronous
- adds a spec for `buildPageTargeting`. This was based on an [existing spec in frontend](https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/common/modules/commercial/build-page-targeting.spec.ts) which can now be removed
Fewer arguments mean the method is simpler to consume.
The spec always belonged here and not in frontend, [as acknowledged at the time](https://github.com/guardian/frontend/pull/25556#discussion_r988886343).
> feat: Remove `countryCode` parameter from `buildPageTargeting` and add spec

- src/__vendor/a9-apstag.js
- src/__vendor/ipsos-mori.js
- src/__vendor/launchpad.js
- src/__vendor/pubmatic.js
- src/index.ts
Add the following third party scripts from Frontend to the `__vendor` directory:
- Ipsos Mori stub
- A9 Apstag
- Launchpad (used by Redplanet)
- Pubmatic override (for using Permutive audiences with Pubmatic Prebid)
Note that for A9 and Launchpad we wrap the stubs in `() => void` functions, so we can defer their execution without using a dynamic import.
Collect more of our vendor third party code in one place. Make it clearer that this should remain as JavaScript.
> feat: Vendor scripts from Frontend

- README.md
Remove npm install suggestion from readme
We shouldn't encourage using a package manager other than yarn as the `yarn.lock` file won't be read or written to, and could cause inconsistent dependencies.
> chore: Remove npm suggestion from README

- src/lib/ab-localstorage.spec.ts
- src/lib/ab-localstorage.ts
- src/targeting/build-page-targeting-consentless.spec.ts
- src/targeting/build-page-targeting-consentless.ts
- src/targeting/build-page-targeting.spec.ts
- src/targeting/build-page-targeting.ts
Removes the parameter `clientSideParticipations` from `buildPageTargeting()`. The `clientSideParticipations` is instead calculated directly from localstorage.
> feat: Remove `clientSideParticipations` parameter from `buildPageTargeting`

- src/ad-targeting-youtube.ts
- src/index.ts
- src/targeting/build-page-targeting.ts
- src/targeting/session.ts
- src/targeting/youtube-ima.spec.ts
- src/targeting/youtube-ima.ts
Adds a utility function `buildImaAdTagUrl` for our YouTube IMA ads integration.
Once we have full targeting in commercial-core (coming soon) we will update to use that. For the moment this is a foundational piece of work to shift the building of the ad tag from DCR into commercial-core
This will construct an ad tag URL to be used by the YouTube IMA ads integration.
> feat: YouTube IMA AdTag builder

- src/index.ts
- src/targeting/build-page-targeting-consentless.ts
- src/targeting/build-page-targeting.spec.ts
- src/targeting/build-page-targeting.ts
- src/targeting/personalised.spec.ts
- src/targeting/personalised.ts
- src/targeting/youtube-ima.ts
- src/targeting/youtube.spec.ts
- src/targeting/youtube.ts
When `youtube` is set to `false`, `buildPageTargeting` pulls the regular permutive segments (i.e. those stored in localstorage under the key `_papns`). This was the default behaviour before this change.
When `youtube` is set to `true`, `buildPageTargeting` pulls the youtube-specific permutive segments (i.e. those stored in localstorage under the key `_pdfps`)
So we can finally start using `buildPageTargeting` in `buildAdsConfig`, which happens in [this commit](https://github.com/guardian/commercial-core/pull/708/commits/260f96ff78ab9d4789c64ad4be05bc5e25e8b5d1).
> feat: add `youtube` parameter to `buildPageTargeting`

- src/targeting/build-page-targeting-consentless.ts
- src/targeting/build-page-targeting.spec.ts
- src/targeting/build-page-targeting.ts
- src/targeting/youtube-ima.spec.ts
- src/targeting/youtube-ima.ts
- src/targeting/youtube.spec.ts
- src/targeting/youtube.ts
- adds back `clientSideParticipations` as a parameter to `build-page-targeting`.
- updates public YouTube targeting functions to accept an object rather than an array of parameters
We previously thought we could read test participations from localstorage. This works on Frontend but the [library that DCR uses](https://github.com/guardian/ab-testing) for ab testing [does not write to localstorage](https://github.com/guardian/ab-testing#differences-of-this-library-vs-frontend-implementation).
> feat: Pass client side test participations to targeting functions

- package.json
- yarn.lock
Bump dependencies for this week.
Cherry pick 4 Dependabot PRs, plus upgrade `@guardian/libs` to `10.0.0` so that we can remove our development dependency on `web-vitals` (this was required to run the test since it used to be a peer dep of libs).
~The remaining TypeScript upgrade will require a change to our TS setup, so will be addressed separately.~
The upgrade to TypeScript 4.9.3 required we pull in `@types/node` explicity - see [this dicsussion](https://github.com/microsoft/TypeScript/issues/51567) for more context.
Keep our dependencies up to date.
> chore(deps-dev): dependencies bump `2022-11-29`

- src/ad-sizes.test.ts
- src/ad-sizes.ts
Add the `320x480` size to our set of known ad sizes.
A small amount of drive-by refactoring as well: sorting the size keys, adding some short comments, and using `as const` in the test.
We'll need this size when we enable Picnic on mobile web.
> feat: Add `320x480` ad size

- src/create-ad-slot.spec.ts
- src/event-timer.spec.ts
- src/google-analytics.spec.ts
- src/targeting/viewport.spec.ts
- src/targeting/viewport.ts
- src/types.ts
Sets targeting `inskin: 'f'` when on the preview site
Page skins are rendering incorrectly in preview due to not finding the correct top.window.
We decided to turn them off entirely for editorial's preview environment ( h/t @ashishpuliyel )
> fix: Set targeting to not show page skins if on preview site

- src/event-timer.spec.ts
- src/event-timer.ts
- src/send-commercial-metrics.spec.ts
This changes the set of externally defined event names, removing all of the existing per-framework names and using ones that are framework-agnostic.
The three new event names:
- [`cmp-init`](https://github.com/search?q=repo%3Aguardian%2Fconsent-management-platform+cmp-init&type=code)
- [`cmp-ui-displayed`](https://github.com/search?q=repo%3Aguardian%2Fconsent-management-platform+cmp-ui-displayed&type=code)
- [`cmp-got-consent`](https://github.com/search?q=repo%3Aguardian%2Fconsent-management-platform+cmp-got-consent&type=code)
Some time ago the Consent Management Platform moved over to a ['unified implementation'](https://github.com/guardian/consent-management-platform/pull/561). In doing so, we stopped leaving the same unique performance marks for each of the three CMP frameworks. This …
> fix: Use unified CMP event names

- src/ad-sizes.ts
Remove the `320x480` size from our size mappings.
This size mapping was introduced as part of #735. We now only want to apply this size to certain inlines on articles, so we'll add it as an additional size in Frontend instead.
> fix!: Remove portrait interstitial from size mappings

- core/src/ad-sizes.ts
- Removes tall ads (skyscraper, half-page) from comments section
- Reordered breakpoints so that all are in ascending order
There is not enough room to display a tall ad without create a large amount of whitespace, pushing the content below down. Therefore we should limit this ad slot to ad sizes that can be placed without moving the content.
> fix: Remove tall ads from comments section

- yarn.lock
Chop old typescript versions out of the yarn.lock
We [currently resolve TypeScript to `~4.9.0`](https://github.com/guardian/commercial-core/blob/main/package.json#L40)
> chore: Update lockfile

- core/src/create-ad-slot.spec.ts
- core/src/event-timer.spec.ts
- core/src/google-analytics.spec.ts
- core/src/targeting/build-page-targeting-consentless.spec.ts
- core/src/targeting/build-page-targeting-consentless.ts
- core/src/targeting/build-page-targeting.spec.ts
- core/src/targeting/build-page-targeting.ts
- core/src/targeting/content.spec.ts
- core/src/targeting/content.ts
- core/src/types.ts
Adds a new targeting key-value `rc` ("Recently Published Content"). 
As per [this document](https://docs.google.com/document/d/1toiKkrrThWHB72GYFuirE2ktGnljwcOsdZbsr0DUTUU/edit#), the bucketing should work as follows:
| `rc` | Meaning |
| --- | --- |
| 0 | Content < 2 hours old |
| 1 | Content between 2 hours and 24 hours old |
| 2 | Content between 24 hours and 3 days old |
| 3 | Content between 3 and 7 days old |
| 4 | Content between 7 days and 1 month old |
| 5 | Content more than 1 month old but less than 10 months old |
| 6 | Content more than 10 months old less than 14 months old |
| 7 | Content more than 14 months old |
To allow line items to target content based on date of publication.
> feat: Add new targeting key-value `rc` ("Recently Published Content")

- core/.releaserc.json
semantic-release can only use npm to publish, which can't resolve dependencies for some reason, `yarn npm publish` should be able to do the trick https://yarnpkg.com/cli/npm/publish
> ci: use yarn to publish

- .github/workflows/standalone-e2e.yml
- bundle/webpack.config.dev.js
- bundle/webpack.config.js
- bundle/webpack.config.prod.js
webpack was only aliasing the `process` module in the dev build, so the prod build didn't actually work in the browser.
Also re-enable the E2E tests that would have caught this...
> fix(bundle): include used process.env.* in prod build

- core/src/event-timer.ts
- core/src/send-commercial-metrics.spec.ts
- core/src/send-commercial-metrics.ts
Record the `offlineCount` at the point the user navigates away, part of `gatherMetricsOnPageUnload`, rather than at the time of initialisation of `EventTimer`.
There’s a possibility that `EventTimer` is initialised before the user has experienced all their offline events.
Follow-up on #773
> fix(offlineCount): measure at page unload

- e2e/cypress/lib/util.ts
Redo of #799
I scheduled it wrong.
> fix(e2e): correct DCR dev server path

- core/src/send-commercial-metrics.spec.ts
- core/src/send-commercial-metrics.ts
Ensure we still collect `0` values.
`0` is falsy in JS – 🤦‍♂️
> fix: send offlineCount of `0`

- bundle/src/projects/commercial/modules/dfp/render-advert-label.ts
Updates the file location for the cross icon used in the mobile sticky close button
Currently the import does not point to the correct file location, leading to 'undefined' showing where the cross icon should appear
> fix: update file location for cross icon

- bundle/package.json
- bundle/src/projects/commercial/modules/consentless/render-advert-label.ts
- bundle/src/projects/commercial/modules/dfp/render-advert-label.ts
- bundle/src/types/global.d.ts
- bundle/webpack.config.js
- yarn.lock
We discovered it was due to a webpack 5 issue, replaced `svg-loader` with `raw-loader`
> fix(bundle): mobile sticky cross icon

- .github/workflows/visual-e2e.yml
- bundle/package.json
- bundle/src/projects/commercial/modules/dfp/create-advert.ts
- bundle/src/projects/common/modules/article/space-filler.ts
- bundle/src/projects/common/modules/spacefinder-debug-tools.ts
- e2e/cypress/fixtures/api/long-read.ts
- e2e/cypress/lib/rewriteGamRequest.ts
- e2e/cypress/lib/stubApiRequests.ts
- e2e/cypress/lib/util.ts
- e2e/cypress/snapshot/snapshot-article-long-read.cy.ts
- e2e/cypress/snapshot/snapshot-article-standard.cy.ts
- e2e/cypress/support/commands.ts
- e2e/cypress/support/e2e.ts
- yarn.lock
One last run of the migration script from Frontend brings in:
- exclude DuckDuckGo from 'could not create advert' errors https://github.com/guardian/commercial/pull/810/commits/c1e2e36b5ac5a84fc2d0135660f627d07cf10e61
- spacefiller-complete event https://github.com/guardian/commercial/pull/810/commits/543036b2608c5105cba1ba471e74f0af8c4403d0
- e2e visual tests https://github.com/guardian/commercial/pull/810/commits/67e79463385a99d04a48129c9a29498e85014334 (WIP but bringing it over to commercial)
> feat: Migration update

- bundle/package.json
- yarn.lock
Bump @guardian/source-foundations@^9.0.0 to align deps with upcoming bumps in Frontend:
https://github.com/guardian/frontend/pull/25949
> chore: Bump @guardian/source-foundations@^9.0.0

- bundle/src/bootstraps/standalone.commercial.ts
- bundle/src/projects/commercial/modules/dfp/prepare-googletag.ts
- bundle/src/projects/commercial/modules/elementsManager.ts
- bundle/src/projects/commercial/modules/manage-ad-free-cookie-on-consent-change.spec.ts
- bundle/src/projects/commercial/modules/remove-slots.ts
- bundle/src/projects/common/modules/experiments/ab-tests.ts
- bundle/src/projects/common/modules/experiments/tests/elements-manager.ts
- Create an Elements Manager 0% AB test. This is [mirrored in frontend](https://github.com/guardian/frontend/pull/25940).
- When in the test:
- Don't load opt-out or googletag
- Load an example ad in an iframe in the right slot.
To test, note that you will need to run elements manager on port 3002 to see the ad.
This is a step towards using elements manager to place elements on the page.
> feat: Create elements manager ab test. Place test ad in right slot.

- core/src/create-ad-slot.spec.ts
- core/src/event-timer.spec.ts
- core/src/google-analytics.spec.ts
- core/src/targeting/build-page-targeting.spec.ts
- core/src/targeting/build-page-targeting.ts
- core/src/types.ts
The targeting property `dcre` (dcr-eligible) should derive from `config.page.dcrCouldRender` and not `config.isDotcomRendering`
> fix: `dcre` should use `dcrCouldRender`

- bundle/src/bootstraps/standalone.commercial.ts
- bundle/src/types/global.d.ts
We were previously relying on `window.guardian.config.page` providing the `frontendAssetsFullURL` property. However, the actual data model reliably provides that value in `window.guardian.config` - so we'll use that instead.
Where it's populated on DCR:
- [For articles](https://github.com/guardian/dotcom-rendering/blob/5217cb56aa23a896c14840123fd1f5378a8faa30/dotcom-rendering/src/web/server/articleToHtml.tsx#L125).
- [For fronts](https://github.com/guardian/dotcom-rendering/blob/5217cb56aa23a896c14840123fd1f5378a8faa30/dotcom-rendering/src/web/server/frontToHtml.tsx#L76).
Fix an issue with dynamic imports not loading. on new DCR fronts - this is because `window.guardian.config.page.frontendAssetsFullURL` was not defined.
> fix: Update `frontendAssetsFullURL`

- bundle/src/bootstraps/standalone.commercial.ts
- bundle/src/projects/commercial/modules/elements-manager/init.ts
- bundle/src/projects/commercial/modules/elements-manager/targeting.spec.ts
- bundle/src/projects/commercial/modules/elements-manager/targeting.ts
- bundle/src/projects/commercial/modules/elements-manager/types.ts
- bundle/src/projects/commercial/modules/elements-manager/util.ts
This PR lays out the initial functionality for targeting in the GEM client.
We fetch the full set of elements, with their assets and targeting, from the endpoint introduced in [this elements-manager PR](https://github.com/guardian/elements-manager/pull/21). In production we'll retrieve an object of the same shape from the CDN. It is then the responsibility of the client to determine, for each slot, which element would be eligible to fill it.
Imagine an element has the following targeting fetched from the elements-manager UI:
```json
[
{ "key": "slot", "value": "mostpop,comments" },
{ "key": "k", "value": "commentisfree" }
]
```
For a slot to be filled by this element, the combined page and slot targeting for this slot must contain:
- the key `k` with at least one corresponding value that …
> feat: Client-side targeting for elements-manager

- core/src/targeting/content.ts
Following on from [this PR](https://github.com/guardian/commercial-core/pull/782), Tom has now added the new `rc` key to GAM. Include a link in the comment.
Because all the other keys have GAM links.
> docs: Add GAM link in comment

- bundle/src/projects/common/modules/spacefinder-debug-tools.ts
Adds smooth transitions to the spacefinder debugger
Also triggers a release which I forgot to do in this PR: https://github.com/guardian/commercial/pull/835
> feat: Add smooth transitions to the spacefinder debugger

- bundle/.releaserc.json
- core/.releaserc.json
[conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) syntax should allow a `!` postfix to commit types to signal a major release to semantic-release.
At some point the conventionalcommits preset configuration for semantic-release stopped working for `!` with types (`build, chore, ci, docs, style, refactor, perf, test`) and now only work for `fix` or `feat`.
A related discussion around `!` is here:
https://github.com/semantic-release/semantic-release/issues/2339
The current preset configuration looks correct [according to the docs](https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugin-options-configuration) but [this post](https://github.com/semantic-release/semantic-release/issues/2339#issuecomment-1451987883) suggested a change to the way the preset …
> chore!: fix semantic-release conventionalcommits ! syntax

- bundle/src/projects/common/modules/experiments/tests/eager-prebid.ts
It was supposed to be 6%, follow up to #849 
there are 6 variants each needing 1%
> fix: eager-prebid ab test 5 -> 6%

- bundle/src/bootstraps/standalone.commercial.ts
When in the elements-manager variant, don't load the consentless bundle.
Fix so we can properly enter the consentless AB test.
> fix: Skip loading Opt Out if in the elements-manager test

- bundle/README.md
Add some extra documentation for using the commercial development server against Frontend. This change was introduced in [this PR](https://github.com/guardian/frontend/pull/26044).
Clarity on how to use the dev server when using Frontend.
> docs: Add instructions for using the dev server against Frontend

- core/src/create-ad-slot.ts
Allow `exclusion` named slots to be created by the `createAdSlot` function.
An exclusion slot is a special slot that can be used to exclude Opt Out Advertising from an entire page.
We currently server-side render `exclusion` slots, but we could client-side render them once we know we'll be making requests to Opt Out. This PR is the first step to achieve this.
> feat: Permit dynamic `exclusion` slots

- bundle/package.json
- bundle/src/bootstraps/commercial.consentless.ts
- bundle/src/projects/commercial/modules/consentless/dynamic/exclusion-slot.ts
- yarn.lock
This PR completes the work in https://github.com/guardian/dotcom-rendering/pull/7551 and https://github.com/guardian/frontend/pull/26070, where we switch from server side rendering the `exclusion` slot to rendering it client-side.
We add a new module `initExclusionSlot` which simply creates a new `exclusion` ad slot div and defines a corresponding Opt Out slot. This will get picked up when we make the request to the Opt Out server.
From the code:
> This is a special type of ad which, when filled, blocks all other ads on the page. This allows us to run "exclusion campaigns" against certain breaking news pages.
>  
> Exclusion ads are used for consentless advertising only. GAM has a different mechanism to achieve the same thing.
By switching to rendering it client-side, we can avoid having …
> feat: Render the `exclusion` slot from the Opt Out script

- core/src/targeting/build-page-targeting.spec.ts
- core/src/targeting/build-page-targeting.ts
- core/src/targeting/content.spec.ts
- core/src/targeting/content.ts
Add a targeting key `allkw` that is the unique values from both `urlkw` and `k`
Excerpt from the ticket:
> The reason for a new key-value is that there still remains a number of use cases for just using urlkw and just k. However, the new key-value will populate when either are present - which helps resolve issues (e.g. from Google, where they want to block 100s of distinct keywords regardless of it it's in the URL or editorial keywords).
> feat: Add new `allkw` targeting key

- bundle/package.json
- yarn.lock
So that the new targeting key in #858 is available
> feat: Bump commercial-core in commercial-bundle to 6.2.0

- core/src/targeting/youtube-ima.spec.ts
- core/src/targeting/youtube-ima.ts
- core/src/targeting/youtube.spec.ts
- core/src/targeting/youtube.ts
YouTube targeting updates to assist reporting for a YouTube IMA test
When the user is not part of the IMA integration test (i.e. regular YouTube targeting) then we add a `yt_embed_ima=0` to the ad targeting so it is easier for Google to distinguish between the two ad requests.
> feat: YouTube targeting updates

- bundle/src/projects/commercial/modules/dfp/fill-advert-slots.ts
Adds the Outstream ad sizes to server-side inserted inline ads.
So that we can show Outstream ads (Teads) on liveblog pages when the advert slots are inserted server-side.
> fix: Allow Teads on liveblog server-side inserted inline ads

- e2e/package.json
- yarn.lock
Upgrade Percy to latest
Maybe fix some flakiness with Percy runs failing to report in GitHub checks?
> chore: bump @percy/cli to 1.24.0

- .github/workflows/ci-core.yml
- core/README.md
Remove coveralls from ci-core action
Coveralls is not currently bringing us value. The CI check in GitHub often hangs with the message "Expected — Waiting for status to be reported". We have disabled the check on GitHub PRs. This change deletes the action from the CI workflow.
> ci: Remove coveralls from ci-core action

- bundle/package.json
- core/package.json
- yarn.lock
Bumps the version of cmp to remove fb and update ipsos mori vendor id
Version 13.0.2: https://github.com/guardian/consent-management-platform/releases/tag/v13.0.2 
vendor id changes which have a knock on effect.
> chore!: bump cmp in bundle and core

- bundle/package.json
- yarn.lock
Bump version of commercial core in commercial bundle to accommodate update of consent-management-platform.
https://github.com/guardian/consent-management-platform/releases/tag/v13.0.2 
https://github.com/guardian/commercial/releases/tag/%40guardian%2Fcommercial-core-v7.0.0 
To pick up changes of vendor id.
> chore!: bump commercial core in bundle

- bundle/src/projects/commercial/modules/article-body-adverts.ts
This change removes `<ul>` elements from the list of elements that Spacefinder avoids placing ads close to. Spacefinder will now be able to place ads close to a bulleted list.
Some elements in an article are not suitable to place ads next to or close to. For example, an advert too close to a full-width image would not look good when rendered on the page. A bulleted list is regular article content and should not be avoided when trying to place ads. This change will not insert ads immediately above a bulleted list, as adverts are only inserted above paragraph `p` tags.
|-------------|------------|
| ![before][] | ![after][] |
[before]: https://github.com/guardian/commercial/assets/9574885/c90b1752-ab5d-497d-bd15-58f740f2052c
[after]: …
> fix: Add <ul> to spacefinder ignore list

- .github/workflows/beta-release-on-label.yml
- .github/workflows/ci-bundle.yml
- .github/workflows/ci-core.yml
Add `permission: write-all` to each of the Github actions that release NPM packages.
Attempt to fix an issue where we're unable to release packages due to permission issues.
> chore!: Permissions for Github Actions

- bundle/src/bootstraps/standalone.commercial.ts
Authored by @emma-imber
Tweak the Opt Out boot logic so that we only perform `chooseAdvertisingTag()` when Opt Out is switched on.
Avoid a case where we don't perform some commercial modules when Opt Out is switched off.
> feat: Tweak the opt out boot logic

- .github/workflows/beta-release-on-label.yml
- bundle/src/projects/commercial/modules/consentless/render-advert-label.spec.ts
- bundle/src/projects/commercial/modules/consentless/render-advert-label.ts
- Fixes the beta release action by using a slightly older version of node to preform the beta release
- Changes the consentless label rendering logic to add labels to merchandising slots, as these are used to display ads in consentless, instead of in house content
Before:
After:
> fix: Add labels to consentless merchandising slots

- core/src/ad-sizes.ts
- core/src/create-ad-slot.ts
Adds the fronts-banner ad slot type.
So that we can target this new type of slot with banner style ads on fronts pages
> feat: Add new fronts-banner ad slot

- e2e/package.json
- yarn.lock
Bumps Percy from 1.24.0 -> 1.24.2
Partially fixes a [high severity issue](https://github.com/guardian/commercial/security/dependabot/21) identified by Dependabot, introduced through an old version of cosmiconfig, which is used by 1.24.0 of Percy.
> chore: bump percy to v1.24.2

- bundle/package.json
- bundle/src/bootstraps/standalone.commercial.ts
- bundle/src/projects/commercial/modules/dfp/Advert.ts
- bundle/src/projects/commercial/modules/fronts-banner-adverts.ts
- bundle/src/projects/commercial/modules/header-bidding/request-bids.ts
- bundle/src/projects/commercial/modules/header-bidding/slot-config.ts
- bundle/src/projects/commercial/modules/header-bidding/types.d.ts
- yarn.lock
Add fronts-banner ads to Frontend UK Network Front.
Ads will be inserted above the following sections: `opinion`, `sport`, `around-the-world`, `lifestyle`, `in-pictures`.
This functionality is behind an [AB test](https://github.com/guardian/frontend/pull/26117) which looks to test a new ad strategy on Fronts pages. For this test, the new adverts will only be inserted in the following conditions:
- The page is the UK Network Front, i.e. https://www.theguardian.com/uk
- The page is not rendered by DCR
- The viewport size is above the desktop (980px) breakpoint.
So that we can gather results for an [AB test](https://github.com/guardian/frontend/pull/26117) regarding the commercial impact of a new ad strategy.
> feat: Add fronts-banner ads to Frontend UK Network Front

- bundle/src/projects/commercial/modules/dfp/Advert.ts
- bundle/src/projects/commercial/modules/dfp/add-slot.ts
- bundle/src/projects/commercial/modules/dfp/create-advert.ts
- bundle/src/projects/commercial/modules/dfp/define-slot.ts
- bundle/src/projects/commercial/modules/fronts-banner-adverts.ts
Add section slot targeting to fronts banner slots
Following on from #877, this adds a targeting key-value to the slot for the section it is adjacent to, to enable contextual targeting for these slots.
> feat: Add section slot targeting to fronts banner slots

- package.json
make `yarn build` build both the dev and prod bundles
Frontend when running locally is requesting the bundle without a hash, simply copying the file without the hash doesn't work as the separated chunks will still be requested with the hash in the URL (prebid.js and consentless), probably because webpack works out the paths at compile time?
A quick solution is to build both dev and prod so that they both will end up in the npm package and either can be used.
> fix: build dev & prod by default

- .github/workflows/beta-release-on-label.yml
Amends the grep command in the beta release script to return the latest release version tags.
The beta release versioning was using out of date versions because it was searching the git tag entries to find the latest versions. Now that bundle and core are merged, the release version tags are no longer prefixed with commerical-bundle or commercial-core in the tags, and are now just **v8.0.0**, for example. By removing the **@guardian/commercial** prefix from the grep command, we will find the latest tag version and assign the correct version number to the beta release.
Basically, tags used to look like this:
And they now look like this:
So we need to update the grep code accordingly.
> chore: Fix beta release versioning

- .vscode/settings.json
Do not specify a default formatter in `.vscode/settings.json`.
To avoid issues where the installed formatter does not match the default one specified in the file.
> chore: Do not specify default formatter

- src/projects/common/modules/experiments/tests/limit-inline-merch.ts
Increase the audience participation of the Inline Merch AB test to 10%.
Additionally, set its offset to 40%, so that it doesn't overlap with any other test groups.
See the corresponding DCR PR: https://github.com/guardian/dotcom-rendering/pull/7864.
The original test setup: https://github.com/guardian/dotcom-rendering/pull/7780
The sample sizes have been calculated and we're ready to launch the test.
> feat: Increase Inline Merch test participation to `10%`

- package.json
- yarn.lock
Bumps the @guardian/consent-management-platform to version 13.2.0 which includes a deny list and associated code to remove any outstanding non-essential 1st party cookies and local storage when a reader changes their consent towards reject-all from a different consent.
Release notes: https://github.com/guardian/consent-management-platform/releases/tag/v13.2.0 
This is the first step of the cookie remediation project to improve our processes.
> chore!: bump consent-management-platform

- package.json
Reverts guardian/commercial#886 remove the dev build from the package for now, causing issues with the URL hash on frontend
> fix: Revert "fix: build dev & prod by default"

- src/projects/commercial/modules/fronts-banner-adverts.ts
Add data attribute to opinion banner ad container
So we can get results from the AB test: https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/01-ab-testing.md#getting-the-results
> feat: Add data attribute to opinion banner ad container

- .changeset/tidy-eyes-grab.md
- src/projects/commercial/modules/header-bidding/prebid-types.ts
- src/projects/commercial/modules/header-bidding/prebid/appnexus.ts
- src/projects/commercial/modules/header-bidding/prebid/bid-config.spec.ts
- src/projects/commercial/modules/header-bidding/prebid/bid-config.ts
- src/projects/commercial/modules/header-bidding/prebid/improve-digital.ts
- src/projects/commercial/modules/header-bidding/slot-config.ts
- src/projects/commercial/modules/header-bidding/utils.ts
- Fixes a bug that enables prebid to be run on fronts banner ads.
- Configures the following vendors to be able to identify and bid on fronts-banner-ads: Improve; Pubmatic; Appnexus; Index; Smart; Criteo.
So that we can run header-bidding on the fronts banner ads
> Configure Prebid on fronts banner ads

- .changeset/empty-squids-guess.md
- src/projects/common/modules/experiments/tests/limit-inline-merch.ts
Increase the audience size for the inline merch AB test to 20% (that's 10% in the variant and 10% in the control).
We've seen lower traffic than expected in this test, most likely due to how current marketing campaigns are setup (the number of eligible pages is dependent on the campaigns running, so if we don't have many campaigns, or don't target popular keywords, then we'll get less traffic). To reach significance sooner, we'll increase the audience size.
> Increase inline merch test participation to 20%

- .changeset/witty-pianos-give.md
- package.json
- webpack.config.dev.js
- webpack.config.prod.js
Move built bundle files to `prod` and `dev` subdirectories in the dist/bundle folder and have both in npm, so they can both be used, this is a breaking change as the path to the files/entrypoints will change.
frontend when running locally wants the unhashed files to be available, webpack bakes in the hashes for chunks like prebid and consentless so we need to provide a build without them.
> build both dev and prod to subdirectories in the dist folder

- src/bootstraps/standalone.commercial.ts
- src/projects/commercial/am-i-used.spec.ts
- src/projects/commercial/am-i-used.ts
- Set default sendBeacon test sampling rate to zero, and update the function test file to reflect that
- Call amiused in the bootCommercial function for 0.01% of cases, to test the reliability of sendBeacon vs fetch
- Send the UserAgent details in the amiused testing logs
We will no longer use the actual amiused call (in spacefinder.ts) to test the reliability of sendBeacon vs fetch. This is because we don't know if there might be bias in the situations in which this function is called, perhaps in the browsers or different user setups, and this could lead to bias in our results. Instead, we will call amiused 0.01% of the times that the bootCommercial function in the standalone file runs. We know this script should run for all users who see google ads, and this should give us a more …
> Enhance sendBeacon testing

- .changeset/kind-tables-build.md
- .github/workflows/beta-release-on-label.yml
Updates the reference to the Github API in the beta release workflow.
This is so that the beta release flow can comment the version on pull requests. The previous way was deprecated and was causing errors when creating beta releases.
> Try updating reference to Github API to fix beta release version comments

- .changeset/hot-lemons-hug.md
- package.json
- yarn.lock
We are seeing the prebid.js entry in yarn lockfiles intermittently switch to a format that causes issues for snyk in DCR and Frontend e.g.:
https://github.com/guardian/dotcom-rendering/pull/8049
https://github.com/guardian/frontend/pull/25995
https://github.com/guardian/frontend/pull/25947
Good: `"prebid.js@github:guardian/prebid.js#2e3b96d":`
Bad: `prebid.js@guardian/prebid.js#2e3b96d:`
Instead of referencing a commit we can just use head of [guardian/prebid.js](https://github.com/guardian/prebid.js) which _might_ mean a consistent lockfile format and snyk is happier with.
ps. I am sure there were 'reasons' to use commit hashes as part of the dependency that I struggle to recall now. But I think using head should be okay as long as we know that merges into the fork main will immediately …
> Use head of guardian/prebid.js fork

- .changeset/stale-pets-remember.md
- src/standalone.commercial.ts
- webpack.config.prod.js
This PR bakes the commit SHA into the bundle and logs it to the browser console.
This should make it easier to tell which version of the Commercial bundle is running on CODE/Production.
> feat: Bake commit hash into bundle

- .github/workflows/e2e-cypress.yml
This PR switches our Cypress tests to using DCR as a Github Actions _service_, pulling down and starting a [prebuilt container](https://github.com/guardian/dotcom-rendering/blob/6a6df272/.github/workflows/container.yml).
Using a prebuilt container allows us to avoid having to download, install dependencies and build DCR in each concurrency group. This should make our E2E test actions appreciably faster.
The time it takes to prepare DCR for requests before using containers:
The time it takes to prepare the DCR service for accepting requests:
Before:
After:
> Cypress tests use containerised DCR

- .changeset/twenty-numbers-dress.md
- src/lib/header-bidding/slot-config.spec.ts
- src/lib/header-bidding/slot-config.ts
- src/lib/header-bidding/utils.spec.ts
- src/lib/header-bidding/utils.ts
Remove usage of mobileStickyLeaderboard and mobileStickyPrebid switches, mobile sticky (floating ad at the bottom in aus/nz/usa/canada) will now be permanently enabled and require a PR to disable.
These have been enabled since their inception and it's been determined the switches are no longer required
> Remove usage of mobileStickyLeaderboard and mobileStickyPrebid switches

- .github/workflows/e2e-cypress.yml
Run our E2E tests on pushes to the `main` branch.
To verify that the main branch is healthy when we merge our pull requests.
> Run E2E tests on push to `main`

- .github/workflows/e2e-visual.yml
This PR changes the Percy visual testing Github Action to only be triggered manually from the Github UI.
This action is not currently required for a build to pass, and often errors. This prevents the workflow from running when its not required.
> Visual tests should only be manually triggered

- .changeset/tough-flowers-listen.md
- src/lib/dfp/dfp-env.ts
- src/lib/dfp/prepare-a9.spec.ts
- src/lib/dfp/prepare-a9.ts
- src/lib/dfp/prepare-googletag.spec.ts
- src/lib/dfp/prepare-prebid.spec.ts
- src/lib/dfp/prepare-prebid.ts
- src/lib/header-bidding/a9/a9.ts
- src/lib/header-bidding/prebid/prebid.ts
- src/types/global.ts
This PR removes the `hbImpl` object, and replaces its use with the value of the underlying switches.
Remove an unecesary indirection, where it'd be simpler to just use the switch values directly.
> Remove `hbImpl`

- .changeset/clever-worms-divide.md
- src/lib/dfp/dfp-env.ts
In dfp-env `shouldLazyLoad` should always returns true if on mobile/tablet breakpoints
Currently it only checks for `hasPageSkin: false` but this causes issues on mobile/tablet where the pageskin doesn't actually run but `hasPageSkin` is still true
this is causing problems with viewability on mobile/tablet breakpoints.
> shouldLazyLoad should always return true if on mobile/tablet breakpoints

- .changeset/cold-plants-pay.md
- src/lib/dfp/render-advert-label.ts
The close button was being pushed off to the side of the mobile sticky ad, meaning that it was very difficult to see. The styles have been updated so that the button is now back where it should be.
Also renames the button element variable in the code that creates the close button, to be clearer about the type of element it creates.
Before:
After:
> Fix mobile sticky close button

- .changeset/wicked-plums-matter.md
- src/core/create-ad-slot.ts
- src/lib/high-merch.ts
Remove unused slots from ad slot config object:
- `high-merch-lucky`: There are no places where `createAdSlot` is called with this slot name.
- `high-merch-paid`: This is the exact same object as `high-merch`, so we can just use this definition.
- `epic`: There are no places where `createAdSlot` is called with this slot name.
- `mostpop`: These slots are currently not created dynamically.
`createAdSlot` is used to create an ad slot div for dynamically inserted ads (e.g. by Spacefinder). This function relies on some configuration, which I've cleaned up above to remove definitions we no longer use.
> Remove unused `createAdSlot` config

- src/lib/utils/am-i-used.ts
- src/standalone.commercial.ts
No longer call amiused from standalone, and remove the sendBeacon sampling option from amiused.
We now have 4 weeks worth of data comparing the performance of sendBeacon and fetch, which will be enough for analysis.
> Remove the testing of sendBeacon from amiused

- .changeset/slimy-plums-taste.md
- src/lib/dfp/fill-advert-slots.ts
- src/lib/spacefinder/liveblog-right-adverts.ts
- src/lib/spacefinder/liveblog-right-column-adverts.ts
- src/standalone.commercial.ts
- This fixes a bug in the liveblog right column adverts AB test. The liveblog-right ads were being created by `fill-advert-slots.ts`. However, we cannot be certain that all the `liveblog-right` ad slots will be on the page when this code is run. Therefore there's an extra call to `fillAdvertSlots()` before the eventListener is registered, in case the slots are already on the page.
- Moved the logic to restrict the height of the `right` ad slot from the DCR to Commercial repo.
- We want the `liveblog-right` adverts to be created when we know the slots are ready.
- So that we can update the styles, since the `right` ad slot is rendered on the server
> Ensure liveblog-right ads are inserted via custom event

- .changeset/chilled-bobcats-sit.md
- README.md
- src/lib/experiments/tests/liveblog-right-column-ads.ts
Sets the audience to 15% for the liveblog right column ads AB test
- This will start the AB test and allow us to create metrics.
- Setting the audience to 15% so that the participation group of each control and variant (of which there are two) will be 5%.
> Start liveblog right column ads test

- .changeset/wet-cougars-yell.md
- src/core/ad-sizes.ts
- src/lib/dfp/Advert.ts
- src/lib/dfp/fill-external-slots.ts
- src/lib/remove-slots.ts
- src/standalone.commercial.ts
Enable ads to be placed on the page via an external route e.g. thrashers
I'm not completely convinced about the naming but going with 'external' for now
Mostly a generic implementation of #947, specifically [liveblog-right-adverts.ts](https://github.com/guardian/commercial/blob/53e203c77b8a7c9f36300a4dfba81c5b404baa43/src/lib/spacefinder/liveblog-right-adverts.ts) - thanks @domlander !
The extra logic in addition to dynamic slots covers when:
- the commercial runtime loads after the slot so we query any external slots and fill them
- the commercial runtime loads before the slot so we listen for custom events and fill them e.g.
```js
document.dispatchEvent(
new CustomEvent('gu.commercial.slot.fill', {
detail: { slotId: 'dfp-ad--external1' },
}),
);
```
> External ads

- .changeset/cool-baboons-hope.md
- src/lib/dfp/on-slot-viewable.ts
Don't apply min height with label height when `data-label=false`
h/t to @domlander and @emma-imber for their help on this.
This causes ads to shift when we add min-height even though `data-label=false`
Before:
https://github.com/guardian/commercial/assets/7014230/5f00eafe-954b-4252-9daf-481033d15f23
After:
https://github.com/guardian/commercial/assets/7014230/933b2023-54b5-46e3-a912-19b2cfac3392
> Don't apply label height to min-height when there is no label

- .changeset/weak-poems-own.md
- src/lib/dfp/on-slot-viewable.ts
Remove redundant check for setting min-height when there is an ad label - addresses this [comment](https://github.com/guardian/commercial/pull/987#discussion_r1284460661).
> Remove redundant check for setting min-height when there is an ad label

- .changeset/twelve-years-exercise.md
- package.json
- src/core/event-timer.ts
- src/core/send-commercial-metrics.ts
- yarn.lock
Start recording DCR performance measures.
So we can see what is fast and what is slow for our users.
> Record DCR performance measures

- cypress/e2e/parallel-4/pageskin.cy.ts
- cypress/fixtures/pages/articles.ts
- cypress/fixtures/pages/fronts.ts
- cypress/fixtures/pages/index.ts
- cypress/fixtures/pages/liveblogs.ts
- cypress/lib/util.ts
Add a test for pageskins, testing if the pageskin image is applied on desktop and that Single Request Mode is used, also check the opposite on tablet/mobile.
Refactored `getTestUrl` slightly, to remove DCR option, we're always on DCR now and in the future.
We wan't to be confident that the logic is working correctly, especially single request mode, it's not easy to notice if it's not behaving as we'd like.
Bonus: [Puppies Test Pageskin](https://www.theguardian.com/uk?adtest=puppies-pageskin)
> Add cypress test for pageskins

- .changeset/funny-dragons-deliver.md
- cypress/e2e/parallel-2/article-inline-slots.cy.ts
- cypress/e2e/parallel-3/liveblog-inline-slots.cy.ts
- cypress/e2e/parallel-3/liveblog-live-update.cy.ts
- cypress/fixtures/pages/Page.ts
- cypress/fixtures/pages/articles.ts
- cypress/fixtures/pages/liveblogs.ts
- Fixes a failing cypress test. 
- Replaces the liveblog test page with another that contains a more typical number of embeds. The previous Liveblog test page had a lot more Twitter embeds than usual.
- Split expected slot tests into mobile and desktop.
- The reduction in line height for text content on liveblog meant that the page became shorter and commercial have less space to insert ads. On the test liveblog page, we were now only inserting 3 ads instead of 4 at some breakpoints.
- There is no need for our test liveblog page to have so many twitter embeds. It was a red herring when investigating the cause of this Cypress test failure.
- Desktop and mobile screen sizes typically render a different number of ad slots
> Update cypress tests following reduction of text line height

- .changeset/healthy-dolphins-grin.md
- src/lib/experiments/tests/liveblog-right-column-ads.ts
Turns off the liveblog-right-column-ads AB test.
We have reached the required number of impressions to obtain a result for the test.
> Switch off liveblog right column ads AB test

- .changeset/red-cooks-heal.md
- package.json
- yarn.lock
Bump @guardian/libs and bump this package…
The latest version of `getMeasures` actually works – this package is not a peer dependency
See https://github.com/guardian/dotcom-rendering/pull/8571
> chore(deps): bump @guardian/libs

- .changeset/eighty-lizards-refuse.md
- src/core/targeting/youtube.ts
YouTube targeting uses `Consentstate.canTarget`
Since [this PR](https://github.com/guardian/consent-management-platform/pull/597) we now determine `canTarget` as part of the CMP process [here](https://github.com/guardian/consent-management-platform/blob/e768b95da95ded9c6320247cf5ddebb9beeb19a4/src/onConsentChange.ts#L50).
> YouTube targeting uses `Consentstate.canTarget`

- .changeset/grumpy-needles-study.md
- package.json
- src/lib/dfp/on-slot-render.ts
- src/lib/dfp/prepare-googletag.spec.ts
- src/lib/dfp/prepare-googletag.ts
- src/lib/dfp/prepare-permutive.ts
- yarn.lock
Update @types/googletag v3.0.3
Some of the types have been updated, and `googletag.setNonPersonalizedAds` was deprecated, requiring some code change, so giving this dependency update it's own PR
The deprecation is in the types PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61241, but missing from the release notes https://developers.google.com/publisher-tag/release-notes which was a little confusing.
> Update @types/googletag to v3.0.3

- .changeset/young-houses-eat.md
- package.json
- src/lib/experiments/ab-tests.ts
- src/lib/experiments/tests/prebid-kargo.ts
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/prebid/prebid.ts
- src/lib/header-bidding/utils.ts
- yarn.lock
Adds `kargo` as a bidder in the USA, 
Frontend PR where switch and test was added: https://github.com/guardian/frontend/pull/26475
Enabling kargo bid adapter in our prebid.js fork https://github.com/guardian/Prebid.js/pull/134
which has been updated in this PR
The relevant line-items have been generated in this PR https://github.com/guardian/commercial-tools/pull/165 where you can see the price bucketing and line items priority (same as prebid main)
The placement IDs are as follows:
Platform | Type | Sizes | Placement ID
-- | -- | -- | --
Mobile | Middle In-Article | 300x250 | _y9LINEsbfh
Mobile | Adhesion | 320x50 | _odszPLn2hK
Desktop | Middle In-Article | 300x250 | _qDBbBXYtzA
Desktop | Right Rail | 300x250, 300x600, 160x600 | _zOpeEAyfiz
Desktop | Above The Fold | 728x90 | _y6zKwuoPpX …
> Add kargo as a prebid bidder in the US if in 0% AB test

- .vscode/settings.json
- Sets the title bar colour of VS Code
- Remove `eslint.packageManager`
- DX. Distinguish between code editors
- Package manager is detected automatically now
Green?
https://github.com/guardian/commercial/assets/9574885/8895e018-8221-410f-aa52-64ca312927a1
or red?
https://github.com/guardian/commercial/assets/9574885/8141f95c-72f2-4943-a20e-40823e236801
> VS Code title bar colour

- .gitignore
- .vscode/settings.json.recommended
- .vscode/settings.json.required
- Removes `.vscode/settings.json` from the repo
- Adds `.vscode/settings.json.required` and `.vscode/settings.json.recommended`
In the spirit of [the recommendation](https://github.com/guardian/recommendations/blob/main/VSCode.md#vscodesettingsjson). We can then keep these files up to date and individual devs can pick and choose their preferred settings.
> Remove `.vscode/settings.json` from git

- .changeset/heavy-berries-sit.md
- package.json
- yarn.lock
Move all `@guardian` dependencies to peer dependencies so that clients of commercial (primarily DCR) with strict checks on peer dependency alignment do not have to raise versions in lockstep.
Yarn and npm < v7 do not install peer dependencies so we have to add them to dev dependencies for local development and bundling.
The commercial repo publishes two things:
1) the commercial bundle which requires deps at bundle time
2) utility functions for consumption by consuming applications
aiui release bundling still works with @guardian deps as peers deps because we install all dependencies (i.e. not using install --production) and then this get cached and restored by all the workflow jobs.
> Make `@guardian` dependencies peer dependencies

- .changeset/dirty-dancers-repeat.md
- babel.config.js
- package.json
- src/lib/detect/detect-breakpoint.ts
- yarn.lock
Uses the "@guardian/browserslist-config" package so that we build the bundle to be compatible with the browsers defined here: https://github.com/guardian/csnx/tree/main/libs/%40guardian/browserslist-config#included-browsers
I've also added the deprecated addListener function as a fallback for addEventListener in detect-breakpoint. In versions of Safari before 14, the MediaQueryList does not inherit the addEventListener function, and this was preventing ads from loading as the function could not be found.
This means Safari versions 11, 12, and 13 are now supported and will show ads.
Using a standardised list is more robust than just building for the last x versions of a browser, and makes sure that we build our bundle to be compatible with the browsers that we know our readers use. This …
> Use Guardian browserslist to govern browser support

- .changeset/flat-beers-learn.md
- package.json
- src/lib/header-bidding/prebid/prebid.spec.ts
- yarn.lock
Upgrade Prebid.js to v7.54.4 as per https://github.com/guardian/Prebid.js/pull/132
Note:
The prebid config object has changed to not include any private fields (`_*`) when calling:
`window.pbjs.getConfig()`
I think this is okay as all the fields have public equivalents and it does not seem to affect the functioning of prebid.
Have tested on CODE
> Upgrade Prebid.js to v7.54.4

- .changeset/stale-rings-attend.md
- src/lib/commercial-features.ts
We're removing this switch as part of our switch audit, so we don't need to check it any more.
> Remove switch check for carrot ad

- .changeset/large-mayflies-judge.md
- src/lib/experiments/tests/public-good.ts
Set public good test to 10%
To test the UX impact of adding public good at the end of articles in the USA
> Public good test to 10%

- .changeset/hip-wasps-sniff.md
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/utils.ts
Currently `tripleLift` is targeted specifically to USA or Canada IP's to return appropriate ID's.
Depending on the ad types detected, the function returns an appropriate inventory code.
Generating the correct inventory code that TripleLift needs to identify the specific ad placement and size during the bidding process. 
The inventory code is used to target the right ad inventory and ensure that the correct creative is shown if the bid wins the auction
An Array of `bids` is created in order to be sent to `prebid`, we need to ensure that `tripleLift` is included only in US or Canada and Australia or NZ.
However within that logic we also need to ensure the appropriate inventory code is provided for each region (`_AU` for Australia)
in order to test this I am looking at the logger for the …
> add new id's to tripleLift prebid for AUS

- .changeset/short-scissors-fix.md
- src/core/ad-sizes.test.ts
- src/core/ad-sizes.ts
- src/core/create-ad-slot.ts
- src/core/lib/breakpoint.ts
- src/core/types.ts
- Fixes a bug where additional sizes could be added to a breakpoint which has no existing size definition. When adding additional sizes, instead of appending the additional sizes to the existing ad sizes from the next smallest breakpoint with ad sizes, it would overwrite these sizes.
- Inline slots on liveblog pages at phablet & tablet viewport sizes were only using the additional sizes and not the sizes defined for mobile viewport with the additional sizes.
| Before | After |
| - | - |
| ![Before] | ![After] |
[Before]: https://github.com/guardian/commercial/assets/9574885/283a6bdb-bcd4-43a1-9cb1-45304743a8f5
[After]: https://github.com/guardian/commercial/assets/9574885/ca2bfb84-0f80-442e-8bee-55fec6c1818c
> Fix bug when adding additional sizes to empty size mapping.

- .changeset/gentle-suns-battle.md
- src/core/ad-sizes.ts
- Adds the merch-high ad size (88x87) to fronts-banner ad slots
- So we can display adverts targeting the 88x87 size in these slots
> Add merch-high ad size to fronts-banner ads

- .github/workflows/e2e-cypress.yml
- cypress.config.js
- Record Cypress videos when running in CI, detected via the [`CI`](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) environment variable.
- Only upload the captured videos as artifacts when the E2E test suite fails.
This should make it slightly easier to debug any issues with failing tests running in CI.
I've opted to switch to only upload artifacts on failure to minimise the amount of videos stored that we'll likely never watch.
> Record Cypress videos in CI

- .changeset/hot-weeks-sell.md
- src/lib/raven.ts
Stop bypassing the Sentry sampling rate for Okta test participants.
When we migrated to Okta we wanted to see all Sentry errors from Okta test participants to keep an eye out for any new errors. Now that the test is going to 10%, we want to reintroduce sampling so that we don't flood Sentry with error messages.
> Sentry sampling for Okta test participants

- src/core/ad-sizes.ts
Removes the leaderboard size for mostpop ads on tablets.
The div that the mostpop fits in on tablet view is never big enough to contain a leaderboard size. On articles on tablets, the div is usually 698px, whereas the leaderboard ad is 728px wide.
At the moment, the mostpop ad slot remains 300px wide even when a leaderboard is served into the slot which means the ad is skewed to the side:
However, even when we change this to allow the slot to expand to accommodate the leaderboard, the ad will still overflow the div, because the ad is too big:
It makes sense to remove this ad size for this slot, as it will never fit.
> Remove leaderboard ad size for mostpop

- .github/workflows/e2e-cypress.yml
- cypress/e2e/parallel-2/googletag-switch.cy.ts
- cypress/lib/util.ts
- scripts/fixtures/fixtures-server.js
- scripts/fixtures/fixtures.js
- webpack.config.dev.js
It'd be useful to be able to run end-to-end / integration tests where we fix the data model we send to DCR.
1. When the `shouldLoadGoogletag` switch is switched on, ads load on the page.
2. When the `shouldLoadGoogletag` switch is switched off, ads do not load on the page.
Therefore, we want to ignore the production value for the `shouldLoadGoogletag` switch and override it with a value we have fixed for the test.
The test that implements that as part of this PR is located in [googletag-switch.ts](https://github.com/guardian/commercial/blob/39fd2ab93ff3feae54ee2e4c1db745c38f9e33d3/cypress/e2e/parallel-2/googletag-switch.cy.ts) as part of this PR.
In order to achieve the above, this PR adds a _fixtures server_ to our existing webpack dev server setup. This has an endpoint that accepts GET …
> Allow overriding the data model in E2E tests

- .changeset/calm-windows-refuse.md
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/bid-config.ts
Add the publisher ID to the improveDigitalBidder. I've kept it as an optional parameter for now as we don't need to send it for the improve pageskin bidder.
To address an incoming request from Improve Digital
> Add publisher ID for improve digital

- .changeset/forty-rice-attend.md
- src/core/ad-sizes.ts
- src/lib/dfp/define-slot.spec.ts
- src/lib/header-bidding/slot-config.ts
Use the new TypeScript [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator) operator when defining ad sizes and size mappings. I've combined this with `as const` in order to infer the narrowest possible types, allowing things like in Intellisense:
Doing this required size mappings use readonly arrays of ad-sizes (and some fixing up in a place or two to satisfy this). I think this is probably a good thing!
This allows us to infer a narrower type in each case, whilst still asserting that ad sizes and size mappings have a certain shape:
- In the case of ad sizes, this doesn't have a material effect, since the type inferred is the same as the one that is satisfied.
- In the case of size mappings, it means we can now access …
> Use `satisfies` when defining ad sizes and size mappings

- src/lib/consentless/render-advert-label.spec.ts
- src/lib/dfp/render-advert-label.spec.ts
- src/lib/dfp/render-advert.ts
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/slot-config.spec.ts
Fixes a few of the more simple errors that result from switching on the noUncheckedIndexedAccess rule for the bundle code.
Reduces the number of errors left to tackle:
Before:
After:
> Fix some noUncheckedIndexedAccess rule errors

- .changeset/fuzzy-fireants-behave.md
- src/lib/header-bidding/prebid/prebid.spec.ts
- src/lib/header-bidding/prebid/prebid.ts
Adds 'ix', the bidder name for indexSSP, to acBidders in the realTimeData config.
This will allow them to access our Permutive audience segments so that they have audience data for targeting deals.
**Before:**
**After:**
> Add ix to acBidders in realTimeData

- .changeset/thirty-ravens-give.md
- package.json
- yarn.lock
Upgrade Prebid to 7.54.5, to use the version from this PR: https://github.com/guardian/Prebid.js/pull/135
> Update Prebid.js to 7.54.5

- .changeset/violet-cycles-doubt.md
- src/lib/spacefinder/sticky-inlines.ts
Sets `top: 61px` for inline2+ sticky ads on Paid Content article pages
On Paid Content pages, there is a banner at the top of the page. The right ad slot has `top: 61px`, but inline2+ ads further down the page have `top: 0`, which meant they are partially covered by the banner. Setting the top value to the height of the banner plus a bit of padding ensures no overlap.
| ![before][] | ![after][] |
[before]: https://github.com/guardian/commercial/assets/9574885/97795c1f-f470-413b-b61b-80e7f9ebe7db
[after]: https://github.com/guardian/commercial/assets/9574885/3541ad0a-e453-49c9-81e9-6838fb3ffcd8
> Prevent overlap of labs banner and inline2+ ads

- cypress/fixtures/pages/articles.ts
Removes a reference to the simpleReach switch.
We're deleting the simpleReach switch as it's no longer used, so we need to delete any references to it in the code.
> Remove reference to simpleReach

- .changeset/bright-panthers-sip.md
- src/lib/spacefinder/spacefinder.ts
Fix errors related to [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) in the `spacefinder.ts` file.
Much better type safety when access collections by their index.
| ![before][] | ![after][] |
[before]: https://github.com/guardian/commercial/assets/8000415/713a4824-582e-45d5-99bc-d76a68843861
[after]: https://github.com/guardian/commercial/assets/8000415/58867bcd-62fb-4a4a-8b41-842f5b7cada7
> Fix unchecked indexed access errors in `spacefinder.ts`

- .changeset/rude-lemons-eat.md
- cypress/fixtures/pages/articles.ts
- src/lib/manage-ad-free-cookie.ts
- src/lib/user-features.spec.ts
- src/lib/user-features.ts
This PR removes any related logic to the `AdFreeStrictExpiryEnforcement` switch.
This was also removed from the related PR in `frontend` [here](https://github.com/guardian/frontend/pull/26587)
Currently we have a switch `AdFreeStrictExpiryEnforcement` 
When this switch is ON and the website loads, it checks to see if the user's ad-free cookie has expired. If so, it will refetch data to update this cookie. This switch has been OFF for a long time and is no longer needed.
We are not concerned with how old the cookie is so therefore we are removing any logic which checks for date or expiry for that cookie.
so the `ad-free-strict-expiry-enforcement` the logic related to this along with the tests have been removed.
> remove logic related to expiry-ad-free-cookie and its switch

- .github/workflows/e2e-cypress.yml
- cypress.config.js
Reverts guardian/commercial#1035.
I've found I get lots of errors when compressing the video artefacts in CI. Since we're moving away from Cypress, I figure we may as well revert this.
> Stop recording Cypress videos in CI

- .changeset/dirty-scissors-scream.md
- .eslintrc.js
- src/lib/consentless/dynamic/liveblog-inline.ts
- src/lib/dfp/init-slot-ias.spec.ts
- src/lib/dfp/prepare-permutive.spec.ts
- src/lib/spacefinder/article-aside-adverts.ts
- src/lib/spacefinder/liveblog-adverts.ts
- src/lib/third-party-tags.ts
- src/lib/utils/geolocation.ts
Fixe instances of no unchecked indexed access errors in:
- src/lib/consentless/dynamic/liveblog-inline.ts
- src/lib/dfp/init-slot-ias.spec.ts
- src/lib/dfp/prepare-permutive.spec.ts
- src/lib/spacefinder/article-aside-adverts.ts
- src/lib/spacefinder/liveblog-adverts.ts
- src/lib/third-party-tags.ts
- src/lib/utils/geolocation.ts
I've also switched the `no-unnecessary-condition` rule to `warn` whilst we squash these errors. We can re-enable it once this work is complete.
Better type safety once the rule is enabled.
> Various `noUncheckedIndexedAccess` fixes

- src/lib/dfp/display-ads.ts
- src/lib/dfp/get-advert-by-id.ts
- src/lib/dfp/on-slot-render.ts
Fixes instances of no unchecked indexed access errors in following Dir:
- src/lib/dfp/display-ads.ts:24
- src/lib/dfp/get-advert-by-id.ts:5
- src/lib/dfp/on-slot-render.ts:40
Better type safety once the rule is enabled.
> fix `noUncheckedIndexedAccess` from dfp directory

- src/lib/spacefinder/article-body-adverts.ts
- src/lib/third-party-tags/imr-worldwide.ts
Fixes the final 3 errors we get when we enable the noUncheckedIndexedAccess rule.
Gets us to 0 errors 📉
> Fix remaining noUncheckedIndexedAccess errors

- .changeset/giant-ducks-exist.md
- src/lib/identity/api.ts
- src/lib/identity/okta.ts
I think uncaught exceptions from the Identity Auth library might be contributing to the spike in dropped errors in Sentry.
In DCR, we catch errors and print them to console. I think it is sensible to do the same here.
https://github.com/guardian/dotcom-rendering/blob/7fe3c9adf5cddc28830d433421a69085a2415fb2/dotcom-rendering/src/lib/useAuthStatus.ts#L88-L102
Part of https://github.com/guardian/dotcom-rendering/issues/8820
See [this chat thread](https://chat.google.com/room/AAAAG9rU0m0/jgCCywOVkm8) for more info.
> Catch errors from Okta

- .changeset/empty-bananas-work.md
- src/lib/messenger/background.ts
Adds the functionality to messenger to create a video inside the interscroller ad if a video source has been specified.
This allows us to support a video interscroller. The template will also be updated to add the videoSource parameter. This is an optional parameter that we check for, and if it's been added we create a video html element inside the interscroller ad.
This has been tested on CODE, demo of the video interscroller is below (video is supposed to be cropped, it's just a cropped version of another video):
https://github.com/guardian/commercial/assets/108270776/98a6a905-8e49-47ba-8fba-716a20196332
> Add video option to interscroller

- .changeset/three-dolls-accept.md
- package.json
- yarn.lock
Updating the version of @guardian/consent-management-platform to the latest version.
> Updated @guardian/consent-management-platform to 13.7.0

- .vscode/settings.json.recommended
- package.json
- playwright/fixtures/pages/articles.ts
- playwright/lib/util.ts
- playwright/tests/parallel-1/consent.spec.ts
- playwright/tests/parallel-2/article-inline-slots.spec.ts
- playwright/tests/parallel-3/liveblog-ad-limit.spec.ts
- playwright/tests/parallel-3/liveblog-live-update.spec.ts
- yarn.lock
- Adds a couple of script which should make it easier for new users to be able to run Playwright
- Added basic "Accept cookies -> ad slots fulfilled test"
- Reordered tests
- Removed skipped "cookie expiry" tests. Commercial only check the existence of cookies (ad free and digital subscriber) when checking consent, so these tests were attempting to test implementation details outside of our domain. Therefore they are not needed.
- We were doing a count() to get the expected number of ad slots which resolve immediately. This was waiting for the first inline slot to appear before running. However, Spacefinder runs through it's logic twice when inserting inline ad slots on article pages. This change ensures we wait until Spacefinder has completely finished inserting inline ad slots before we …
> Playwright fixes: consent and article inline tests

- .changeset/spicy-dogs-cry.md
- package.json
- yarn.lock
- bumps ophan-tracker-js to 2.0.1
- Playwright is removed from yarn.lock (this is fine, playwright-core is what we need)
> bump ophan-tracker-js

- .changeset/fresh-buttons-brush.md
- src/lib/build-page-targeting.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/utils.spec.ts
- src/lib/header-bidding/utils.ts
- Adds a testgroup parameter to Ozone targeting which is a random integer between 0 and 99.
- Renames Falsey to the more usual Falsy: https://developer.mozilla.org/en-US/docs/Glossary/Falsy
- Requested by Ozone so they can AB test.
> Add testgroup to Ozone targeting

- .changeset/lazy-sheep-laugh.md
- src/lib/experiments/tests/eager-prebid.ts
Sets the eager prebid test to 0%
Depending on the outcome of the test, we may want to test again with different numbers or keep the logic in the code, so it makes sense to preserve it behind a 0% test instead of deleting it while we wait for the test results.
> Make eager prebid a zero percent test

- playwright/tests/parallel-3/liveblog-ad-limit.spec.ts
- playwright/tests/parallel-3/liveblog-live-update.spec.ts
- Makes the liveblog-live-update tests run in order instead of concurrently, as this resolves the flakiness
- Adds an extra console log line to the liveblog-live-update test for easier local testing and debugging
- Forces the code to wait until newly inserted blocks are visible before counting them in the liveblog-ad-limit test
- Separates out the liveblog-ad-limit tests into individual tests on a shared web page context, so that we're only testing one thing at a time instead of having three test conditions in one test
These changes improve the flakiness in the liveblog-live-update and liveblog-ad-limit tests.
I ran these tests a large number of times locally to get these percentage pass rates, to give us a rough idea of how flaky the tests are:
Liveblog-live-update test: 98% pass rate …
> Fix liveblog Playwright tests

- .changeset/poor-lobsters-nail.md
- package.json
- yarn.lock
Update Prebid to the latest version
The latest version bumps babel/core to 7.23.2 to resolve a vulnerability
> Update Prebid to use updated version of babel/core

- .changeset/dull-paws-attend.md
- src/lib/dfp/render-advert.ts
- Collapses the fronts-banner ad slot containers when the ad slot is collapsed
- So we don't show an empty ad slot when we collapse an ad
> Hide fronts-banner ads when collapsing slots

- playwright/fixtures/pages/articles.ts
- playwright/fixtures/pages/blogs.ts
- playwright/fixtures/pages/fronts.ts
- playwright/lib/util.ts
- playwright/tests/parallel-1/consent.spec.ts
- playwright/tests/parallel-2/googletag-switch.spec.ts
- playwright/tests/parallel-2/sponsor-logo.spec.ts
- scripts/fixtures/fixtures-server.js
- scripts/fixtures/fixtures.js
This PR builds on the work in #948, adding support for defining a fixture object within a test. This is base64 * encoded and passed via a query parameter `?fixture=...` to the fixtures server. The fixtures server decodes this object and merges it into the data retrieved from Frontend, in the usual way.
(*) I chose base64 arbitrarily because it's simple to use without pulling in a dependency, although I'm sure their are other schemes which compress JSON better.
There was some discussion (cc @arelra) around POSTing the fixture data, to avoid hitting the maximum length of a URL. This is possible, but when I tried this before it causes a headache trying to fix all of the paths that are relative to DCR, so this PR sticks with a simple GET request.
Allows us to define fixtures closer to the …
> Support defining fixtures locally in E2E tests

- src/lib/dfp/dfp-env.spec.ts
- src/lib/dfp/prepare-googletag.spec.ts
- Moves the existing two tests for shouldLazyLoad to a new file
- Adds a mocked version for getCurrentBreakpoint to test the behaviour of shouldLazyLoad at different breakpoints
- Adds a test to cover when `dll = 1`
We had an incident earlier this year where shouldLazyLoad was not returning the value we expected on mobile view. We wanted to add more rigorous unit testing to help catch this before it becomes a problem in production.
> Unit tests for shouldLazyLoad

- .changeset/wild-flies-flow.md
- src/lib/messenger/background.ts
Centres the video element of the video interscroller to make sure it appears in the middle of the container
| <img width="302" alt="Screenshot 2023-10-24 at 12 51 28" src="https://github.com/guardian/commercial/assets/108270776/68946dcb-43d3-4ff0-8f77-ee890c8c4580"> | <img width="307" alt="Screenshot 2023-10-24 at 12 51 08" src="https://github.com/guardian/commercial/assets/108270776/cf874d8c-a47c-49be-baac-4f864ccd57cf"> |
> Centre video element in video interscroller

- src/lib/dfp/Advert.spec.ts
- src/lib/dfp/Advert.ts
- src/lib/dfp/define-slot.spec.ts
- src/lib/dfp/define-slot.ts
- src/lib/dfp/prepare-googletag.spec.ts
- src/lib/dfp/should-refresh.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/slot-config.spec.ts
This PR adds Ozone testgroup to the GAM request. We add it to ad slot object `DefineSlot` in order to get the same value of the testgroup in prebid. We create the testgroup in `DefineSlot` which is then stored in the Advert class. We read this value back in the `OzoneClientSideBidder` object. 
We’d like to compare Ozone data with Ad Manager data which it wasn't the case before when we had just key-value in the Ozone prebid configuration but not in Google Ad Manager.
> Add Ozone testgroup to Ad slot

- src/lib/dfp/dfp-env.ts
- src/lib/dfp/empty-advert.ts
- src/lib/dfp/fill-dynamic-advert-slot.ts
- src/lib/dfp/fill-slot-listener.ts
- src/lib/dfp/fill-static-advert-slots.ts
- src/lib/dfp/get-advert-by-id.ts
- src/lib/dfp/on-slot-render.ts
- src/lib/dfp/prepare-googletag.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/messenger/disable-refresh.ts
- Remove the `advertIds` property from `dfpEnv` and instead store adverts as a `Map` from their string ids to the adverts themselves. This allows us to store the same information in a single structure, with clearer semantics around getting/setting elements.
- Remove the unused `creativeIds` property. It appears this array is only ever pushed to, and the values never retrieved from it.
Should be clearer when managing which adverts are being tracked in the `dfpEnv`.
In the browser console, for `window.guardian.commercial.dfpEnv.adverts`:
> Use a `Map` to track adverts on the page

- playwright/fixtures/pages/fronts.ts
- playwright/fixtures/pages/index.ts
- playwright/lib/util.ts
- playwright/tests/parallel-2/front-inline-slots.spec.ts
- Added E2E tests for fronts-banner ads
- Since fronts pages may change their layout, this test doesn't intend to ensure the correct amount of `fronts-banner` ad slots are present, since the removal of collections may lead to fewer ad slots being inserted. Instead, this test merely ensures that the first `fronts-banner` ad slot is being inserted.
- Testing coverage
> Added E2E tests for `fronts-banner` ads

- .changeset/thin-goats-lay.md
- package.json
- yarn.lock
add the full hash for the link to the prebid commit
yarn 4 won't stand for the short hash
> Provide the full hash for prebid in dependencies

- src/lib/dfp/on-slot-viewable.ts
- src/lib/spacefinder/article-body-adverts.ts
- This change is a small refactor of the addDesktopInlineAds function
- This function includes logic for inserting inline1 and then as many inlines (inline2, inline3, etc) as will fit.
- The function has been split into two smaller functions: `addDesktopInline1` and `addDesktopInline2PlusAds`
- The logic for inserting inline1 and further inlines is very different and is confusing to follow. Splitting this function into two makes it easier to follow the logic for how the inline1 is inserted. Similarly for inline2+.
> Refactor: separate inline1 and inline2+ slot insertion into separate functions

- .changeset/breezy-beds-sleep.md
- src/lib/header-bidding/prebid/appnexus.ts
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/prebid/improve-digital.ts
Removes the logic checking whether the fronts banner test is running.
The fronts banner test has been removed a while ago and this was missed.
> Remove fronts banner test

- .changeset/warm-seas-grow.md
- src/core/ad-sizes.ts
- src/lib/dfp/ads-in-merchandising-test.ts
- src/lib/dfp/fill-static-advert-slots.ts
- src/lib/dfp/merchandising-high-test.ts
- src/lib/experiments/ab-tests.ts
- src/lib/experiments/tests/ads-in-merch.ts
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/slot-config.ts
- adds MPU size to `merchandising-high` slot
- adds MPU and billboard sizes to `merchandising` slot
- enables header bidding for these slots and sizes
Commercial have identified a number of Black Friday opportunities, one of which is to show ads in `merchandising-high` and `merchandising` slots on fronts and articles.
This change ensures that ads of Billboard and MPU sizes can be added to these slots.
There was an AB test added in guardian/commercial#954 to support showing Billboard ads in `merchandising-high`. This change extends the scope of this test to include new sizes and the `merchandising` slot. 
By extending the scope of the AB test, I thought it appropriate to update the name of the test. Corresponding name changes will also be needed in DCR and frontend.
This change will not be …
> New ad sizes for merchandising slots

- .changeset/proud-turkeys-drive.md
- src/commercial.consentless.ts
- src/standalone.commercial.ts
This PR aims to provide a test to check whether the feature switch for `userFeaturesDcr` is set to true.
This is to enable us to test the Feature switch in the Frontend switchboard, depending on its value, it will force user-features module to be loaded from the desired code base (`dcr` or `commercial`)
> add logic for feature swtich

- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
This PR adds a new `siteId` to be used with the mobile-sticky ads by Index. We add this site id to Index's bid params when we detect the slot supports the mobile-sticky size.
In order to accommodate this, I did a small amount of refactoring to break out the way we pick a site id into two separate functions.
So that Index can bid on this new inventory.
> Add Index site id for `320x50` size ads

- .changeset/olive-meals-travel.md
- src/lib/dfp/render-advert-label.ts
- src/lib/dfp/render-advert.ts
- src/lib/high-merch.ts
Add `ad-slot-container--centre-slot` class to replace the `top-above-nav-ad-rendered` attribute. Which will be removed later so this can release across DCR and Frontend gracefully.
Move the code out of the `render-advert-label` module as it's not to do with labels, it was just there to benefit from the check for fluid.
So we can reuse the centring style semantically for other slots like merchandising.
Also changing to a class name, as this is just used to apply a css style.
This is to fix the centring issues when ads are displayed in merch slots ([details and screenshots in the Frontend PR](https://github.com/guardian/frontend/pull/26694))
> Unify centring slots in container to a single class

- .changeset/chilled-knives-tell.md
- src/lib/dfp/render-advert.ts
This should prevent a momentary flicker of the uncentered ad
> Change order of adding ad centering/rendered classes

- .changeset/quick-ligers-fix.md
- playwright/fixtures/pages/blogs.ts
- playwright/lib/util.ts
- playwright/tests/parallel-3/liveblog-ad-limit.spec.ts
- playwright/tests/parallel-3/liveblog-inline-slots.spec.ts
- playwright/tests/parallel-3/liveblog-live-update.spec.ts
- src/spacefinder/liveblog-adverts.spec.ts
- src/spacefinder/liveblog-adverts.ts
- On liveblog pages where inline ads are inserted server-side, this enables the functionality to insert more ads as new blocks are pushed to the page. This functionality currently exists when inserting inline ads client-side, but we are moving to a server-side strategy.
- So that we can replicate the functionality of client-side inserted ad slots, allowing to make the switch to server-side inserted inline ad slots
> Enable inserting new inline ad slots when new blocks are created on liveblogs

- src/dfp/Advert.spec.ts
- src/dfp/Advert.ts
Adds a helper function that finds the smallest known (i.e. not fluid, fabric, or other ad size of varying width/height) ad size that can be selected to fill a slot.
This is useful when attempting to minimise CLS. Our strategy in this regard is to reserve space on the page for the height of smallest ad size that can be inserted into a slot, then expand the slot if a larger ad size is selected.
Currently, when we find the smallest ad size for a particular slot, it is [hard-coded](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/ArticleContainer.tsx#L146), rather than derived from the list of possible ad-sizes. This means it is susceptible to be incorrect in the future if the list of ad-sizes for a slot changes. For example, the smallest ad size on …
> Adds helper function to find smallest size for slot

- src/experiments/tests/integrate-ima.ts
Extend the IMA AB test until end of Feb 2024.
> Extend IMA AB test

- src/commercial.consentless.ts
- src/standalone.commercial.ts
This PR aims to remove logic which will conditionally load the user-features 
We moved `user-features` to `dcr`: https://github.com/guardian/dotcom-rendering/pull/9362.
As a transitional process, we kept user-features in commercial and added a feature-switch in order to switch back if any issues.
We are now confident it is working as expected in `dcr` and loading appropriately with all cookies.
> remove feature swtch logic for user-features module

- .github/workflows/e2e-playwright.yml
- playwright/tests/article-inline-slots.spec.ts
- playwright/tests/consent.spec.ts
- playwright/tests/front-inline-slots.spec.ts
- playwright/tests/googletag-switch.spec.ts
- playwright/tests/liveblog-ad-limit.spec.ts
- playwright/tests/liveblog-inline-slots.spec.ts
- playwright/tests/liveblog-live-update.spec.ts
- playwright/tests/merchandising-high.spec.ts
- playwright/tests/merchandising.spec.ts
- playwright/tests/mostpop.spec.ts
- playwright/tests/pageskin.spec.ts
- playwright/tests/right-slot.spec.ts
- playwright/tests/sponsor-logo.spec.ts
- playwright/tests/targeting.spec.ts
- playwright/tests/top-above-nav.spec.ts
Use playwright [sharding](https://playwright.dev/docs/test-sharding) to automatically assign tests to the CI workers
Micro improvement in run time and no need for the `parallel-{x}` directories
> Let playwright figure out sharding/parallelism

- .changeset/tidy-lizards-develop.md
This PR adds a changeset for the PR `remove user-features module and related code`: https://github.com/guardian/commercial/pull/1173
In order to release and bump the change in commercial appropriately
> add changeset for removing user features

- .github/workflows/e2e-playwright.yml
- playwright/fixtures/pages/articles.ts
- playwright/lib/load-page.ts
- playwright/lib/util.ts
- playwright/tests/pageskin.spec.ts
- playwright/tests/right-slot.spec.ts
- src/dfp/empty-advert.ts
- src/lib/remove-slots.ts
Some minor tweaks to improve Playwright test stability:
- add logging to help diagnose when ad slots are not fulfilled. This is an indication that we are not requesting an adtest and therefore requesting real ads from GAM which may not fulfill (h/t @Jakeii )
- remove the opt-out specific article and adtest from the articles list
- from the opt-out UI the adtest has been changed from `comdev` to `fixed-puppies-ci`. This makes it easier to ensure we are using the default adtest across gam and opt-out tests
- don' wait for the top-above-nav slot in the page-skin tablet and mobile tests as the pageskin adtest will not appply (> desktop) and so it goes out to regular GAM ads and may not fulfill
- perf tweak to only install Chromium browsers on CI as that is all we test against
> Playwright stability tweaks

- package.json
- yarn.lock
This PR updates Playwright to version 1.40.1
> Update Playwright to version 1.40.1

- .changeset/dull-jeans-reply.md
- src/core/event-timer.ts
- src/dfp/on-slot-viewable.ts
Add a few more marks to commercial metrics
- viewable
- prebidStart
also track metrics for the first 2 fronts-banners
`viewable` - don't know why we don't have this to be honest! Records the timestamp when the slot became viewable
`prebidStart` - because we may [separate running prebid for slots from fetching the ad](https://github.com/guardian/commercial/pull/1057), this could be useful for determining if prebid is running sufficiently in advance.
> More commercial metrics

- .changeset/dry-terms-invite.md
- src/header-bidding/utils.spec.ts
- src/header-bidding/utils.ts
This PR adds the `mobile-sticky` slot to ROW.
Any questions on this format, chat to Alex Amoui @Amouzle 
Increase inventory for the mobile sticky slot.
> Add mobile sticky to ROW 

- .changeset/quick-tomatoes-drop.md
- playwright/fixtures/pages/blogs.ts
- playwright/tests/liveblog-ad-limit.spec.ts
- playwright/tests/liveblog-inline-slots.spec.ts
- src/spacefinder/liveblog-adverts.spec.ts
- src/spacefinder/liveblog-adverts.ts
- Removes code that was responsible for inserting inline ad slots on liveblog pages on page load. This is now done on DCR, where the slots are inserted server-side. The code that remains in `liveblog-adverts.ts` is responsible for inserting ad slots when more content is pushed to the page.
- Adds a Playwright test to check the correct set of ad slots are used.
- Refactor
- DCR now renders inline ad slots on liveblogs server-side
> Remove liveblog client-side ad insertion on page load logic

- src/header-bidding/prebid/bid-config.spec.ts
- src/header-bidding/prebid/improve-digital.spec.ts
- Split the Improve Digital placement ID unit tests out into a separate functions.
- Use table-driven tests via `test.each`.
- Only mock region / breakpoint, and avoid mocking checking the sizes (these functions are pure anyway!).
This should make it easier to contribute to the tests moving forward.
> Refactor Improve Digital unit tests

- src/spacefinder/article-body-adverts.ts
What it says on the tin.
2023 is almost at a close, and this solution to the ads-pushing-down-content bug is fairly settled now.
> Make comment in `article-body-adverts.ts` more reflective of reality

- .changeset/nasty-bikes-melt.md
- src/header-bidding/prebid/appnexus.ts
- src/header-bidding/prebid/bid-config.spec.ts
- src/header-bidding/prebid/bid-config.ts
- src/header-bidding/prebid/improve-digital.spec.ts
- src/header-bidding/prebid/improve-digital.ts
This PR enables Prebid for mobile-sticky in ROW and add the correct placement IDs for each Prebid vendor. We also refactored the unit tests and added few more to test mobile-sticky in Ozone, Ozone US, Improve, OpenX. 
In the future we should add more tests for Ozone and AppNexus.
A follow up work #1187
> Enable Prebid for mobile sticky web in ROW

- .changeset/itchy-hats-share.md
- src/dfp/render-advert.ts
Currently when a user changes the viewport size from desktop to tablet or phone size, the merch slots still contain the `billboard` ad size which gets cut off.
This PR should collapse the `merchandise` and `merchandise-high` slot when the viewport is resized and therefore if billboard ad no longer fits in viewport.
This PR adds an callback which adds a class to `dfp-ad--merchandising` element for thje `merchandising` and `merchandising-high` ad slots.
This class is conditionally added on the premise that the adSize is `billboard` (970x250)
As a result of testing in CODE we discovered that some ads were larger than `billboard` ad like 1300x250.
As a result the aproach was to include non `fluid` ads as well.
This is essential so that code in `dotcom-rendering` can detect this class and in …
> collapse merchandise ad slots on viewport resize

- .changeset/spotty-carrots-change.md
- src/core/event-timer.ts
- src/core/targeting/build-page-targeting.spec.ts
- src/core/targeting/build-page-targeting.ts
- tsconfig.core.json
Use the performance API to determine the type of navigation so that we can better deduce if this is the users first visit.
[The performance API's navigation events let us distinguish the navigation type
](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/type#value)
Only if the referrer is empty and the navigation type is `navigate` can we assume this is the users first visit, otherwise they have refreshed or clicked the back/forwards button.
So we can target ads without consent only on their "first visit" to the site.
> Improve consentless first visit detection

- .changeset/lovely-vans-help.md
- src/core/targeting/build-page-targeting.ts
- tsconfig.core.json
Use relative import, not doing this has led to a strange failure in frontend https://github.com/guardian/frontend/actions/runs/7478681099/job/20354162665?pr=26808
> Use relative import path between core modules

- .changeset/late-pumas-camp.md
- package.json
This updates various internal peer dependencies to request their latest version.
WebEx are seeking to enforce met peer dependencies in DCR and this clears a blocker for them https://github.com/guardian/dotcom-rendering/issues/10204
> Update peer dependencies causing conflicts in DCR

- docs/spacefinder/readme.md
- playwright/tests/spacefinder-debugger.spec.ts
- src/init/consented/article-body-adverts.ts
- src/spacefinder/spacefinder-debug-tools.ts
- src/spacefinder/spacefinder.ts
This PR makes a couple of small changes to the Spacefinder debugger:
- Renames `inline2` to `subsequent-inlines` to reflect that the button means all inlines after inline1, not just inline2
- Selects the first button in the Spacefinder control panel by default, so that we have the annotation appearing on the page and it doesn't appear blank
- Updates the documentation to reflect the fact that your URL only needs to contain `?sfdebug` - there's no difference between using `?sfdebug=1` or `?sfdebug=2` any more
At the moment, when you load a page with `?sfdebug` in your URL, only the ad slots are highlighted by default, not the paragraphs, so the functionality of the debugger isn't immediately clear without clicking on a button on the control panel.
The name of inline2 was also misleading - …
> Updates to the Spacefinder debugger

- .changeset/strange-penguins-tickle.md
- src/init/consented/fill-slot-listener.ts
- src/init/consented/prepare-googletag.ts
- src/standalone.commercial.ts
Move the fill slot listener to be initialised in `standalone.commercial`
We need the event listener to be added ASAP.
At the moment it's possible for the event to be sent before the listener has been setup.
The particular case where this is happening is the `article-end` slot. If the page is refreshed while it's in view, the slot is inserted after the fixed ad slots are initialised but before the fill-slot-listener has been setup, resulting in an empty slot.
Adding `window.googletag.cmd.push` will ensure the slot will only be filled if googletag loads.
> Move fill slot listener to standalone

- src/header-bidding/prebid/appnexus.spec.ts
- src/header-bidding/prebid/appnexus.ts
- src/header-bidding/prebid/bid-config.spec.ts
This PR adds more Ozone prebid unit tests and creates AppNexus prebid tests which was noted in a previous PR #1190.
All the added tests checks if `placementID` is correct based on region, breakpoint and ad size. 
Covering more unit test cases.
> Add Ozone and AppNexus prebid unit tests for placementID

- .changeset/hungry-rivers-relate.md
- package.json
- src/ad-verification/prepare-ad-verification.spec.ts
- src/dfp/Advert.spec.ts
- src/experiments/ab-ophan.ts
- src/init/consented/liveblog-adverts.spec.ts
- src/init/consented/prepare-googletag.spec.ts
- src/init/consented/third-party-tags.spec.ts
- src/types/modules.d.ts
- yarn.lock
Replace `ophan-tracker-js` with `@guardian/ophan-tracker-js`
`ophan-tracker-js` is deprecated and we should replace with `@guardian/ophan-tracker-js`.
v2.0.4 will also bring in this fix to how Ophan constructs its requests: https://github.com/guardian/ophan/pull/5624
> Replace `ophan-tracker-js` with `@guardian/ophan-tracker-js`

- .changeset/neat-mayflies-glow.md
- package.json
- yarn.lock
Updates Prebid to bring in the latest changes. This will resolve the peer dependency mismatches with dotcom-rendering.
This update has been tested on CODE to make sure that Prebid still runs as expected.
> Update Prebid to resolve peer dependency mismatches with DCR

- .changeset/curvy-zebras-travel.md
- package.json
- scripts/bump_commercial.sh
- src/init/consented/prepare-prebid.ts
- src/lib/header-bidding/prebid/prebid.spec.ts
- yarn.lock
Since https://github.com/guardian/Prebid.js/pull/145 we now publish our fork of prebid.js to npm:
https://www.npmjs.com/package/@guardian/prebid.js
We can now reference the version of `@guardian/prebid.js` from npm instead of attempting to reference a github commit which causes issues for yarn's cache, Snyk and Dependabot.
This also [bumps the version to 8.34.0](https://github.com/guardian/Prebid.js/pull/146) as a test of the new publishing flow.
Tested on CODE
> Use `@guardian/prebid.js@8.34.0` from npm

- .changeset/honest-rivers-drive.md
- src/core/messenger/background.ts
- Sets the height of the background to `100vh`
- There is unintended zoom on mobile devices when changing scrolling direction, when the viewport changes dimensions depending on which direction the user is scrolling. This is often when the address bar pops up/down when the user scrolls up. The background interscroller image covers the screen, so when the viewport aspect ratio changes, the image can look zoomed in/out
- `vh` (same as `lvh`. Less explicit, but [better supported](https://caniuse.com/viewport-unit-variants)) was preferred over `svh`, because with the latter there can be some white space below the ad image when the viewport is at its tallest: 
- The image still "jumps" up and down slightly when changing scroll direction. This PR does not attempt to fix this bug.
| Before | …
> Fix issue with unintended zoom on interscrollers

- .changeset/big-kiwis-live.md
- src/experiments/tests/mpu-when-no-epic.ts
This PR is a part of the `mpuWhenNoEpic` AB test work which started in #1157. We first ran the tests for a week without Teads which was a blocked work for some time because it required external changes (Teads team) but now the work has been done and we will set the tests back live for a week. 
Testing if Teads in `article-end` MPU would increase the revenue towards our Advertising.
> Extend expiry for mpuWhenNoEpic AB test to set back live

- .changeset/serious-lemons-kick.md
- src/init/consented/prepare-googletag.ts
We're unsure how empty strings come through to ad manager, safer to set it to 'empty'.
> Explicitly set cookieDeprecationLabel targeting to 'empty'

- .changeset/few-ladybugs-explain.md
- package.json
Missed the downgrade of the cmp peer dep following https://github.com/guardian/commercial/pull/1244
> Downgrade cmp peer dep

- playwright/tests/targeting.spec.ts
This test is flagging a live issue with the TCF Prebid vendor being dropped from Sourcepoint which also means Prebid header bidding is failing for newly consented users in TCF.
We will be transferring to a custom vendor asap.
This PR skips the prebid test until we add the new vendor.
> Skip prebid e2e test

- playwright/fixtures/pages/fronts.ts
- playwright/fixtures/pages/index.ts
- playwright/lib/util.ts
- playwright/tests/front-inline-slots.spec.ts
Rename TagFront endpoint to TagPage in e2e tests following https://github.com/guardian/dotcom-rendering/pull/10542
> Rename TagFront endpoint to TagPage

- .changeset/healthy-guests-kick.md
- package.json
- playwright/tests/targeting.spec.ts
- src/init/consented/prepare-prebid.spec.ts
- src/init/consented/prepare-prebid.ts
- yarn.lock
The TCF global Prebid vendor has been dropped from Sourcepoint which means Prebid header bidding is failing for newly consented users in TCF.
This PR adds an additional check for consent for the new custom Prebid vendor so that we maintain consent for existing consented users and newly consented users.
If the user does not consent to either vendor Prebid will not load.
> Check global and custom vendor for Prebid

- .changeset/shiny-tigers-tease.md
- src/init/consented/prepare-prebid.spec.ts
- src/init/consented/prepare-prebid.ts
Improve readability of prebid consent check and log
The logic is equivalent
I'm adding a changeset to force a release
> Improve readability of prebid consent check and log

- .changeset/wicked-guests-protect.md
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/slot-config.ts
This PR enables `prebid` for the new ad slot added to `crossword-banner-mobile`.
Currently the ad slot does communicate with GAM and has been implemented through the this PR: https://github.com/guardian/commercial/pull/1229
This will allow us to better monetise these slots, by exposing them to more demand.
| Prebid.js Event | 
|----------|
| <img width="560" alt="Screenshot 2024-02-14 at 12 39 21" src="https://github.com/guardian/commercial/assets/49187886/cc40e117-fe19-4b3c-aa25-fef25c2af08e">  |
> enable prebid for mobile banner

- .changeset/fair-turkeys-flash.md
- src/lib/header-bidding/prebid/appnexus.ts
- src/lib/header-bidding/prebid/bid-config.ts
Adds a 'slot' keyword to the AppNexus bidder to send the slot name with the request.
This will allow better targeting for ads coming via AppNexus as they will now be able to target by slot.
This has been tested locally and the slot name is being added as expected (note 'and' is the bidder name for AppNexus):
> Add slot name to AppNexus bidder

- .changeset/warm-planes-decide.md
- package.json
- yarn.lock
Bumps the consent-management-platform to the latest version
To include the final parameter in the onConsentChange function as well as some dependency bumps.
> Bump consent-management-platform to 13.11.1

- .changeset/hungry-hounds-rule.md
- src/insert/comments-expanded-advert.ts
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/slot-config.ts
- Enables Prebid for desktop `comments-expanded` ad.
- Don't run Prebid for mobile `comments-expanded` ads - we only want MPU sizes in these slots and Prebid can send through ads that aren't the size we expect.
- Uses a minHeight on the mobile discussion ads ad slot instead of a fixed height on the container.
Note that the mobile `comments-expanded` ads are numbered in the same way as `inline` or `fronts-banner` ads, so by adding `comments-expanded` to slot-config, we're only targeting the desktop slots with the name `comments-expanded`, not the mobile slots that are called `comments-expanded-2` for example.
Desktop `comments-expanded` ads have never had Prebid enabled on them. Hopefully by enabling it we can get some higher value ads in that slot. I've tested locally and it seems to be …
> Changes to Prebid for comments-expanded ads

- .changeset/spicy-rats-shout.md
- src/events/empty-advert.spec.ts
- src/events/empty-advert.ts
- Removes the top-level ad container from the DOM when removing a `fronts-banner` advert
- Adds a test
- The top-level ad container has a minimum height on it to prevent layout shift, so we need to remove this too when removing a `fronts-banner` advert
https://github.com/guardian/commercial/assets/9574885/22e2dd0c-35dc-459d-9a16-c8a647172062
https://github.com/guardian/commercial/assets/9574885/5df91746-db79-477c-bffb-15ae58ac6256
> Remove top-level container from DOM when removing fronts-banner ad

- .changeset/chilly-candles-visit.md
- src/insert/comments-expanded-advert.ts
- Inserts an advert between comments on frontend-rendered pages when a `comments-loaded` [Custom Event](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) is received. [PR to insert ads on crossword pages](https://github.com/guardian/frontend/pull/26943)
- Inserts `comments-expanded` adverts _between_ top-level comments, instead of inside a top-level comment.
- Moves the advert container inside an `li` element, since the parent is a `ul` element.
- For the `comments-expanded` ad on DCR desktop pages, the resizeObserver has been removed. This is because we now fire the event once the comments have been loaded, instead of when the button has been clicked, so we know how much space is available and do not need to wait. [DCR …
> Add ads between comments on frontend-rendered pages

- src/core/ad-sizes.ts
- src/define/Advert.spec.ts
This PR adds sizemappings for tablet in `fronts-banner`, defining `leaderboard`.
Related PR: https://github.com/guardian/dotcom-rendering/pull/10766
As a result of including ads to `fronts-banners` in `DCR` for the tablet size (see here), we need to update the sizeMappings to include a request for Leaderboard size, to effectively populate the ad slot in DCR.
Size mappings from googletag:
> adds tablet to fronts banner sizemapping for gam

- docs/ab-testing/readme.md
- Add documentation on creating AB tests
- We have documentation in [Frontend](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/01-ab-testing.md) and [DCR](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/docs/development/ab-testing-in-dcr.md) for how to set up AB tests in each repo. For commercial, it can be hard to know where to start and what to do for each type of test (client-side and server-side), so this document can serve as a starting point when needing to add an AB test for commercial purposes.
> Add AB testing documentation

- .changeset/tough-rice-enjoy.md
- playwright/fixtures/pages/articles.ts
- src/insert/spacefinder/article-body-adverts.ts
Remove the `hr` element as a candidate from mobile spacefinder
These elements have a large top margin (~50px), an ad would obviously be above this margin but spacefinder is unable to account for it, leading to ads being inserted a tad closer than we'd like to images if a `hr` follows an image. 
With the introduction of the `bypassMinBelow` rule it's unnecessary to have it be a candidate anyway.
Before:
After:
> Remove the `hr` element as a candidate from mobile spacefinder

- package.json
`prettier:fix` is already run as part of `lint-staged`
No changeset needed for this change
> Remove duplicate prettier from precommit hook

- playwright/fixtures/pages/articles.ts
- playwright/tests/comments-expanded.spec.ts
Adds a Playwright test to check that the desktop and mobile versions of the `comments-expanded` ads are added when the comments are opened.
In the comments on [this PR](https://github.com/guardian/commercial/pull/1239), I promised to add an E2E test for the `comments-expanded` ads when the new mobile ads were stable.
> Add Playwright test for comments-expanded ads

- src/events/on-slot-viewable.ts
Log to commercial logger when slot is viewable
So we have insight into when a slot is [viewable](https://www.iabuk.com/news-article/quick-qa-viewability)
> Log when slot is viewable

- .changeset/fifty-glasses-wait.md
- src/insert/mobile-crossword-banner.ts
- Shows the crossword mobile banner ad in position 1 (below controls) for all users
- Shows the crossword mobile banner ad in position 2 (above controls) for users in the AB test
Prior to this change, the ad slot would be placed below the controls element as part of the "Option 1" server side test https://github.com/guardian/commercial/pull/1229.
This has been tested on other crossword pages that we have:
- [Cryptic](http://localhost:9000/crosswords/cryptic/29335)
- [Quiptic](http://localhost:9000/crosswords/quiptic/1269)
- [Everyman](http://localhost:9000/crosswords/everyman/4039)
- [Speedy](http://localhost:9000/crosswords/speedy/1484)
- The AB test results no significant reduction in UX metric following the introduction of this change and resulted in increased revenue.
- We would like …
> Crossword mobile banner advert - Send live and AB test

- .changeset/yellow-hotels-train.md
- package.json
- src/init/consented/comscore.ts
- src/types/global.ts
- yarn.lock
To deal with the depreciation of third party cookies in Google Chrome, Comscore has requested changes to the tag which currently sits on site. The changes will allow them to drop their cookie as a first-party cookie on our domain.
This has been through and been approved as part of the Tech Review process.
Once added, if consent is given for comscore a new first party cookie will be added `_scor_uid`
> Enable first party cookie for comscore

- .changeset/slow-falcons-turn.md
- src/insert/comments-expanded-advert.ts
- Remove DCR discussion ads feature switch
- This feature has been live for a while and the switch is no longer needed
> Remove DCR discussion ads feature switch

- src/experiments/tests/mpu-when-no-epic.ts
This PR extends mpuWhenNoEpic AB test until we have a chat with @Amouzle to check if it is still needed.
Expires before Easter break and we still don't know if it is needed or we can remove it.
> Extend mpuWhenNoEpic AB test

- .changeset/clever-brooms-judge.md
- src/init/consentless/define-slot.ts
- src/init/consentless/render-advert-label.ts
Checks the opt out ad request for the `'NATIVE'` tag which has been added to the native template in the ad server. If present, we add an `ad-slot--native` class to the ad slot. We then check that this class isn't present before adding a label.
Also removes some redundant logic that was a workaround from when we only used to show house ads in the merch slots. This is no longer needed so we can tidy it up 🧹
We'll be using opt out to show some native templates but they currently appear with an advertisement label, which we don't want. This change aligns the code with the way these ads show when they come from GAM.
> Don't add an advertisement label to native templates served via opt out

- src/insert/spacefinder/spacefinder.ts
Removes an `amiused` call which has been there for a pretty long time.
It is used:
Removing this means we can reduce a bit of noise in our logging.
> Remove old amiused call

- .changeset/calm-dryers-poke.md
- src/core/event-timer.ts
Add a new commercial metric _property_ that we can set when we detect the user is running an ad blocker.
Note there is an [existing metric](https://github.com/guardian/commercial-core/blob/03b572557fa492e05b7f30a896acd23d527df1bf/src/core/send-commercial-metrics.ts#L54), but we'd like to keep this distinct as we roll out the new [AdBlockAsk](https://github.com/guardian/dotcom-rendering/pull/11124).
So that we can record the number of pageviews for which we perform adblock detection.
> New commercial metric for ad block detection

- .changeset/friendly-zoos-float.md
- src/events/empty-advert.spec.ts
- src/events/empty-advert.ts
This PR loosens the assumptions around how the DOM is structured for banner slots (that's front banners and the top-above-nav "banner" container element).
Previously, we assumed the `top-fronts-banner-ad-container` and `top-banner-ad-container` must be direct parents of the ad slot container. Instead, these can now be any ancestor of the ad slot container. This allows for more flexibility in how the DOM is structured, with additional elements placed between the `ad-slot-container` elements and the top-level banner containers.
Fix a bug whereby the top-above-nav slot is no longer properly collapsed, due to a change in the DOM structure introduced in https://github.com/guardian/dotcom-rendering/pull/11124.
The existing unit tests pass, and I've added three test cases that assert the desired …
> Less strict DOM structure for banner containers

- .changeset/metal-spoons-build.md
- package.json
- pnpm-lock.yaml
Whatever code used it has been subsequently been removed, so we can drop it
> Drop @guardian/support-dotcom-components as a dependency

- .changeset/brown-tables-act.md
- src/core/event-timer.ts
- src/core/messenger/background.ts
Sends the percentage of a video interscroller ad that was shown to a user as part of commercial metrics. Also finds the `creativeId` of the interscroller so that we can match video progress data to specific creatives. We do this by searching the slots on the page to find which one is using the interscroller template, as only one native interscroller will appear on any one pageview. Tested with two different creatives on CODE and the data is added to commercial metrics payload as expected:
DAP would like to be able to offer video progress tracking for our native ads, as this is often a metric that advertisers are particularly interested in which we don't currently support.
> Interscroller video progress tracking

- .changeset/honest-pants-melt.md
- src/init/consentless/render-advert-label.ts
We added a native class to native ads in opt-out so that we can serve them without labels in this PR: https://github.com/guardian/commercial/pull/1334
This tag has ended up being added to fabric ads in opt-out, but unlike their GAM counterparts they have no built-in label. There's a takeover going live on monday morning and the native templates for opt-out can't be edited without the opt-out team, so this quick fix is the only way we can get labels on these takeover ads in time for monday.
Next week we'll look to fix the tagging so that we can have labels on fabrics but not on the labs multiple.
Takeover banner ads (tested locally):
> Add labels for opt-out fabric ads

- .changeset/clean-tools-warn.md
- package.json
- pnpm-lock.yaml
Pin typescript@5.3.3, fix peer deps and remove resolution
We specify 
https://github.com/guardian/commercial/blob/53f2a08107f7137d63eb197d476e45fed9d09b08/package.json#L97
But have a resolution to:
https://github.com/guardian/commercial/blob/53f2a08107f7137d63eb197d476e45fed9d09b08/package.json#L117-L119
There's more work to pin and fix up our deps but keeping this self contained.
> Pin typescript@5.3.3 and remove resolution

- .changeset/rich-schools-brake.md
- .eslintignore
- src/core/__mocks__/ad-sizes.ts
- src/core/ad-sizes.ts
- src/core/create-ad-slot.spec.ts
- src/core/create-ad-slot.ts
- src/core/lib/breakpoint.spec.ts
- src/core/lib/breakpoint.ts
- src/define/Advert.ts
- src/define/define-slot.ts
- src/init/consented/remove-slots.ts
- src/lib/header-bidding/slot-config.spec.ts
Add a size mapping for `interactive` ad slots to our size mapping
Rather than fallback to data attributes, merge them with any other size mappings for that slot.
Allows us to remove the `outofpage` and `empty` sizes from interactive slot data attributes.
> Tweaks for interactive ad article slots

- docs/spacefinder/readme.md
This is a small change to fix the broken link in Spacefinder rules in the docs.
A working link to the correct file name and path.
> Fix broken link for article.ts in spacefinder docs

- .changeset/wicked-apricots-warn.md
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/carrot-traffic-driver.ts
`:scope` was introduced to spacefinder selectors in https://github.com/guardian/commercial/pull/1337, but some selectors were missed
Consistency
> use `:scope` everywhere

- .changeset/two-dolls-call.md
- playwright/fixtures/pages/fronts.ts
- src/insert/spacefinder/article.ts
This PR changes the order of the `im` and `inline1` slots so now we have the `im` below `inline1`. 
Occasionally `hasInlineMerch` will be true but won't serve, due to unsupported targeting being added to the line items, this causes `inline1` to be lower than it should be cause it will still try to avoid `im`.
`inline1` is our most valuable slot so changing the order seemed like the best way to avoid this `im` issue.
This change is tested locally and in CODE with this [article](https://www.theguardian.com/society/2024/apr/18/scottish-gender-clinic-pauses-prescribing-puberty-blockers-to-under-18s) using Spacefinder debug which you can use by adding `?sfdebug` at the end of the url.
Reduce revenue impact when the above `im` issue occurs. 
| ----------- | …
> Move `im` below `inline1`

- .changeset/spicy-readers-return.md
- src/core/event-timer.ts
Add `didDisplayAdBlockAsk` to event timer properties
Not every time we've detected an ad blocker will we show the ad block ask message, so add this prop to record it separately.
> Add `didDisplayAdBlockAsk` to event timer properties

- .github/workflows/ci.yml
Run changeset publish as changeset-bot
This should allow workflows/checks to run on version bump PRs so we don't have to force-merge
> Run changeset publish as changeset-bot

- .changeset/great-beds-smash.md
- src/insert/comments-expanded-advert.ts
- src/insert/mobile-crossword-banner.ts
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/spacefinder.ts
Removes the mega test from the commercial code.
The results are in, and we'll be keeping our changes. See PR that introduced the mega test here: https://github.com/guardian/commercial/pull/1318
> Remove mega test

- .changeset/itchy-cows-relate.md
- playwright/tests/front-inline-slots.spec.ts
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/spacefinder-debug-tools.ts
- src/insert/spacefinder/spacefinder.ts
Handle where spacefinder candidates/opponents overlap each other by improving the check for opponents being below - to also a check that `opponent.top` is below `candidate.bottom` and handling when opponents/candidates are adjacent/overlapping.
I suspect this may be happening now due to #1271 which fixed some bugs in the `testCandidate` code, there's a rule [here](https://github.com/guardian/commercial/pull/1377/files#diff-40044f4d0100808638e7ed46790f93dbaff168485b9043e4a6bacb4df4578ae6L174) that set a 500px margin for interactives that I think was a "hack" that worked with the old `testCandidate` but not the new one.
With this change spacefinder can now handle a bit more gracefully this edge case and can remove the "hack" setting the margin to a more reasonable 100px.
Also updated …
> Spacefinder handle opponents/candidates overlapping

- .changeset/afraid-nails-speak.md
- src/experiments/ab-tests.ts
- src/experiments/tests/deeply-read-right-column.ts
- src/insert/spacefinder/article.ts
Adds 650px to top of desktopRightRailAds when in deeplyReadMostViewed test variant
Corresponding change to DCR (pr https://github.com/guardian/dotcom-rendering/pull/11299)
Frontend (pr https://github.com/guardian/frontend/pull/27084)
> Deeply read right ab test

- .changeset/lovely-zoos-wink.md
- src/core/send-commercial-metrics.spec.ts
- src/core/send-commercial-metrics.ts
replace `sendBeacon` with fetch for sending commercial metrics
fetch should be more reliable than `sendBeacon`
Upon testing `fetch` will go through on the occasions that `sendBeacon` is blocked.
@emma-imber also [did some testing on this](https://github.com/guardian/commercial/pull/888) a while back and determined `fetch` to be more reliable.
> use fetch to send commercial metrics

- .changeset/sour-peas-train.md
- src/insert/spacefinder/article.ts
The current rule specifies the first ad can appear 100px from the top of the article. This means that sometimes the first ad appears after the opening sentence/paragraph, and this has raised concerns within the editorial team. 
Increasing the rule to 200px should mean that the at least a couple of sentences are included before the first ad on mobile.
Testing suggests the issue is not as common on desktop (where the rule is 300px).
> Increase spacefinder mobile minAbove distance by 100px

- .changeset/green-clouds-hammer.md
- src/insert/spacefinder/article.ts
Increase spacefinder mobile minAbove distance to 250px
Tweak to #1384 
| ![before][] | ![after][] |
[before]: https://github.com/guardian/commercial/assets/7014230/bda2336c-59a6-4956-8518-761fd395bb55
[after]: https://github.com/guardian/commercial/assets/7014230/a81344e3-e630-4ca2-95eb-224d637e818c
> Increase spacefinder mobile minAbove distance to 250px

- .changeset/selfish-buses-press.md
- src/core/messenger/background.ts
Uses an intersection observer to play the video interscroller when it's in the viewport, and pause it when it isn't. This is the default behaviour on Chrome on Android, but not on other browsers.
This replicates the behaviour of the fabric video ad, and should improve the accuracy of the video progress data we've been seeing.
Video does not pause when we scroll away from the ad.
https://github.com/guardian/commercial/assets/108270776/dad6c0cb-059b-4a0e-8c69-ea28f00d10ff
Video does pause when we scroll away from the ad.
https://github.com/guardian/commercial/assets/108270776/c5e85c9f-94f6-4301-8b9c-888f6288513e
> Only play the video interscroller when it's in the viewport

- .changeset/shaggy-shoes-sniff.md
- src/core/messenger/background.ts
Bypasses the commercial metrics sampling for the video interscroller progress reporting.
We want to get progress data for all video interscroller ads, not 1% of them.
> Bypass metrics sampling for video interscroller progress data

- .changeset/swift-bears-eat.md
- src/core/ad-sizes.ts
This enables a new ad size 300x50 to `mobile-sticky`.
I tested in CODE and using a VPN to be in a region that has a `mobile-sticky` slot. Here is a screenshot from `googletag.openConsole()` with the new size.
This request was made by AdOps which will give us the opportunity to serve creatives in smaller size.
> Add 300x50 ad size to mobile-sticky

- .changeset/orange-apes-behave.md
- src/lib/header-bidding/slot-config.spec.ts
- src/lib/header-bidding/slot-config.ts
This PR adds 300x50 ad size to Prebid for `mobile-sticky`. It's part of the work done in https://github.com/guardian/commercial/pull/1403
We can use Prebid for the new size in `mobile-sticky` slot.
> Add 300x50 size to Prebid for `mobile-sticky`

- .changeset/loud-cameras-learn.md
- src/insert/spacefinder/spacefinder-debug-tools.ts
- src/insert/spacefinder/spacefinder.ts
Moves the check for the `?sfdebug` url param to be before the debug tools are imported. This allows us to only import the debug tools if someone wants to run debug mode.
At the moment, we import the 6kb of code needed for spacefinder debug mode for all users. By selectively importing when the `?sfedebug` param is present, we can ship less javascript to users.
> Only import sf debug tools if sfdebug url param is present

- .changeset/big-pens-agree.md
- src/core/messenger/background.ts
Adds a test `sendBeacon` and `fetch` call to 10% of messenger background calls.
Jake and Ashish realised that `sendBeacon` is blocked by some ad blockers. In earlier testing, we discovered that `sendBeacon` is less reliable than `fetch`. It would be good to test if **all** of the flakiness of `sendBeacon` is explained by ad blockers. By adding a test to a part of the code that only executes if there’s no ad blocker, we can see if we then observe parity between `fetch` and `sendBeacon`.
This messenger code is only called by certain commercial templates, which will only be sending messages on the page if there is no ad blocker. This allows us to control for ad blockers, and hopefully to determine if ad blockers are the sole cause of `sendBeacon`'s flakiness.
> Add test to compare sendBeacon and fetch numbers for users with no ad blocker

- src/core/messenger/background.spec.ts
Fixes the test error in the background spec file by defining sendBeacon as a jest function.
For some reason this test passed fine on the PR but then after merging it flaked on main with the error: `TypeError: window.navigator.sendBeacon is not a function`. Hopefully this fixes the error.
> Define sendBeacon in test file

- .changeset/nervous-papayas-type.md
- src/core/messenger/resize.ts
This allows the viewport to be made <980px in width or to change orientation on an iPad without the native ad getting cut off at the the bottom.
Native ads `resize` on render and therefore change ratio (width and height), therefore when we reduce the width of the viewport or change the orientation on the iPad the bottom gets cut off.
The CSS states a max-height of 624px which persists at all breakpoints.
The `resize` is a Post Message, so when messenger tells us to resize (which only happens for in-house creatives) it should also check the container and remove max-height if necessary.
| Before | After |
|---|---|
| <img width="320" alt="Screenshot 2024-06-17 at 16 42 03" src="https://github.com/guardian/commercial/assets/49187886/6510737f-a6f8-4833-b850-6b101fe39a9a"> | <img width="350" …
> fix native ads cut off with max height

- .changeset/stupid-turkeys-learn.md
- src/core/messenger/background.ts
Reduces the sendBeacon test sampling rate from 10% to 1%.
We're getting loads more data than I thought, and we got about 73000 data points just for yesterday. We definitely don't need that much so I'm reducing the sampling. I would rather sample at a lower rate over a longer time period to better account for different usage patterns.
> Reduce beacon test sampling

- .github/dependabot.yml
Major versions may contain breaking changes, so we'll want to do those bumps manually
> Tell dependabot not to bump major versions

- .changeset/early-dots-stare.md
- src/core/messenger/passback.ts
This PR removes the second layout shift from `inline1` if Teads passes back the slot and centres in the middle of the slot in the case of an `mpu` ad size. Check the [ticket](https://trello.com/c/YxHvJgnv/2931-blip-reduce-layout-shift-for-inline1-teads-step-1) for more info.
For context we reserve `250px` for `inline1` in articles. Teads resizes it to `350px` (first shift).
If Teads passback then it resizes back to `250px` (second shift).
I made some checks to implement the changes just for desktop as we don't want to have a `350px` height for mobile.
These changes are tested locally and in CODE.
You can test an mpu locally by adding `?adtest=teadspassback2022` to the end of the article URL.
You can test a direct sold outstream by adding `?adtest=outstreampassback2024` to this article URL …
> Reduce CLS for inline1 when Teads passback - step 1

- .changeset/shiny-turkeys-breathe.md
- src/insert/spacefinder/article.ts
This PR reduces the spacefinder mobile minAbove distance to 250px
| ![localhost_3030_Article_https___www theguardian com_us-news_article_2024_may_17_university-of-georgia-cop-city-lawsuit_sfdebug(iPhone 12 Pro) (3)](https://github.com/guardian/commercial/assets/49187886/97a90de6-0b8e-434d-a59b-8de1986d39f9) | ![localhost_3030_Article_https___www theguardian com_us-news_article_2024_may_17_university-of-georgia-cop-city-lawsuit_sfdebug(iPhone 12 Pro) (6)](https://github.com/guardian/commercial/assets/49187886/e80f2dd3-3e1d-457f-bc2e-c571fdcc2214) |
> reduce min distance from top of article to 200px for spacefinder

- .changeset/five-crabs-sparkle.md
- src/core/ad-sizes.ts
Add sizes for new slot that will appear at the top of liveblogs, only when targeted with an ad.
> Add liveblog-top ad sizes

- .changeset/silly-pandas-give.md
- src/core/send-commercial-metrics.ts
- src/core/types.ts
- src/types/global.ts
Adds a new property - `commercialMetricsInitialised` - to the Guardian window config.
At the moment, `bypassCommercialMetricsSampling` doesn't work in the commercial repository, because DCR initialises the metrics, so the commercial bundle doesn't have access to that version of the `initialised` variable. By storing the state of initialisation on the window instead, we can share the value between DCR and commercial, which means `bypassCommercialMetricsSampling` should now work for commercial code.
Tested on CODE:
> Add commercialMetricsInitialised to window

- .changeset/rude-plants-happen.md
- src/core/messenger/background.spec.ts
- src/core/messenger/background.ts
Removes the test added in https://github.com/guardian/commercial/pull/1416
The test has been running for over a week so we've got more than enough data now.
> Remove sendBeacon test for users with no ad blocker

- .husky/post-merge
- .husky/pre-push
This PR adds a 'post-merge' hook to git with husky:
- If dependencies have been updated then run `pnpm i` to reinstall them
- If the .nvmrc has changed, notify users to install the new version
Just to be confident that no issues will happen because someone forgot to update the dependencies and it should improve the developer experience.
> Add post-merge hook to run `pnpm i` on git pull

- .github/dependabot.yml
This PR groups dependencies in `dependabot.yml` and adds more configuration rules to make it granular and easier to keep up to date with dependency bumps in Commercial.
The main reason is to avoid being out of sync with other dependencies we rely on to run Commercial or the other way around when other dependencies relies on Commercial . This will save us time and development effort.
> Configure dependabot to keep up to date with dependency bumps in Commercial

- .changeset/wise-schools-bathe.md
- src/init/consentless/define-slot.ts
- src/init/consentless/render-advert-label.ts
Adds a class to opt out ads with the `HOSTEDBY` tag. If this class is present on an ad, we don't attach an ad label.
We'd like to start serving more native templates on opt out, so we need to remove the label from certain templates.
> Don't add advertisement labels to Hosted By ads served by opt out

- .changeset/brave-peaches-confess.md
- src/core/send-commercial-metrics.ts
- src/types/global.ts
Refactors the metrics bypass functionality to make it easier to read and work with.
At the moment, metrics are sent when either a `visibilitychange` or `pagehide` event listener fires. The event listeners are added when someone is in the dev environment (eg testing locally or on CODE) and when someone is in the sampling group. The `bypassCommercialMetricsSampling` function works by adding the event listeners when called.
This isn't what you would intuitively expect the `bypassCommercialMetricsSampling` function to do. It also means that listeners could be coming from DCR or from commercial, which might be harder to trace and debug.
Instead, this PR refactors the code to add listeners as part of the `initCommercialMetrics` function. This means listeners only get added in one place, at one …
> Refactor metrics bypassing

- .changeset/fluffy-meals-shake.md
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/rules.ts
Move spacefinder rules to their own file
Remove the use of the "catch-all" rules, aka the ones that look like:
```js
let ignoreList = `:scope > :not(p):not(h2):not(ul):not(.${adSlotContainerClass}):not(#sign-in-gate):not(.sfdebug)`;
if (hasLeftCol) {
ignoreList +=
':not([data-spacefinder-role="richLink"]):not([data-spacefinder-role="thumbnail"])';
}
```
What these selectors are doing is selecting elements that are not candidates or already have an opponents selector rule, effectively a "catch-all" for any other elements.
The behaviour (and the selector) is a little fuzzy and confusing, it would be better if we could reliably select all the elements we want to avoid.
Since all articles are rendered by DCR now, we know all the blocks/elements that can appear …
> Spacefinder rule optimisation

- .husky/post-merge
- .husky/pre-commit
- .husky/pre-push
For some reason I merged #1479 as it had all green ticks, but some lines in the husky hooks have been deprecated and no longer work https://github.com/typicode/husky/releases/tag/v9.1.1
and need to be removed
Breaking CI
> Fix husky hooks

- .changeset/seven-yaks-ring.md
- src/insert/spacefinder/rules.ts
- src/insert/spacefinder/spacefinder.ts
avoid h3 the same as we do for h2's
I've spotted `h3`'s in the wild that are not being avoided since #1458, I think a `data-spacefinder-role="heading"` might be more suitable but can follow up with that.
> spacefinder should avoid h3's

- .changeset/empty-icons-mate.md
- playwright/lib/util.ts
- src/core/messenger/passback.ts
Adds a new Passback handler for the vendor Ogury which runs in the mobile-sticky slot.
- added a decideSizes function based on the source of the passback being Teads or Ogury
- passback.ts will now disable refresh of the parent slot as mobile-sticky refreshes by default
> Ogury passback for mobile sticky slot

- src/commercial.ts
- src/elements-manager/elements-manager.ts
- src/elements-manager/find-creative.test.ts
- src/init/consentless/define-slot.ts
- src/init/elements-manager.ts
_Merging into #1470 not main_
Only run elements manager if the opt out response is empty or if the url param `forcegem` is present
> [GEM] Only fill slot via gem if opt out response empty

- .changeset/lovely-seas-knock.md
- src/experiments/ab-tests.ts
- src/experiments/tests/opt-out-frequency-cap.ts
- src/init/consentless/prepare-ootag.ts
- src/types/global.ts
Add opt out frequency capping behind a 0% test
Switch PR here https://github.com/guardian/frontend/pull/27377
Opt out would like to review it, it's also not working as far as I can see, so hopefully they can shed some light!
> Add opt out frequency capping behind test for debugging

- .github/dependabot.yml
Move some of the groups into the devDependency group
There's still an unwieldy amount of PRs being raised by dependabot
> Refine dependabot.yml

- .changeset/silly-cobras-grab.md
- src/core/lib/video-interscroller-progress.ts
- src/core/messenger/background.ts
Log interscroller via logs as well as via commercial metrics
We're not getting the volumes of progress data that we expect, this could be due to the way that metrics is initialized in DCR, via an island that may not run due to the adaptive site mechanism.
> Record interscroller progress with logs and metrics

- .changeset/gold-rules-joke.md
- src/core/messenger/background.ts
- src/events/render-advert-label.spec.ts
- src/events/render-advert-label.ts
- src/events/render-advert.ts
This PR is part of a bigger project to remove the Native ad-labels at inception from commercial templates: related PR.
Currently the logic which decides if an label should be rendered lies here in the Commercial bundle. This logic will applies a `data-label-show='true'` class attribute to the `adSlotNode`.
This will enable the CSS set out in [DCR](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/components/AdSlot.web.tsx#L118), to apply the ad label styling.
The AdSlots are added to the article server-side rendered (in DCR). The CSS for rendering the Ad label is also server-side rendered and targets .ad-slot[data-label-show='true']:not(.ad-slot--interscroller)::before.
The commercial bundle dynamically adds the data-label-show='true' attribute, handled by the …
> conditionally render ad labels with data-show-label attribute

- .changeset/sharp-melons-flash.md
- src/init/consentless/prepare-ootag.ts
it's not needed as capping is available in the opt out UI.
> remove debug_forceCap from the frequency cap test

- .changeset/twenty-singers-deliver.md
- src/core/lib/video-interscroller-progress.ts
- src/core/send-commercial-metrics.ts
There are way more progress reports than impressions, hopefully recording the `pageviewId` will uncover if we're getting duplicates
This code only executes when googletag is already loaded but for safety/paranoia have added the same consent check that commercial metrics uses.
> Add pageviewId to video progress logs behind consent check

- .changeset/blue-wombats-wave.md
- src/experiments/tests/optimise-spacefinder-inline.ts
- src/insert/spacefinder/rules.ts
Adds some potential spacefinder optimisations for the desktop inline1 slot behind a 0% test. This rule set has some pretty large margins that we're convinced need to be so cautious. We want to AB test these changes to see if they boost ad ratio, so we're popping them behind a 0% test for now.
More detailed examples of each change are given below.
These are currently avoided in exactly the same way as an inline image, which seems overly strict. By relaxing the rules we can improve the placement of inline1 significantly and it still looks fine.
No inline1 appeared on this whole article because the paragraphs were considered too close to the rich link
Inline1 appears, and I think this looks absolutely fine with the rich link still
Rule changes now mean that ads can appear underneath …
> Add Spacefinder inline1 desktop margin changes behind a 0% test

- .changeset/shy-crabs-travel.md
- src/init/consentless/dynamic/article-body-adverts.ts
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/rules.ts
Adds a bigger `desktopRightRailMinAbove` for consentless ads.
We've been seeing opt out inline2 ads overlapping the most viewed column, and this should fix it. The overlapping happens whenever an ad doesn't fill inline1, and the inline1 slot collapses. This happens pretty frequently for consentless ads.
> Add a bigger rail min above for consentless ads

- playwright/fixtures/pages/articles.ts
This PR increases the `expectedMinInlineSlotsOnDesktop` value to reflect the increase in the inline ad slots.
This related to the PR opened in [DCR](https://github.com/guardian/dotcom-rendering/pull/12142)
This change might be attributed to Spacefinder’s algorithm potentially being more lenient in its calculations regarding the spacing between ads.
| Test passing with 12 inline slots | Test failing with 13 min/max no. slots |
| <img width="1274" alt="Screenshot 2024-08-14 at 17 20 11" src="https://github.com/user-attachments/assets/36ae0f3b-bb59-44b4-a666-f4a44797c13e">| <img width="1279" alt="Screenshot 2024-08-14 at 17 20 48" src="https://github.com/user-attachments/assets/63a2d733-2aea-490e-83eb-1b887fe31fba"> |
> increase min inline slots for desktop

- .changeset/bright-bobcats-lie.md
- src/core/lib/video-interscroller-progress.ts
Wraps `sendProgress` in `once()`.
This should mean it only gets executed once. At the moment, we think it can be called twice by the two different event listeners. Hopefully this should reduce the duplicate log entries we see.
> Only execute sendProgress once

- src/init/consentless/dynamic/article-body-adverts.ts
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/rules.ts
- src/insert/spacefinder/spacefinder.ts
Merge the `addFirstInlineAd` and `addSubsequentInlineAds` functions into one function.
Now that inline-merch has been deleted, we no longer need to separate the code to add inline ads into inline1 and subsequent inlines. This results in less lines of code and things being a bit easier to read.
> Merge first and subsequent inline ad functions

- .changeset/seven-zoos-thank.md
- src/core/lib/video-interscroller-progress.ts
- src/core/messenger/background.ts
Log line item id as well as creative id for interscroller video progress tracking
Stop reporting via commercial metrics and rely soley on the logging endpoint
DAP want to run reports based on the line item id
> Log line item id as well as creative id for interscroller video progress tracking

- .changeset/dirty-otters-trade.md
- src/experiments/tests/optimise-spacefinder-inline.ts
- src/insert/spacefinder/rules.ts
Sets the Spacefinder inline1 margins optimisation test to 5% as recommended by D&I. Also updates the richLink bottom margin to 50px to look better on tablet display.
It's time for the test to go live.
> Set Spacefinder inline1 optimisation test to 5%

- src/elements-manager/find-creative.ts
Adds an if statement to the `pickLineItem` function to return the highest priority line item if there is a sponsorship or takeover targeting the page.
This will make sure that GEM respects takeover campaigns when they're eligible to serve, instead of serving another advert.
> Return highest priority line item if it has a priority of 4 or less

- .changeset/silly-spoons-serve.md
- src/insert/spacefinder/rules.ts
Adds rules for richLink and thumbnail for mobile devices.
I split out richLink and thumbnail opponents into their own selector in this PR https://github.com/guardian/commercial/pull/1517/files#diff-9927c8b2a268d783c13c5a6b48574f33753beefe080178bc7a5e199b53fe48a6R32 but forgot to add that new selector for mobile rules as well.
> Add richLink and thumbnail back into mobile Spacefinder rules

- .changeset/witty-falcons-camp.md
- src/insert/spacefinder/rules.ts
- src/types/global.ts
Check for videos as well as images before increasing the min above for inline2.
Articles with no images can still have a video, which means we don't need the extra buffer on the min above for inline2. By checking if we have a video atom, we should be able to improve ad ratio a bit on articles with videos but no images.
> Check for videos as well as images when setting inline2 min above

- .changeset/great-humans-approve.md
- src/insert/spacefinder/rules.ts
Add an extra 100px to minAbove for articles with video but no images.
On some articles with video but no images, the inline2 ad was overlapping with most viewed at certain breakpoints. I could only replicate on one article of this type at one breakpoint, so hopefully 100px should be enough.
Before:
After:
> Adjust minAbove for articles with video but no images

- .changeset/bright-beans-train.md
- .changeset/mean-items-attend.md
- playwright/fixtures/pages/Page.ts
- playwright/fixtures/pages/articles.ts
- playwright/fixtures/pages/blogs.ts
- playwright/tests/article-inline-slots.spec.ts
- playwright/tests/liveblog-ad-limit.spec.ts
- playwright/tests/liveblog-inline-slots.spec.ts
- src/insert/spacefinder/article.ts
- src/insert/spacefinder/rules.ts
- src/insert/spacefinder/spacefinder-debug-tools.ts
Tablets should use the mobile spacefinder pass/rules as all ads are inserted inline, like they are on mobile.
I had to add specific ad count/positions to the e2e tests as although they're using the mobile rules, things will be in different positions due to text flowing differently in paragraphs etc.
The right rail pass should also be avoiding inline1, at the moment inline2 is way too close to inline1.
There are a few instances of ads being too close together that this will fix
<table>
<tr>
<td>Tablet
<td>Desktop
<tr>
<td><img width="613" alt="Screenshot 2024-08-27 at 16 05 12" src="https://github.com/user-attachments/assets/bc658a45-a7f7-406a-9cf0-d0ca6a27ffbe">
<td><img width="1261" alt="Screenshot 2024-08-27 at 16 04 45" src="https://github.com/user-attachments/assets/99ee365a-e44d-479f- …
> Fix spacefinder placing ads too close together on tablet & desktop

- src/__fixtures__/line-items-fixtures.json
- src/elements-manager/find-creative.ts
- src/elements-manager/line-items.spec.ts
- src/elements-manager/line-items.ts
- Adds a fixture file for a set of line items
- Adds unit tests for various aspects of targeting logic including device targeting
- Fixes a bug where if a line item's custom targeting parameters included an array of items to exclude, only the first item in the array was checked
- Moves the toggle for logging item selection logic decisions higher up the call stack (to make the tests less noisy)
> Add unit tests for GEM line item targeting logic

- .changeset/angry-books-look.md
- .github/workflows/beta-release-on-label.yml
This enables all members of the Guardian org to release beta versions of the commercial bundle.
Restricting beta release permissions only to repo admins is a little too narrow- sometimes it's useful for people outside the team to be able to make quick releases.
> Check user is a member of Guardian org for beta releases

- .changeset/breezy-dryers-worry.md
- package.json
- playwright/fixtures/prebid.ts
- pnpm-lock.yaml
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/utils.ts
Bump prebid to get new version without the smart module
Remove config for the smart SSP
No longer using it.
> Remove Smart SSP from our prebid config

- .changeset/odd-adults-hang.md
- src/experiments/ab.ts
- src/experiments/tests/opt-out-frequency-cap.ts
- src/init/consentless/prepare-ootag.ts
- src/types/global.ts
Add more variants to frequencyCap test for testing timeout
We would like to manually test the timeout values in prod
> Add more variants to frequencyCap test for testing timeout

- src/elements-manager/find-creative.ts
- src/elements-manager/line-items.ts
Uses delivery goal to select between competing line items with the same priority level if they have a sponsorship level priority. Line items with a higher delivery goal are prioritised, as a delivery goal of 100% is used when we're delivering a takeover.
I've tested this using a local json object by adding an extra fake line item with a lower delivery goal but same priority to make sure that the item with the highest delivery goal is selected.
> Handle competing sponsorships

- .changeset/rotten-apes-compare.md
- package.json
- pnpm-lock.yaml
- src/lib/detect/detect-breakpoint.ts
Bump source to 8.0.0
Also looks like typescript had accidently been updated to 5.6 by dependabot, putting it back for now
> Bump source to 8.0.0

- .changeset/red-bats-grow.md
- playwright/lib/util.ts
- src/core/ad-sizes.ts
- src/events/render-advert.ts
- src/insert/spacefinder/article.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/slot-config.spec.ts
- src/lib/header-bidding/slot-config.ts
This is a new size that run through pubmatic via prebid.js in the inline2 slot on articles.
The new size is not allowed to refresh, which is handled in the size callbacks; or display after a slot is refreshed which is handled by negatively targeting the `refreshed` custom targeting param.
New line items have been set up in Ad Manager.
> Add new 371x660 prebid size

- .changeset/tame-cheetahs-fry.md
- package.json
- pnpm-lock.yaml
Remove `commercial/api/hb` endpoint via an update to `@guardian/prebid.js@8.52.0-6`
See:
https://github.com/guardian/Prebid.js/pull/159
https://github.com/guardian/platform/pull/1625
https://github.com/guardian/frontend/pull/27506
The `/hb` endpoint powers the header bidding dashboard in Frontend but it is no longer used so we can remove all associated code.
> Remove `commercial/api/hb` endpoint via `@guardian/prebid.js@8.52.0-6`

- .changeset/swift-jars-drop.md
- src/core/index.ts
- src/init/consented/messenger.ts
- src/init/consentless.ts
- src/lib/header-bidding/prebid/improve-digital.spec.ts
- src/lib/header-bidding/prebid/magnite.spec.ts
Removes unused exports from the commercial repo.
This is a hangover from when `commercial-core` and `commercial` were two separate libraries and we would export from core into commercial. Since merging we can now remove any exported functions which were just for internal sharing and not used by other repositories.
I based the exports that we should keep on this search:
https://github.com/search?q=org%3Aguardian+%40guardian%2Fcommercial&type=code&p=1
Exports required for atoms-rendering were ignored as that is an archived project.
> Remove unused exports

- .changeset/tender-wasps-worry.md
- package.json
- pnpm-lock.yaml
Temporary downgrade to @guardian/prebid.js@8.52.0-6 so we don't make requests to /hb while we put back the backend routes
> Temporary downgrade to @guardian/prebid.js@8.52.0-6

- .changeset/nervous-planes-attend.md
- src/init/consentless/define-slot.ts
- src/init/consentless/render-advert-label.ts
Move to using a generic 'NOLABEL' tag that can be added to opt out templates that we don't want an ad label added to.
The previous approach of adding a template specific label was unsustainable and would have meant a code change for every new template we add to opt out.
> Don't add label when NOLABEL tag is present

- .changeset/quiet-buses-tell.md
- package.json
- pnpm-lock.yaml
Bumps Prebid version to start sending Prebid data to the commercial/api/hb endpoint again.
We temporarily downgraded yesterday so that we could release the MSPS changes without them being tied up with this work.
> Upgrade prebid again after temporary downgrade

- .changeset/angry-boats-relax.md
- src/init/consented/prepare-permutive.ts
Respect permutive switch for `prepare-permutive`
We respect the switch for loading the [permutive script](https://github.com/guardian/commercial/blob/cc2714570fa248ac298aa3875dd8e5116188585a/src/init/consented/third-party-tags.ts#L85-L87) but but not for initialising permutive segments.
This change adds a check of the permutive switch for initialisation of permutive segments.
> Respect permutive switch for `prepare-permutive`

- .changeset/modern-brooms-yawn.md
- src/core/targeting/youtube-ima.spec.ts
- src/core/targeting/youtube-ima.ts
Adds the article URL to the youtube IMA ad request, by adding the description_url parameter. It seems pretty common practice from what I've read online to use the URL of the page that the video is loading on as the description url. Also updates tests to make sure the request URL is constructed as expected.
This is used to determine if the domain is eligible for ads to serve. See [here](https://support.google.com/admanager/answer/1734048?hl=en#:~:text=video%20ad%20inventory.-,The%20description%20URL,-For%20Ad%20Exchange) for more info.
I've tested on CODE, and we get ads loading before the video as expected:
And we can see description_url getting added to the payload:
> Add description_url to IMA ad requests

- src/lib/header-bidding/prebid/prebid.ts
Adds a comment to describe what the prebidPermutiveAudience switch is used for.
It wasn't immediately clear looking at the code what the difference between the permutive switches was - hopefully this makes things clearer in the future.
> Add comment to explain what prebidPermutiveAudience switch is for

- .changeset/empty-ghosts-film.md
- src/lib/header-bidding/utils.ts
This adds logic to the mobile-sticky banner to appear on Interactives outside of the UK
As part of the process to allow for mobile sticky ad banners to be available in Interactives as well as Articles
https://www.theguardian.com/us-news/ng-interactive/2024/oct/30/election-harris-trump-myths-lies-fact-checkfalse-claims-include-that-noncitizens-are-voting-in-broad-numbers-and-attacks-on-the-voting-and-counting-process
Having set VPN to AUS/US vs Uk to see the difference.
To ensure loading of mobile sticky in testing you can use `?adtest=mobile_sticky_test`
https://github.com/user-attachments/assets/0a6c6491-60aa-4ffc-9a4c-2838e5bd4cf6
> add sticky banner to interactive articles

- .changeset/eight-tools-press.md
- src/init/consentless/init-fixed-slots.ts
Filter out the static top-above-nav slot on mobile DCR when defining consentless fixed slots.
At the moment, two top-above-nav slots get defined - the static one, and the dynamically inserted mobile top-above-nav. The styling and ad label logic is currently being applied to the static slot, not the dynamic one, causing display issues. Filtering out the static slot so that we don't have duplicate definitions mirrors the logic for consented ads, and makes sure the label and extra classes are applied as expected.
> Don't define static top-above-nav on consentless mobile DCR

- .changeset/ten-penguins-play.md
- src/lib/header-bidding/a9/a9.ts
- src/types/global.ts
Block GumGum on fronts
They keeps serving interscrollers on Fronts which we don’t want
> Block GumGum on fronts

- .changeset/cyan-boats-joke.md
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/utils.ts
Re-enables Criteo for Australia and New Zealand as requested, and updates the bid-config tests accordingly.
I tested locally using a VPN and requests are being sent as expected:
> Enable Criteo in Australia and New Zealand

- playwright/lib/gam.ts
Fixes [https://github.com/guardian/commercial/security/code-scanning/1](https://github.com/guardian/commercial/security/code-scanning/1)
To fix the problem, we need to escape the `.` character in the regular expression to ensure that it matches only the intended host (`securepubads.g.doubleclick.net`). This can be done by replacing the `.` with `\.` in the regular expression. This change will prevent the regular expression from matching unintended hosts and ensure that it only matches the exact host specified.
The specific change required is in the file `playwright/lib/gam.ts` on line 3. We need to update the regular expression to escape the `.` character before `doubleclick.net`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 1: Incomplete regular expression for hostnames

- .github/workflows/stale.yml
Adds a workflow to mark PRs as stale after 30 days of inactivity
Less noise
> Stale workflow

- .changeset/rare-pants-jump.md
- package.json
- pnpm-lock.yaml
- src/experiments/ab-tests.ts
- src/experiments/tests/new-header-bidding-endpoint.ts
- src/lib/header-bidding/prebid/prebid.ts
Adds a second endpoint for prebid analytics that is behind a 0% test.
To get a small amount of data in the new table to compare with the current data.
> Setup test for new prebid analytics endpoint

- .changeset/curvy-ads-scream.md
- docs/ab-testing/readme.md
- src/core/lib/ab-localstorage.ts
- src/experiments/ab-url.ts
- src/experiments/ab.ts
This used to work, evidenced by the fact that `ab-localstorage.ts` already existed, and broke at some point.
I'm not sure how leaving the test used to work but have modified slightly to allow leaving by clearing the variant e.g. `http://localhost:3030/Front/https://www.theguardian.com/uk#ab-yourTest=`
It's quite useful for the test to persist between pageviews.
> Fix persisting of forced ab test to localstorage

- .changeset/large-emus-sin.md
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/bid-config.ts
This PR adds `keywords` param to Sonobi prebid, a US prebid adaptor. `keywords` in the page config is a string but Sonobi wants an array of strings.
It's tested locally and it works as you can see from the screenshot 
This was a request made by Sonobi prebid so that buyers can make better informed bidding decisions.
> Add `keywords` param to Sonobi prebid

- .changeset/lemon-nails-drop.md
- package.json
- pnpm-lock.yaml
This dependency has turned up in the dependency tree on Frontend as it's in the dependencies list, however we think this is a dev dependency so we have moved it accordingly.
> Moving changesets to dev dependencies

- .changeset/short-beers-pay.md
- src/experiments/tests/new-header-bidding-endpoint.ts
Start gathering data from real users on the new endpoint, 
note: This is in addition to the current method not instead of, the old method will be turned off once this ramps up to 100%.
See https://github.com/guardian/gcp-iac-terraform/pull/984
> Increase new header bidding endpoint rollout to 1% of users

- .changeset/cool-turtles-grab.md
- src/insert/spacefinder/rules.ts
Adds elements with the role 'halfWidth' to the list on inline elements that Spacefinder avoids inserting ads next to.
At the moment Spacefinder doesn't know we should avoid these elements, and ads look terrible next to them.
> Avoid putting ads next to halfWidth elements on the page

- .changeset/giant-toes-tease.md
- src/lib/header-bidding/prebid/bid-config.ts
We are adding a new placementID to the Pubmatic custom ad-size[371x660]
Currently we have a a prebid  ad  partner - `Pubmatic` which runs globally.
We would like a US specific integration keeping the existing placement ID for all other countries.
Logic has been added to deliver a specific placement ID customised for US `seenthis_guardian_mweb_us`
We are continuing to deliver the existing placement id `seenthis_guardian_371x660_mweb` for the rest of the world.
This will allow fine-tuned targeting, better performance in the market market, and compliance with regional needs.
| Professor prebid:`Pubmatic` - dfp-ad-inline2 US (VPN)   |
|----------|
| <img width="1100" alt="Screenshot 2024-11-20 at 12 57 46" src="https://github.com/user-attachments/assets/5945ab62-6b9c-4f44-8e1b-705e2bc4bfd2"> …
> add pubmatic placement id for US

- .changeset/sharp-cherries-lay.md
- package.json
- pnpm-lock.yaml
Update to `@guardian/libs@19.2.1`
To bring in this fix:
https://github.com/guardian/csnx/pull/1804
> Update to `@guardian/libs@19.2.1`

- playwright/tests/liveblog-ad-limit.spec.ts
- playwright/tests/liveblog-live-update.spec.ts
Update `liveblog-ad-limit` e2e test to reduce flakiness.
On inspection it looks like its possible for `window.mockLiveUpdate` to be undefined until the `Liveness` island is hydrated and the function is set on the window.
Adding a wait on `window.mockLiveUpdate` to be defined should remove this corner case.
> Unskip liveblog-ad-limit test

- .changeset/nine-yaks-type.md
- src/lib/commercial-features.ts
Allow ads to show in the right column on the [football live page](https://www.theguardian.com/football/live). 
Follow on from #1379
> Show ads in right column of football live page

- .changeset/five-owls-obey.md
- package.json
- pnpm-lock.yaml
- src/lib/header-bidding/prebid/prebid.ts
Stop logging to both endpoints and just log to the new endpoint that's been receiving 100% of data as of #1676
The new endpoint has been working great over the last few weeks.
See https://github.com/guardian/gcp-iac-terraform/pull/984 for details.
> Disable old prebid analytics endpoint

- .changeset/tidy-grapes-judge.md
- src/core/targeting/youtube-ima.spec.ts
- src/core/targeting/youtube-ima.ts
Add `plcmt` to IMA targeting
This is a new-ish parameter required for video ads - https://support.google.com/admanager/answer/10655276?ref_topic=10684636&sjid=18321668743419539961-EU#plcmt
This also needs to be done for outstream ads but we're unsure about implementation details, we're asking google for clarification.
> Add `plcmt` to IMA targeting

- .changeset/pretty-feet-worry.md
- src/insert/article-aside-adverts.ts
- src/insert/high-merch.ts
Adds `amIUsed` calls to see if some modules we have to handle ads on frontend are still needed. Also does some more granular logging in `article-aside-adverts` to see if both conditional blocks are still needed, in case we might be able to reduce the code down.
We last checked these modules a couple of years ago and we've had more migrations since, so we're checking if these bits of code are still needed.
> Add amIUsed calls to see if modules are still needed

- .changeset/polite-ghosts-guess.md
- src/lib/header-bidding/prebid/prebid.ts
Sample prebid analytics unless in a test
There's no sampling at the moment, 100% of analytics are sent and recorded, this is a huge amount as there is a prebid auction every time an ad is displayed on the page.
We asked D&I if we could sample these which will reduce the amount of requests in users browsers and amount of data generated that needs processing, and they have said that 10% would be enough to be able to perform analysis effectively.
> Sample prebid analytics at 10%

- src/experiments/tests/gpid-prebid.ts
This PR extends the expiry of the GPID test to the end of January. Associated with PR: https://github.com/guardian/commercial/pull/1651
To collate more meaningful data from the experiment.
> extend expiry of gpid test to end of January

- .changeset/warm-donuts-yawn.md
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/appnexus.spec.ts
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/prebid/prebid.spec.ts
- src/lib/header-bidding/utils.spec.ts
- src/lib/header-bidding/utils.ts
This PR removes the Sonobi SSR (Server-Side Rendering) integration from the Prebid configuration. The following changes have been made to achieve this:
1. **Removed Sonobi Bidder Configuration:**
Deleted all references to the Sonobi bidder from the Prebid configuration files.
Removed Sonobi-specific parameters and targeting logic.
2. **Updated Bidder Imports:**
Removed Sonobi-related imports from the relevant modules.
3. **Cleaned Up Bidder Code:**
Ensured that any Sonobi-specific code, including bid requests and response handling, has been removed.
4. **Updated Documentation:**
Updated any relevant documentation to reflect the removal of the Sonobi bidder.## Why?
Sonobi has been determined to be not be worthwhile supporting. Let’s remove the SSP and all associated code.
Sonobi has been …
> Remove Sonobi SSP from Prebid Configuration

- playwright/benchmark/test-ad-load-time.spec.ts
This broke when changing to riff-raff deployment as the prod bundle build location has moved.
> Fix ad speed benchmarking

- src/experiments/ab-tests.ts
- src/experiments/tests/prebid-keywords.ts
- src/lib/header-bidding/prebid/prebid.ts
Adds page keywords to the Prebid config following the docs [here](https://docs.prebid.org/features/firstPartyData.html#:~:text=hints%20are%20used.-,Supplying%20Global%20Data,-Here%E2%80%99s%20how%20a).
The change has been added behind a 50% test so that we can measure any impact this may have on revenue. I've offset the test to make sure that it doesn't overlap with the RegionSpecificPrebid test.
We want to try adding keywords to our Prebid config to help make sure programmatic ads can target our pages properly. Our current implementation for adding keywords for Magnite is out of date for our current Prebid version, so we need to update how we do this.
Once the test is complete, if we want to go ahead with adding keywords this way, we can remove the current keyword implementation for …
> Add keywords to pbjsConfig if user is in the prebidKeywords test

- src/code-structure.md
A document that explains the current codebase structure
Helps new joiners to the team.
@dskamiotis @deedeeh @cemms1
> Doc explaining the codebase structure

- .prout.json
We're getting overdue comments, but I suspect this is just because the prout URL with the commit hash is cached by fastly, increasing to 30 minutes until a better solution can be found.
> Increase prout overdue time

- src/lib/header-bidding/prebid/prebid.ts
Adds keywords as an array to `site.ext.data`. I'm adding it under the existing test so that we can measure the combined revenue impact.
Magnite require the keywords to be sent via `site.ext.data` in order to use them for targeting.
> Also add keywords to site.ext.data

- riff-raff.yaml
Configure riff-raff to set the max-age of the prout file to 0
Checked on CODE:
prout file
All other files still have very large max-age
And curl:
```
> curl -I https://assets-code.guim.co.uk/commercial/prout
HTTP/2 200
x-amz-id-2: TG5pKLzK0faqoebnXK8armIsUvY71SwKZP/ux4z/xCw1TsnTAyHH4jn88+mGqZx+D4k2a5t7Z9KGRcxN1uyY9A==
x-amz-request-id: BMMZ56W5E3M1SATF
last-modified: Fri, 17 Jan 2025 10:34:07 GMT
etag: "5bfbe965af71978abdbd50d7dae58c61"
x-amz-server-side-encryption: AES256
cache-control: max-age=0
x-amz-version-id: JrmuvoRqyHwdYH4.zE23dk9719WvJwhK
content-type: application/octet-stream
server: AmazonS3
fastly-restarts: 1
accept-ranges: bytes
date: Fri, 17 Jan 2025 10:58:27 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-lhr-egll1980087-LHR
x-cache: MISS
x-cache-hits: 0
x-timer: …
```
> Reduce prout cache control max age

- .changeset/thick-camels-grin.md
- src/insert/spacefinder/rules.ts
Increases the margin added to the base value for the inline2 min above on showcase articles or articles that have video as the main media.
A few long headlines in the Most Viewed component caused inline2 to overlap with Most Viewed on one article. Increasing the value of this margin eliminates the overlap.
I have added a ticket to Trello to investigate if we can handle this better, we do a few too many of these types of PRs!
| ------------- | ------------- |
| <img width="416" alt="Screenshot 2025-01-22 at 15 47 13" src="https://github.com/user-attachments/assets/79593746-66d7-4f6d-b5a6-d56b38bbb00a" /> | <img width="345" alt="Screenshot 2025-01-22 at 16 47 32" src="https://github.com/user-attachments/assets/d2d363be-9add-4900-98c4-554958f61eb3" /> |
> Increase margin for most viewed on Showcase articles

- src/init/consented/remove-slots.ts
On the first page view where for ad free users but where the ad free cookie hasn't been set yet or has expired and not been renewed yet. Slots aren't hidden server-side, and need to be removed client side.
There's reports of the fronts-banners not being hidden in some circumstances, this could be the cause.
> Add `.top-fronts-banner-ad-container` to elements removed by removeSlots

- src/experiments/tests/prebid-keywords.ts
Extends the `PrebidKeywords` test for another month.
We want to run this test for a bit longer to understand the revenue impacts.
> Extend prebid keywords test

- .changeset/sour-chairs-clean.md
- package.json
- pnpm-lock.yaml
- src/experiments/ab-tests.ts
- src/experiments/tests/ttd-prebid.ts
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/bid-config.spec.ts
- src/lib/header-bidding/prebid/bid-config.ts
- src/lib/header-bidding/prebid/prebid.ts
- src/lib/header-bidding/utils.ts
Adds new config for new prebid bidder The Trade Desk.
The line-items have already been setup. And I've tested that the new module is requesting bids.
This is behind a 0% test for the commercial and the trade desk folks to test also.
> Add The Trade Desk to prebid

- src/init/consented/dynamic-ad-slots.ts
- src/init/consented/third-party-tags.ts
This is a small refactor of unnecesary use of `await` in module loading/initialisation code.
This is unlikely to have any significant performance impact, but improves code quality- `await` should only be used when we actually *need* to wait for the result of an asynchronous function call in order to proceed with the following code.
> Refactor out some unnecessary awaits in module loading code

- .changeset/moody-kangaroos-kick.md
- src/lib/third-party-cookies.ts
It's causing whitespace at the bottom of the page and it should not be visible!
> Hide the third party cookie detection iframe

- playwright/benchmark/cmp-accept-all.setup.spec.ts
- playwright/benchmark/cmp-reject-all.setup.spec.ts
- playwright/fixtures/breakpoints.ts
- playwright/fixtures/pages/articles.ts
- playwright/fixtures/pages/blogs.ts
- playwright/fixtures/pages/fronts.ts
- playwright/fixtures/pages/index.ts
- playwright/tests/article-inline-slots.spec.ts
- playwright/tests/liveblog-ad-limit.spec.ts
- playwright/tests/liveblog-inline-slots.spec.ts
- playwright/tests/liveblog-live-update.spec.ts
- playwright/tests/targeting.spec.ts
use `as const` and `satisfies` to improve type safety
This lets us remove several assertions.
This revealed an error in the first `liveblog-inline-blog.spec.ts` test, the filtering at the start conflicted with a check in the test resulting in the test not actually running!
The number of ad slots on the test blogs in that test has changed on tablet, I've updated the test as this was changed a while ago in https://github.com/guardian/commercial/pull/1550
> Improve playwright fixture types and fix liveblog test

- playwright/tests/prebid.spec.ts
- src/lib/header-bidding/prebid-types.ts
- src/lib/header-bidding/prebid/prebid.ts
Expand our e2e tests to better verify prebid is running correctly.
checks include:
* That the prebid.js script is loaded
* That bids are requested for our bidders
* That no bidderErrors occur, excluding timeouts as these are fairly common and unlikely to be because of our own code.
Confidence when making changes to prebid
> Improve E2E testing of prebid

- .github/workflows/compressed-size-action.yml
Adds the compressed size action to pull request workflows.
We've recently made some changes that have reduced the bundle size (eg. removing unused Prebid adapters) and this action will give us immediate feedback on future PRs to help quantify the impact of a change on the bundle size.
I temporarily downgraded the Prebid version to 9.27.0 on this branch, and the compressed size action showed that doing that resulted in an increase in bundle size, as the previous version includes extra adapters.
> Add compressed size action

- src/init/consentless/init-fixed-slots.ts
This removes the top-above-nav slot at the tablet breakpoint in the consentless flow.
Since we cannot pass ad sizes to OptOut in the same way as we do Google, the top-above-nave ad in this slot was served at desktop breakpoint size, causing horizontal scroll. The proportion of unconsented users on a tablet browser is extremely small (and likely to become smaller with consent or pay), so simply removing the slot as we do on mobile is a simpler solution than either trying to implement tablet top-above-nav ads in OptOut, or adding styling to cut off oversized ads with possible knock-on effects on consented advertising.
**Before**
**After**
> Remove top-above-nav at tablet breakpoint on consentless

- src/lib/header-bidding/prebid/prebid.spec.ts
- src/lib/header-bidding/prebid/prebid.ts
Adds page keywords to `ortb2.site.ext.data` in the Prebid bid config. Example of how this looks:
Magnite and Index access keywords through `ortb2.site.ext.data`, and these are the bidders that we want to receive keywords. We're not adding keywords to `ortb2.site` because there is no revenue benefit.
> Add keywords to ortb2.site.ext.data in Prebid config

- src/experiments/ab-tests.ts
- src/experiments/tests/the-trade-desk.ts
- src/lib/header-bidding/utils.ts
Test setup to disable the trade desk for 5% of users
We forgot to do this when we added the trade desk, we'd like to know the impact that this partner is having.
> Disable the trade desk for 5% of users

- src/experiments/tests/defer-permutive-load.ts
This PR adds the `Permutive` delay script behind an ab test.
We are placing the feature behind a test for 10% of control and 10% variant.
Related [PR](https://github.com/guardian/commercial/pull/1783)
We would like to be able to detect a 5% improvement in the `top-above-nav_firstAdOnPage`, testing for 16 days.
> add permutive delay init behind 10% test

- src/lib/header-bidding/prebid/prebid.ts
- src/lib/header-bidding/prebid/price-config.spec.ts
- src/lib/header-bidding/prebid/price-config.ts
- src/types/modules.d.ts
Restore width/height price bucketing for ozone and index
This can be done by overriding the `hb_pb` targeting for these bidders rather than modifying the prebid source code.
https://docs.prebid.org/dev-docs/publisher-api-reference/bidderSettings.html
Added test cases for this.
This was accidently removed when I [deprecated our custom prebid](https://github.com/guardian/commercial/pull/1737) `@guardian/prebid` (it wasn't in the readme but I should have checked!)
We had added `guCustomPriceBuckets` long ago in https://github.com/guardian/Prebid.js/pull/126 which allowed us to set the priceBuckets based on the creative size.
Now this can be done without needing to modify the prebid.js source code as mentioned above.
The background on this is that we have different a price bucket for these …
> Fix prebid ozone/index/criteo custom price bucketing

- src/experiments/tests/prebid-bid-cache.ts
This PR fixes the expiry date for the `prebidBidCache` test that was done in https://github.com/guardian/commercial/pull/1839
We aren't getting the data through into the data lake.
> Fix expiry date for `prebidBidCache` test

- src/experiments/tests/the-trade-desk.ts
Fix expiry date for the test in #1864 :S
It's not 2024 anymore
> Fix the trade desk test expiry

- src/experiments/ab.ts
- src/lib/header-bidding/prebid/prebid.ts
- src/types/global.ts
Refactor `ophanRecord` function
Sentry is reporting that `window.guardian.ophan` is sometimes undefined here, perhaps not loaded yet or could be blocked so changing it to be optional.
We're also wrapping the ophan functions just for logging purposes that we don't really need, we can tidy it up.
I've also added a simple queue so that all events will be sent if ophan becomes available the next time it tries to record.
> Improve ophan record of test events

- src/lib/targeting/build-page-targeting.ts
Checks consent state for `googletag` instead of `consentState.canTarget` before adding the `firstvisit` custom targeting value for opt out ads.
This is because we check the consent for `googletag` before launching opt out ads, not `canTarget`, so by checking the same consent permissions, we can make sure the targeting is reliably added. I think following consent or pay, there's some misalignment between these consent permissions, which means in the UK the `firstvisit` targeting value is not currently being sent.
> Make sure firstvisit targeting is added for opt out ads

- src/define/define-slot.ts
Adding a stringify just to make sure this isn't a weird sentry encoding issue
This is reporting weird sizeMappings such as:
```
{"desktop":["[o]","[o]","[o]","[o]","[o]","[o]","[o]","[o]"],"mobile":["[o]","[o]","[o]","[o]","[o]","[o]"],"tablet":["[o]","[o]","[o]","[o]","[o]"]}
```
> stringify the sizemapping for the reportError

- src/define/create-advert.ts
- src/define/define-slot.ts
Errors are reported from `createAdvert` only.
Stop wrapping errors in a new error, it's unnecessary and the `Could not create advert` prefix makes it harder to see the actual error.
Created a new `DefineSlotError` that is thrown from `defineSlot` and handled in create-slot.
The shim detection added in #1887 appears to be most cases - so we can silence these errors, and still report if sizeMapping creation failed for another reason.
The messages coming from this area are a little all over the place.
> Tidy up error handling when creating an advert

- src/experiments/tests/defer-permutive-load.ts
Extends the expiry for the `DeferPermutiveLoad` AB test to ensure we get the desired volumes, for analysis.
> extend permutive test expiry

- .changeset/better-rules-prove.md
- package.json
- pnpm-lock.yaml
Bump @guardian/libs to 22.2.0
Required to bump version in Frontend and DCR
> Bump @guardian/libs to 22.2.0

- .github/dependabot.yml
This should prevent prebid.js being grouped with other dependency updates
We're a bit more tentative about updating prebid
> Exclude prebid.js from minor dependabot groups

- src/events/render-advert.ts
- src/experiments/ab-tests.ts
- src/experiments/tests/a9-bid-response-winner.ts
- src/lib/gumgum-winning-bid.ts
- src/lib/header-bidding/a9/a9.ts
- src/types/global.ts
This PR introduces functionality to log GumGum winning bids for Amazon advertisements. 
The implementation detects specific Amazon advertisement IDs and fetch bid responses (amznp ID) associated with GumGum, and sends this data to a logging endpoint. 
The logic is encapsulated in a newly created module: `gumgum-winning-bid.ts`
- The renderAdvert function checks if:
- The `advertiserId` matches the Amazon advertiser ID for GumGum (4751525411).
- The amznp ID in `window.guardian.a9WinningBids` equals 1lsxjb4.
- If the conditions are met, the `logGumGumWinningBid` function is called with:
- The ad slot ID (advert.node.id).
- The advertiser ID (slotRenderEndedEvent.advertiserId).
- The logging endpoint dynamically switches between development and production environments:
- Development: …
> Add GumGum winning bid logging for Amazon advertisements

- .changeset/brown-impalas-visit.md
- package.json
- pnpm-lock.yaml
Attempting to revert the libs version to 22.0.1
To match dcr and frontend.
> Revert libs version to 22.0.1

- src/lib/header-bidding/prebid/modules/analyticsAdapter.ts
Passes in the type of the first prebid event into the invalid analytics payload error to help with debugging. This is the data used by the code to check the validity of the payload, so it should help us see what the issue could be.
At the moment the Sentry logs aren't giving much helpful info as the payload isn't readable in the error. See the screenshot of the payload data in the Sentry error below:
> Add event type to invalid analytics payload error

- src/events/render-advert.ts
- src/lib/header-bidding/a9/a9.ts
We are us ign the AB test switch in frontend now, so no need for the feature switch to make the feature available.
Related [PR](https://github.com/guardian/commercial/pull/1898)
Now switching the AB switch on, will automatically opt in any forced URL's such as: http://localhost:3030/Article/http:/localhost:9000/sport/2023/nov/22/ronnie-osullivan-warns-he-will-quit-snooker-if-he-cannot-play-in-china#ab-A9BidResponseWinner=variant
As long as users are in the variant - we are initially at 0% to enable dev testing in PROD for the winning bid.
> remove redundant feature switch for a9 bidding winner

- src/lib/header-bidding/prebid/modules/analyticsAdapter.ts
Throw away `AbortError` errors, they happen when prebid times out the request for taking to long.
Tidy up sentry errors.
> Ignore analytics abort error

- src/insert/spacefinder/article.ts
This PR fixes the error we have for tablet breakpoint with slot id `dfp-ad--inline0` which doesn't exist. 
I tested it locally and in CODE and the error doesn't show up anymore. I also confirmed with the DOM element id.
Fix a slot id that shouldn't exist and reduce sentry errors.
> Fix slot id `dfp-ad--inline0` for tablet breakpoint

- .github/dependabot.yml
In theory this will allow package updates to trickle in, rather than a big wave once a week.
> try running dependabot daily

- src/experiments/ab-tests.ts
- src/experiments/tests/prebid-multibid.ts
- src/lib/header-bidding/prebid/pbjs.ts
- src/lib/header-bidding/prebid/prebid.spec.ts
- src/lib/header-bidding/prebid/prebid.ts
This PR adds the `multibid` feature to the Prebid config when in variant and `useBidCache` is switched on.
The `useBidCache` is switched on for some time now so `multibid` relies on the switch and the AB test when `userIsInVariant` is true.
`multibid` allows configured bidders to pass more than one bid per AdUnit through to the ad server when `useBidCache` is true. 
In order for `multibid` to work we need to include the module with Prebid.js. Check [Prebid docs](https://docs.prebid.org/dev-docs/modules/multibid.html). 
The Frontend related PR https://github.com/guardian/frontend/pull/27930
We want to test if `multibid` will have a revenue uplift for prebid bid caching or not. It was also recommended in Google meeting that happened few weeks ago to add this `multibid` feature to get the …
> Add `multibid` to prebid config and AB test

- src/experiments/tests/a9-bid-response-winner.ts
This PR extends the `a9BidResponseWinner` AB test.
> extend test expiry for a9BidResponseWinner

- playwright/fixtures/pages/articles.ts
- playwright/tests/collapse-slot.spec.ts
- src/events/empty-advert.ts
- src/events/render-advert.ts
- src/insert/comments-expanded-advert.ts
This changes our handling of the 2x2 'empty' ad size to treat them in the same way as we do slots where nothing is returned from GAM/OptOut, and changes the collapsing of any kind of empty slot to use `display: none` rather than removing elements from the DOM. It also adds Playwright tests for this code path.
We decided after some investigation that standardising around collapsing slots with `display: none` was more desirable for increased visibility. We also required tests for slot collapsing behaviour to help prevent a repeat of a regression in which slots for which no ad could be provided were not collapsed and remained as blank space on the page, but due to the differences in how genuinely empty ads and the 'empty' size were handled, it was not possible to test for how empty slots got …
> Unify handling of the empty ad size and actually empty slots

- src/insert/spacefinder/rules.ts
This PR updates the inlineOpponentSelector rule in Spacefinder to avoid having an ad just after an image. There is a rule already for images which is included under `data-spacefinder-role=inline` but in this case it's nested so we had to update the rule to include the `inline` role when it's nested.
| ![Screenshot 2025-05-06 at 16 33 10](https://github.com/user-attachments/assets/6ade967e-6938-4e57-ad93-54ed30164bd7) | ![Screenshot 2025-05-06 at 16 34 22](https://github.com/user-attachments/assets/ed53d01f-f599-40d6-b7c7-21caa480bab4) |
| ![Screenshot 2025-05-06 at 16 34 49](https://github.com/user-attachments/assets/c3e1737b-3fd7-41ef-8e98-23eb332757ca) | ![Screenshot 2025-05-06 at 16 35 …
> Update `inlineOpponentSelector` rule to include nested images

- src/lib/header-bidding/prebid/modules/analyticsAdapter.ts
This sends the full Prebid events array to Sentry when the first event is considered invalid and an error is reported.
We've had an elevated rate of errors being reported since this module was converted to Typescript in #1929. It's unclear as to what exactly is causing this, and whether the data causing the reports is in a genuinely unusable state. This change should give us more visibility to better understand the issue and what we ned to do to address it.
> Send full Prebid events array to Sentry when first event is invalid

- .changeset/neat-carrots-bow.md
- package.json
- pnpm-lock.yaml
Bump `@guardian/libs` to 22.4.0
So we can look-up the ID5 vendor in the `getConsentFor` function (see: https://github.com/guardian/csnx/pull/2076).
> Bump @guardian/libs to 22.4.0

- src/experiments/tests/prebid-id5.ts
Because when analysts spec a 1% test they mean 1% in each variant! 🙃
> Increase Prebid id5 test to 2%

- src/init/consented/messenger.ts
- src/lib/messenger.ts
- src/lib/messenger/video.ts
Add messenger handler for video progress reports, log them with the video progress reporting lib. These events will be sent from `fabric-video` and `fabric-video-xl` native templates.
I did try using a `video-init` event to setup the progress reporting, however it was firing before messenger has set up!
As the `sendProgressOnUnloadOnce` is wrapped in a `once` it can be added to the progress report event to setup the reporting the first time one is recieved.
So we can report video progress from fabric-video(-xl)
> Listen and report video progress messenger events

- pnpm-lock.yaml
This PR fixes the `pnpm-lock.yaml` by removing the duplicate brace-expansion subdependency which fails CI https://github.com/guardian/commercial/actions/runs/15607188273
Fix main branch.
> Remove duplicate brace-expansion to fix pnpm-lock

- src/experiments/tests/prebid-multibid.ts
This PR increases the `PrebidMultibid` test from 0% to 1% variant so in total 2% and it should take around 8 days to collect data. 
We want to retest multibid after the changes that has been done in the setup https://github.com/guardian/commercial/pull/2008 to be confident we don't have any negative impact before we make further changes to group slots and test it separately.
> Add 1% variant for 8 days to PrebidMultibid test

- src/lib/header-bidding/prebid/pbjs-v9.46.0.ts
- src/lib/header-bidding/prebid/pbjs.ts
- src/lib/header-bidding/prebid/prebid.ts
Since we switched to GPP in the US we haven't been passing consent to our prebid vendors for users there.
This wasn't a risk to us as we don't launch prebid without the requisite consent, but likely means our ad-tech partners may believe we’re not adequately collecting and/or passing consent on to them
Before:
After:
> Add `consentManagementGpp` module

- .github/workflows/ci.yml
Fix Build Core artifact path
The build path was incorrect causing changesets release not to work
> Fix core build path

- .github/workflows/ci.yml
It should run in the root of the monorepo
> Fix changesets publish command

- .changeset/grumpy-kids-clean.md
- bundle/src/lib/types.ts
- core/package.json
- core/src/types.ts
- pnpm-lock.yaml
Move `AdsConfig` types to `core`, I didn't notice they were used by frontend.
Also need to import the `googletag` ambient types in `core` and have it as a dependency rather than devDependency as the `Slot` type is used and exported there as part of the `Advert` interface.
Unfortunately there isn't a way to import/export just the `Slot` type as it's not a module.
I'm quite puzzled how I'm only noticing these now 🤔
To make frontend and DCR happy.
> Move more types to core

- bundle/src/experiments/tests/prebid-ad-unit.ts
This PR increases 0% to 2% in total (variant 1% and control 1%) for `PrebidAdUnit` test for 7 days which should allow use to check if grouping slots returns revenue with bid caching. 
We want to test if the grouping slots for Prebid bid caching is going to increase revenue as we will be able to use the same bid cache for subsequent slots.
> Add 2% for PrebidAdUnit test

- bundle/src/experiments/tests/prebid-ad-unit.ts
This PR extends the expiry date for the `PrebidAdUnit` test. The switch is off until we get back the results from D&I and then we will decide if we want to increase the test or remove it based on the outcome. 
Extend the expiry date to 1 week more as it might take longer than a week for the analysis.
> Extend `PrebidAdUnit` test 

- bundle/src/init/consented/prepare-googletag.ts
This PR fixes the logic for the AB test `disableChildDirected` so everyone can see the change except users in control. We want to set live 95% (97.5% with variant) and keep back 2.5%. 
This was suppose to be done in the previous PR https://github.com/guardian/commercial/pull/2185
> Fix logic `disableChildDirected` test 

- bundle/playwright/lib/allow-reject-all.ts
- bundle/playwright/lib/load-page.ts
- bundle/playwright/tests/consent.spec.ts
Use cookie to enable reject all instead of relying on region.
Consent or pay has rolled out in Europe, so we can no longer rely on the test simulating it's in Ireland for testing reject-all.
> Fix playwright reject all now that consent or pay has been rolled out in Europe
